- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterInstrumentedTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
Deleting a model with `@HasOne` or `@HasMany` with another model/s now also deletes data that belongs to it. This is in parity with JS.
> [DataStore] Implement delete cascade

- aws-datastore/src/main/java/com/amplifyframework/datastore/network/ModelMetadata.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/network/ModelWithMetadata.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/network/RemoteModelMutations.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/network/RemoteModelState.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/network/RemoteModelStateTest.java
Provides and observe() signature though which an actor can obtain
all current values of all models in an App Sync endpoint, by means
of k-many base syncs, for k, the number of models managed by the system.
> [DataStore] Create RemoteModelState class

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncApiTest.java
Removes three conditions which seem to be failing due to a difference in computer time vs. server time. Will create a more accurate test later.
> [DataStore] Removes condition from failing integration test

- aws-datastore/src/main/java/com/amplifyframework/datastore/network/DataHydration.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/network/DataHydrationTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/network/MockAppSyncEndpoint.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/network/ModelProviderFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/network/RemoteModelStateTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/network/TestModelWithMetadataInstances.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
DataHydrator consumes RemoteModelState's observe(). For each model
emitted on the Observable, the Hydrator populates the local data store
with the model data, and the metadata about that model.
> [DataStore] Add Data Hydrator

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterInstrumentedTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/GsonStorageItemChangeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/LocalStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/OperatorInterfaceAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/PredicateInterfaceAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/StorageItemChange.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlCommand.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlKeyword.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTable.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategory.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategoryBehavior.java
- core/src/main/java/com/amplifyframework/util/ArrayUtils.java
- core/src/main/java/com/amplifyframework/util/Immutable.java
Implemented conditional save on storage engine layer. Saving with predicate will only write to database if the data being overwritten meets the conditions.
* Overloaded `save` method in `LocalStorageAdapter`
* predicate parameter is `@Nullable` (internal use-case)
* inherited to `SQLiteStorageAdapter`, `InMemoryStorageAdapter`
* Overloaded `save` method in `DataStoreCategoryBehavior`
* predicate parameter is `@NonNull`
* inherited to `DataStoreCategory`, `AWSDataStorePlugin`
* Re-factored logic involved with binding values to pre-compiled SQL statement
* De-coupled the processing of an object for fields and binding procedure. Field extraction from object is now a separate utility method, and binding of values is a separate utility method. …
> [DataStore] Implement conditional save for Storage Engine

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLInstrumentationTest.java
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncApiInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/network/AppSyncApi.java
- testutils/src/main/java/com/amplifyframework/testutils/SynchronousApi.java
- testutils/src/main/java/com/amplifyframework/testutils/SynchronousDataStore.java
Centralizes use of latches into test utility methods/classes. Declutters
test code to help focus on the meaning of the tests.
> [TestUtils] Recycle Synchronous Latching Code

- aws-storage-s3/src/main/AndroidManifest.xml
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- core/src/main/java/com/amplifyframework/storage/StorageCategory.java
- core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java
The APIs of the Storage category are reworked. Instead of accepting a
`ResultListener<SomeTypeOfStorageResult, StorageException>` as a single callback argument, all APIs will now accept
two "decomposed" functional interfaces, a
`Consumer<SomeTypeOfStorageResult>`, and a `Consumer<StorageException>`.
This change enables a simpler experience for the caller.
Instead of obtaining results like:
```
final StorageListOperation<?> operation =
Amplify.Storage.list(path, new ResultListener() {
@Override
public void onResult(StorageListResult storageListResult) {
Log.i(TAG, "Got a result! " + storageListResult);
}
@Override
public void onError(StorageException error) {
Log.e(TAG, "Listing storage items failed.", error);
}
});
```
The user may now more simply write:
```
final StorageListOperation<?> …
```
> [Storage] Split success and error callbacks

- aws-analytics-pinpoint/build.gradle
- aws-api/build.gradle
- aws-datastore/build.gradle
- aws-storage-s3/build.gradle
- build.gradle
- configuration/retrolambda.gradle
- core/build.gradle
- testmodels/build.gradle
- testutils/build.gradle
To reduce friction in using the library, Retrolambda is used to convert
class files to Java class file version 50. before producing aars. This
prevents the need for the user to elect Java 1.8 source and target
compatibility in their consuming project. This configuration may also be
more compatible with older versions of the Android Studio and Android
Build Tools, that may be found in a user's environment.
> Use Retrolambda for broader consumer compatibility

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- core/src/main/java/com/amplifyframework/api/ApiCategory.java
- core/src/main/java/com/amplifyframework/api/RestBehavior.java
- testutils/src/main/java/com/amplifyframework/testutils/SynchronousApi.java
The `ResultListener` callback is removed from the public contract.
Previously, the syntax to perform a REST behavior was verbose:
```
Amplify.API.post(request, new ResultListener<RestResponse, ApiException>() {
@Override
public void onResult(RestResponse response) {
Log.i("API", "POST response: " + response),
}
@Override
public void onError(ApiException failure) {
Log.e("API", "No response for POST.", failure);
}
});
```
By splitting the callbacks into the `Consumer<RestResponse>` and
`Consumer<ApiException>`, the behavior may accept lambas:
```
Amplify.API.post(request,
response -> Log.i("API", "POST response: " + response),
failure -> Log.e("API", "No response for POST.", failure)
);
```
See GitHub issue: https://github.com/aws-amplify/amplify-android/issues/212
By submitting this pull …
> [API] Accept Lambdas for REST Behaviors

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/StorageItemChangeRecordIntegrationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/network/SyncEngine.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/LocalStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/network/DataHydrationTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- core/build.gradle
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategory.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategoryBehavior.java
- testutils/src/main/java/com/amplifyframework/testutils/LatchedConsumer.java
- testutils/src/main/java/com/amplifyframework/testutils/SynchronousDataStore.java
1. Remove Rx from the vanilla DataStore contract. It will be made
available via the forthcoming RxBindings wrapper module, instead.
2. Accept only functional interfaces for callbacks in DataStore APIs.
The `ResultListener` and `StreamListener` are removed from public APIs.
Previously, operations on DataStore were verbose:
```
Amplify.DataStore.save(post, new ResultListener<DataStoreItemChange<Post>>() {
@Override
public void onResult(DataStoreItemChange<Post> saveResult) {
}
@Override
public void onError(DataStoreException error) {
}
});
```
Such calls have been changed to:
```
Amplify.DataStore.save(post, new Consumer<DataStoreItemChange<Post>>() {
@Override
public void accept(DataStoreItemChange<Post> saveResult) {
}
}, new Consumer<DataStoreException>() {
@Override
public void …
```
> [DataStore] Pure Lambda API for DataStore

- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
In-memory storage adapter's current implementation does not behave as it should (e.g. it does not update/overwrite existing models).
* ~~Refactored it to store models in a HashMap for better performance~~
* Reverted this change to not mess up data hydration test
* Distinguished update and insert
* Invoke error on conditional check failure
> [DataStore] Refactor in-memory storage adapter

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageHelperInstrumentedTest.java
An instrumentation test was using a SQLiteCursor, but was not closing
the cursor when it was done using it. This would sometimes cause a
Strict Mode violation to kill the test process, before tests could
complete execution. So, even though all of the executed tests passed,
the process still crashes, leading a failure being reported for the
suite as a whole.
> [DataStore] Always close SQLiteCursor in instrumentation test

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/network/SyncEngine.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreChannelEventName.java
- core/src/main/java/com/amplifyframework/hub/HubEvent.java
- testutils/src/main/java/com/amplifyframework/testutils/HubAccumulator.java
- testutils/src/main/java/com/amplifyframework/testutils/Latch.java
- testutils/src/main/java/com/amplifyframework/testutils/Sleep.java
Previously, DataStore instrumentation tests were using Sleep to wait an
arbitrary amount of time for synchronization tasks to complete. See the
new statement in Sleep.java about why waiting for a random amount of
time is a bad strategy for synchronization. Instead, DataStore
synchronization events are now published to the Hub.
Some test utilities are added to help await Hub events, in tests.
> [DataStore] Use Hub notifications to communicate Sync Engine events

- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointProperties.java
* Patch for issue: https://github.com/aws-amplify/amplify-android/issues/256
#256
Make `PinpointProperties.Builder#add()` public access
> [Analytics] Make builder methods public accessible

- aws-storage-s3/build.gradle
While building the S3 plugin, there's a new warning about annotation
processors. This is from the new dependency on Robolectric. Currently a
work-around is needed to suppress this warning, which is to exclude the
transitive autovalue dependency.
Refer: https://github.com/robolectric/robolectric/issues/5245
> [aws-storage-s3] Suppress autovalue warning from Robolectric

- aws-analytics-pinpoint/proguard-rules.pro
- aws-api/proguard-rules.pro
- aws-datastore/proguard-rules.pro
- aws-storage-s3/proguard-rules.pro
- configuration/publishing.gradle
- core/proguard-rules.pro
- rxbindings/proguard-rules.pro
- testmodels/proguard-rules.pro
- testutils/proguard-rules.pro
1. Repair generation of maven pom file, to enumerate aar dependencies.
2. Repair ProGuard rules, so that emitted aar contain required public/protected members.
> Fixes to accomodate consuming Amplify from an app

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
A SAVE in the storage adapter should be mapped to a SAVE in the
DataStore API, and a DELETE in the storage adapter should be mapped to a
DELETE in the DataStore API. However, these were backwards.
> [aws-datastore] CRUD type mapping is backwards

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/StorageItemChangeRecordIntegrationTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/StrictMode.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/ModelUpgradeSQLiteInstrumentedTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterDeleteTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterSaveTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageHelperInstrumentedTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageHelper.java
- testutils/src/main/java/com/amplifyframework/testutils/HubAccumulator.java
- testutils/src/main/java/com/amplifyframework/testutils/Latch.java
- testutils/src/main/java/com/amplifyframework/testutils/SynchronousApi.java
Potentially fix SQLite leak by making sure that cursor closes with try-with-resources statement
Merged PR #280:
> - ~~`HubAccumulator` now waits proportionally as long as the number of events it is waiting on.~~
> - ~~Potentially resolve a race-condition in `HubAccumulator`~~
> - Use consistent 2 seconds timeout duration throughout datastore instrumented tests
> Use try-with-resources statement to assure that cursor is closed

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/StorageService.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/StorageComponentTest.java
- core/src/main/java/com/amplifyframework/storage/StorageChannelEventName.java
Portion of PR #259
Refactor storage operations for file transfers:
- Clean up `start()` method by implementing `TransferListener` elsewhere
- Emit Hub event on transfer state/progress update
- Upload operation now builds `ObjectMetadata` before invoking storage service
- Upload operation now accounts for `content-type` (and passes it to metadata)
Refactor storage service for upload:
- Remove `uploadFile` overload for optionally not passing in metadata
- Now requires `ObjectMetadata` rather than `Map<String, Object>`
> Refactor storage operations and service

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/utils/S3RequestUtils.java
- core/src/main/java/com/amplifyframework/storage/options/StorageDownloadFileOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageListOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageRemoveOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageUploadFileOptions.java
Portion of #259 that deals with `StorageOptions`.
- Abstracted out `StorageOptions` to reduce duplicate code
- ~~`StorageOptions` is now sufficient for building S3 service key, so added utility method in `S3RequestUtils` class~~
> Refactor storage options to abstract out common properties

- gradle.properties
During development, it is useful to publish development versions of the libraries to a local maven repository, via `publishToMavenLocal`. In the `master` branch, the library version is currently `0.9.0`.
As a result, it can be confusing to know what version of the library is getting consumed, from a consuming application that uses both `mavenLocal()` and `jcenter()`. Both could provide a `0.9.0`.
To avoid confusion, the version name in the master branch is changed to `master`. Development consumers may access the development version of the library through the local maven repository using:
implementation 'com.amplifyframework:core:master'
etc.
> Use "master" as the default version name

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java
This test is not functioning properly and needs to be repaired, in the
future. For now, it is \@Ignore'd, to keep the test suite reliably
passing.
> [aws-api] @Ignore subscribeFailsWithoutProperAuth

- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageDownloadTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java
AWSS3StorageUploadTest
AWSS3StorageDownloadTest
These contain setup logic which is causing the S3 integration test suite
to fail. These should be re-enabled after resolving issues with test
setup/scaffolding.
> [aws-storage-s3] Temporarily ignore upload and download tests

- core/src/main/java/com/amplifyframework/util/UserAgent.java
*Description of changes:* Currently the User-Agent header passed to HTTP servers includes unnecessary details such as the versions of the Linux kernel and Dalvik/ART VMs. This change removes these elements and adds the version of Android, device manufacturer, and device model to the User-Agent string. Details will be passed as they presented by Android with spaces in tact. These data points will aid in future support efforts and decisions.
For example, on my [test phone](http://phonedb.net/index.php?m=device&id=14161&c=nokia_7.1_dual_sim_td-lte_am_64gb__hmd_rooster), the constructed User-Agent is:
```
amplify-android/master (Android 9; HMD Global Nokia 7.1; en_US)
```
By submitting this pull request, I confirm that my contribution is made under the terms of …
> Add Android device details to User-Agent

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/appsync/SynchronousAppSync.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
blogOwnerCreatedAndUpdatedRemotelyIsFoundLocally had been @Ignored,
until now. In order to arrange a creation and an update on the AppSync
API, it is necessary to pass a version number in the update call. That
had been possible until recently.
Additionally, the receipt of a cloud event must be announced over Hub.
This way, the test has something for which to listen.
> [aws-datastore] Re-enable test for cloud to local synchronization

- aws-api/src/main/java/com/amplifyframework/api/aws/operation/AWSRestOperation.java
- aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestRequestFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/utils/RestRequestFactoryTest.java
Previously, when a user passed multiple path segments via the
RestOptions path string:
```
Amplify.API.get(new RestOptions("path1/path2"), ok -> {}, fail -> {});
```
The forward-slash character (`/`) in the path string would be changed
into the string "`%2F`". So, if the endpoint were `https://domain.tld/api`, you'd end
up making a request to `https://domain.tld/api/path1%2Fpath2`.
After this change, the `/` characters in the provide path are preserved.
The system would end up making a request, instead, to
`https://domain.tld/api/path1/path2`.
Resolves: https://github.com/aws-amplify/amplify-android/issues/304
> [aws-api] User wants to provide multiple path segments

- build.gradle
This project will require Java 1.8 in its consumers, and will no longer
use Retrolambda to support older consumers.
Consumers will need to declare the following block in their
`build.gradle`:
```
android {
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
}
```
Amplify and its consumers are expected to use only the first-party
Android tools to provide Java 1.8 features.
> Remove Retrolambda

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/SubscriptionEndpointTest.java
Try to create two subscriptions over a websocket, using the same request
body.
Expect this to result in two subscriptions, each with a unique ID, and
each having received a `subscription_ack` over the websocket.
> [aws-api] Test that two subscriptions for the same thing have unique ACKs

- README.md
- build.gradle
*Description of changes:* Given the vanishingly small number of ICS users according to Google's [Distribution Dashboard](https://developer.android.com/about/dashboards) and our own log analysis and industry trends ([Google Play Services supports API Level 16+](https://android-developers.googleblog.com/2018/12/google-play-services-discontinuing.html), for example), we are dropping support for API Level 15.
> Raise minSdkVersion to 16

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java
- core/src/androidTest/java/com/amplifyframework/hub/HubInstrumentedTest.java
Ignore `AWSDataStorePluginInstrumentedTest`, which seems to break circleCI consistently at the moment. Re-enable upon fix.
> Temporarily ignore broken test

- CHANGELOG.md
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonVariablesSerializer.java
Not the main topic but was reported on issue #216 
Currently when serializing a Date field we have a horrible bug (my bad!) where it ignores the actual value the user provided and sets it to the current date 🤦‍♂️
> Fixes Date fields being converted to current date

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/ModelUpgradeSQLiteInstrumentedTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/CompoundModelProvider.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/CompoundModelProviderTest.java
There was some exiting logic to blow away the SQL tables if the user's
model structure changes (as informed by the version in the model
provider).
However, no such logic existed for changes to the system models
provider.
To acommodate this, form a compound provider of both, and consider its
version, instead.
> [aws-datastore] Re-provision if system models change

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/PersistentModelVersion.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationOutbox.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
While applying cloud content back into the local storage, the Merger
must consider whether or not the Mutation Outbox has a change record
corresponding to a model with the same UUID.
If the Mutation Outbox has a pending change for a model of the same ID,
then the Merger shall NOT apply the cloud update. This is to prevent
loss of customer data on the client.
> [aws-datastore] Mutation outbox precedence over cloud content

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/StorageItemChangeRecordIntegrationTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/SynchronousStorageAdapter.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterDeleteTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterSaveTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/TestStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/StorageItemChangeRecordTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/SynchronousStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationOutboxTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/VersionRepositoryTest.java
Littered around the test code were various synchronous operations on top
of a `LocalStorageAdapter`. Likewise, the `InMemoryStorageAdapter` had grown
a couple of synchronous operations which it exposed in tests. The
responsibility for synchronous access to a storage adapter was split
into a few different places, *including* the utility that is meant to
achieve this, the `SynchronousStorageAdapter`.
To resolve this, numerous tests are refactored to make singular
reference to the `SynchronousStorageAdapter` only, and in lieu of the
other previously mechanisms of doing synchronous storage access.
> [aws-datastore] Single responsibility for SynchronousStorageAdapter

- aws-analytics-pinpoint/build.gradle
- aws-api/build.gradle
- aws-storage-s3/build.gradle
- core/build.gradle
- testutils/build.gradle
Specifying transitive = true is not necessary for the AWS Mobile Client
Gradle dependencies. This clause had been carried over from usages that
use the @aar artifact declaration. For _those_ declarations, transitive
is _not_ true by default.
> Transitive dependencies already included for AWS Mobile Client

- aws-predictions-tensorflow/build.gradle
- aws-predictions-tensorflow/src/main/java/com/amplifyframework/predictions/tensorflow/asset/TextClassificationDictionary.java
- aws-predictions-tensorflow/src/main/java/com/amplifyframework/predictions/tensorflow/asset/TextClassificationModel.java
- aws-predictions-tensorflow/src/main/java/com/amplifyframework/predictions/tensorflow/service/TensorFlowPredictionsService.java
- aws-predictions-tensorflow/src/main/java/com/amplifyframework/predictions/tensorflow/service/TensorFlowTextClassificationService.java
- aws-predictions-tensorflow/src/test/java/com/amplifyframework/predictions/tensorflow/asset/InputTokenizerTest.java
- aws-predictions-tensorflow/src/test/java/com/amplifyframework/predictions/tensorflow/service/TextClassificationTest.java
- aws-predictions-tensorflow/src/test/resources/word-tokens.txt
- Add unit tests for `fetchSentiment()` and `tokenizeInputText()`
- Remove `final` keyword from loaders to make them mockable
> Add unit tests for offline predictions

- core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java
- core/src/test/java/com/amplifyframework/core/AmplifyConfigurationTest.java
*Description of changes:* Handle missing configuration file
If you do not generate a configuration file with Amplify init, your
application will crash with an unhandled exception. This change throws
an AmplifyException instead to allow the developer to catch their error
during development.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> [core] Handle missing configuration file

- testutils/src/main/java/com/amplifyframework/testutils/Await.java
- testutils/src/main/java/com/amplifyframework/testutils/Latch.java
`Await.java`: if `Await.result(...)` is called from thread A, and its method
fires callbacks on that same thread A, they may never be invoked. This
is because the `CountDownLatch` is sleeping the thread A. To address this
situation, ensure that the `ResultErrorEmitter` function always run on a
different (new) thread.
`Latch.java`: `InterruptedException`was being gobbled. But, this needs to be
raised to crash the thread. Otherwise, the thread can hang.
> [testutils] Prevent deadlocks in Latch and Await

- README.md
1. Reworks some language in the README to remove weasel words, "so easy," etc.
2. Fixes documentation links to point to new site
3. Removes some low-level details from the main content, which had served only to disrupt the document's flow.
> Basic cleanups in the README.md

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AWSAppSyncScalarType.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqliteDataType.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/TypeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteColumn.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTable.java
The Core Model schema includes an enumeration of some various
`JavaFieldType`. This will remain in the Core Models package.
The AWS DataStore implementation maps between these types, and the
various `SqliteDataType`, and `AWSAppSyncScalarType`. These types, and
the business of mapping them, belongs as a detail of the AWS DataStore
plugin.
As consequences of this change:
1. AppSync business details are not part of Amplify's core
specification.
2. If the CLI shall generate references to any of these types, it will
bind the implementation specifically for use of the AWS DataStore
Plugin.
> [aws-datastore] Move AppSync and SQL type enums out of core spec

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/ModelUpgradeSQLiteInstrumentedTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/CompoundModelProvider.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/SimpleModelProvider.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/CompoundModelProviderTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
The order in which models are provided is significant.
1. System models must be provided before user models. This is because
system models store information about user models. It is not possible
to store user models without these storage areas having first been
created. The model provider itself should not encode these ordering
rules, but it must be able to store an ordering, that was determined
by an external actor.
2. User models depend on eachother, and so have a topological ordering.
Some models must be known to the system before others, so that
references can be created.
> [aws-datastore] Maintain insertion order in ModelProviders

- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageDownloadAccessLevelTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageDownloadTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageListAccessLevelTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadAccessLevelTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageDownloadFileRequest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageUploadFileRequest.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/StorageComponentTest.java
- core/src/main/java/com/amplifyframework/storage/StorageCategory.java
- core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousStorage.java
*Description of changes:* Currently `downloadFile` and `uploadFile` expect a String with the local path for the source file and destination file respectively. To move us closer to iOS and to simplify the iOS, use a File instead as the input parameter.
> Use File instead of String input parameters

- build.gradle
While we are on the 4.x release train for OkHttp3, continue to use the
latest, most up-to-date version there-of.
In the future, this project may switch to the 3.12.x release train,
which will support older API levels than 21.
> [aws-api] Use latest OkHttp3, 4.5.0.

- aws-api/src/main/java/com/amplifyframework/api/aws/GsonErrorDeserializer.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- aws-api/src/test/resources/error-extensions-gql-response.json
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncExtensions.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncExtensionsTest.java
- configuration/checkstyle-rules.xml
- core/src/main/java/com/amplifyframework/api/graphql/GraphQLResponse.java
- core/src/main/java/com/amplifyframework/api/graphql/error/AppSyncExtensions.java
- core/src/main/java/com/amplifyframework/api/graphql/error/GraphQLLocation.java
- core/src/main/java/com/amplifyframework/api/graphql/error/GraphQLPathSegment.java
The [2018 GraphQL spec](https://spec.graphql.org/June2018/#sec-Errors) specifies that the error type has 4 fields: `message`, `location`, `path`, `extensions`).   The `extensions` field is designed to point to a Map, and can contain any custom error information, as desired by the implementor.   AppSync added some additional fields at the root (`errorType`, `errorInfo`, `data`) of the error object, which goes against the 2018 GraphQL specification (likely because AppSync implemented it prior to 2018, when `extensions` was not part of the spec).   This PR handles this by merged all non-expected fields into the `extensions` map.  If the same field exist in both places, the field inside of extensions take precedence, and the field at the root level is discarded. …
> Expose all GraphQL error properties

- aws-api/src/main/java/com/amplifyframework/api/aws/GsonErrorDeserializer.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonUtil.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonUtilTest.java
- aws-api/src/test/resources/gson-util.json
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncExtensions.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncExtensionsTest.java
- core/src/main/java/com/amplifyframework/api/graphql/GraphQLLocation.java
- core/src/main/java/com/amplifyframework/api/graphql/GraphQLPathSegment.java
- core/src/main/java/com/amplifyframework/api/graphql/GraphQLResponse.java
Addresses the last bits of feedback on https://github.com/aws-amplify/amplify-android/pull/392, specifically:
- Moves GraphQLLocation, GraphQLPathSegment into same package as GraphQLResponse
- Implements custom deserialization of GraphQL error extension into HashMap to eliminate gson's LinkedTreeMap leaking to public interface.
- Adds `toString` implementations to error models
> Expose all GraphQL error properties (part 2)

- configuration/checkstyle-rules.xml
- configuration/checkstyle-suppressions.xml
- core/src/main/java/com/amplifyframework/analytics/UserProfile.java
- core/src/main/java/com/amplifyframework/predictions/operation/InterpretOperation.java
- core/src/main/java/com/amplifyframework/predictions/operation/TranslateTextOperation.java
We already have a checkstyle rule to ensure that Javadoc on public/protected classes/interfaces is formatted correctly ([JavadocType](https://checkstyle.sourceforge.io/config_javadoc.html#JavadocType)).  This PR adds [MissingJavadocType](https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocType), which ensures that Javadoc actually exists in the first place.
> Add MissingJavadocType to checkstyle-rules

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/operation/AWSIdentifyOperation.java
- core/src/main/java/com/amplifyframework/predictions/operation/IdentifyOperation.java
Follow up to https://github.com/aws-amplify/amplify-android/pull/403.   The build passed on this PR above, but failed after the rebase.  This resolves the issue by adding Javadoc to missing classes, since [MissingJavadocType](https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocType) is a new checkstyle rule.
> Add Javadoc to resolve checkstyle error

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java
Disable REST API tests that use API key. It seems that the required test resources were originally created in the SDK test account, which is now deleted.
TODO: Create new test resources and re-enable the tests
> Temporarily disable failing REST API tests

- aws-api/src/main/java/com/amplifyframework/api/aws/GsonErrorDeserializer.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- aws-api/src/test/resources/error-null-properties.json
*Description of changes:* Fixes a bug where a `JsonParseException` is thrown if `path` on an error object is null.  `path` is not required, so no exception should be thrown.
> [aws-api] Fix JsonParseException when parsing null path in Error object

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonErrorDeserializer.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/utils/S3Keys.java
- core/src/main/java/com/amplifyframework/core/model/ModelAssociation.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryPredicateGroup.java
`KNOWN_NON_NULL.equals(maybeNull)` is always safer than
`maybeNull.equals(KNOWN_NON_NULL)`. In any place this occurs, flip the
equality check.
> Flip constant equality checks

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/RemoteModelMutations.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionEvent.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
The Mutation class sounded general, but it wasn't. It only represented
events received over a GraphQL subscription. A better name for this
class is SubscriptionEvent.
> [aws-datastore] Rename Mutation as SubscriptionEvent

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/IdentifyResultTransformers.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/configuration/IdentifyEntitiesConfiguration.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/configuration/InterpretTextConfiguration.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/configuration/TranslateTextConfiguration.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/BinaryFeatureType.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/operation/AWSIdentifyOperation.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/operation/AWSInterpretOperation.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/operation/AWSTranslateTextOperation.java
- core/src/main/java/com/amplifyframework/predictions/PredictionsCategory.java
- core/src/main/java/com/amplifyframework/predictions/PredictionsCategoryBehavior.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousPredictions.java
* Added `BinaryFeatureType` enum to address the [following discussion](https://github.com/aws-amplify/amplify-android/pull/399#discussion_r417682655)
* Fixed some copy-paste error in Javadocs
* Reorganized some interface methods that were out of order
* Other minor fix-ups
> Miscellaneous changes for Predictions

- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/adapter/IdentifyResultTransformersTest.java
Add unit test for utilities used to transform AWS models to Amplify models, as recommended in the [here](https://github.com/aws-amplify/amplify-android/pull/394#discussion_r414159167)
> Add unit test for result transfomer utilities

- aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactoryTest.java
- aws-api/src/test/resources/mutate-person-with-predicate.txt
- aws-api/src/test/resources/query-for-person-by-id.txt
- aws-api/src/test/resources/query-person-by-predicate.txt
- aws-api/src/test/resources/subscription-request-for-on-create.txt
- Formats GraphQLRequest JSON files used for unit tests so they are more readable. 
- Replaced `org.junit.Assert` with `org.skyscreamer.jsonassert.JSONAssert` so that tests still pass by ignoring whitespace differences.
> Format JSON in unit tests so it is more readable

- aws-api/src/main/java/com/amplifyframework/api/aws/GsonFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonListDeserializer.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonVariablesSerializer.java
- aws-api/src/main/java/com/amplifyframework/api/aws/TemporalDeserializers.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactoryTest.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- aws-datastore/build.gradle
- aws-datastore/src/main/AndroidManifest.xml
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java
- build.gradle
- core/src/main/java/com/amplifyframework/core/model/AWSTimestamp.java
- core/src/test/java/com/amplifyframework/core/model/AWSTimestampTest.java
- testmodels/src/main/java/com/amplifyframework/testmodels/meeting/Meeting.java
This single PR is composed of three git commits, which are only related by a common goal of re-instating _passing tests_.
1. A recent change to refactor date/time handling changed the serialization strategy for `java.util.Date`. However, the integration tests rely on a set of existing Model classes, in `testmodels`, that require the old strategy. To re-enable the AWS API Plugin instrumentation tests, this PR re-instates the original behavior of the _`Date`_ type. To accomodate the new improvements that had been made, a new _`AWSTimestamp`_ type it added. It will behave how the _new_ use of `Date` _would_ have, and the Amplify CLI should code-gen using this new type in place of `Date`. 
2. The method count in the single dex file for the AWS API Plugin instrumentation tests now exceeds the …
> Get integ tests passing again

- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
This test does not pass reliably, and will need to be investigated.
Until that time, it is causing the test suite to fail, sometimes, and
should be ignored.
> [aws-datastore] Ignore MutationProcessorTest#canDrainMutationBox

- .circleci/config.yml
- .circleci/copy-configs
Instead of requiring that credentials be kept in `~/.aws/credentials`, in
a profile with a particular name, the credentials will be obtained via
environment variables, e.g.:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_SESSION_TOKEN`
> Do not require a particular profile to run copy-configs

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
This PR changes the initialization of the DataStore plugin such that the `Orchestrator` will only start if the API category is configured for Amplify.
If API is not present, we basically start without the synchronization processes. 
**NOTE on the testing strategy**
I'm asserting whether or not we're in the correct mode, by creating a spy on the modelProvider we're passing to the DataStore plugin. If the `SyncProcessor` interacts with the spy, we know the `Orchestrator` started.
> [aws-datastore] Only start Orchestrator if API configured

- aws-predictions/build.gradle
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/TextractResultTransformers.java
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/AWSPredictionsPluginConfigurationTest.java
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/adapter/RekognitionResultTransformersTest.java
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/adapter/TextractResultTransformersTest.java
- aws-predictions/src/test/resources/configuration-with-identify-entities.json
- aws-predictions/src/test/resources/configuration-with-identify-entity-matches.json
* Unit test for AWS Textract result -> Amplify model transformers
* Add more unit tests for AWS Rekognition result -> Amplify model transformers
* Add entities detection configuration unit tests
> Add unit tests for predictions result transformers

- aws-datastore/build.gradle
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/GsonPendingMutationConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationOutbox.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/TimeBasedUuid.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/PendingMutationPersistentRecordTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/GsonPendingMutationConverterTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationOutboxTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PendingMutationTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/TimeBasedUuidTest.java
- build.gradle
Changes the ID type of the `PendingMutation`. The `PendingMutation` now
has its own UUID. A mechnism still exists to obtain the ID of the
associated model:
pendingMutation.getMutationId();
pendingMutation.getMutatedItem().getId();
The `PendingMuation.PersistentRecord` now has *two* IDs, a "mutation
ID", and a "decoded model ID":
record.getId();
record.getDecodedModelId();
Previously, the getId() on the record would return the same ID as
`pendingMutation.getMutatedItem().getId()`.
After this change, the mutation ID is uniquely for the PendingMutation
itself. This ID is also of a different type. It is a time-based UUIDv1.
This type of UUID was chosen as it may be sorted according to its
timestamp. And as a consequence, `PendingMutation`s themselves may now
be sorted by their UUIDv1s. …
> [aws-datastore] PendingMutations are now Comparable according to their creation times

- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/TimeBasedUuidTest.java
The mechanism to obtain a unique, randomly-ordered list is subtly
flawed. It does produce a random list, but that list may not be unique
from the input.
As a consequence, the call to `assertNotEquals` would occasionally cause
the test to fail. This was observed on a development machine, already.
Instead, keep re-ordering the list in random order, until it is
different.
> [aws-datastore] Test reliability in TimeBasedUuidTest

- aws-datastore/src/main/java/com/amplifyframework/datastore/model/ModelHelper.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- core/src/main/java/com/amplifyframework/logging/AndroidLoggingPlugin.java
- core/src/main/java/com/amplifyframework/logging/LoggingCategoryBehavior.java
Removes debugging calls to `System.out.println`.  These should be
redirected through the Amplify log facility, instead.
Updates the logging namespace in a few places. The AWS DataStore Plugin
is using a namespace of `"amplify:aws-datastore"`. The f`orCategory()`
factory is a promising addition, but it is currently generating a
different slug. The AWS DataStore Plugin can adopt use of this factory
more uniformly, in the future.
> [aws-datastore] Logging cleanups

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/DataStoreCategoryConfigurator.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
The `AWSDataStorePlugin` has a dependency on a `GraphQlBehavior` in one
place, as the portal through which to perform synchronization. In
another place, `Amplify.API` is referenced directly, to determine if there
are plugins available in the API category.
For the purposes of test, consolidate both uses to an `ApiCategory`
instance, which satisfies both purposes. This dependency is wired
through to the constructor, for dependency injection.
> [aws-datastore] Clarify AWSDataStorePlugin dependency on API Category

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
The Rx `PublishSubject` is not thread-safe. It is being used around the
code base in locations where `PublishSubject#on<Event>(...)` methods may
be invoked from different threads.
One strategy to resolve this is to use a serialized `PublishSubject`,
via the `toSerialized()` operator.
Refer: https://stackoverflow.com/a/43008419/695787
Resolves: https://github.com/aws-amplify/amplify-android/issues/451
> [aws-datastore] thread safe rx publish subjects

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
When the `MutationProcessor` fails to publish a `PendingMutation`, it emits
an error. This error message currently contains no information about the
mutation that failed. To help debug, include the contents of the
mutation in the error message.
> [aws-datastore] Include mutation details in publication exception

- aws-datastore/src/main/java/com/amplifyframework/datastore/model/ModelHelper.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationOutbox.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/StorageObserver.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
Adds more detailed logging about the system state.
Changes some existing logs to verbose, which is not printed in
production, by default.
General strategy is to log lifecycle events at `INFO` (visible to
production), recoverable failures as `WARN`. Everything else as `VERBOSE`.
> [aws-datastore] Additional logging

- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionOperation.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageHelper.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationOutbox.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
Move debugging logs to debug level, to avoid the noise that is present
in the verbose level.
> [aws-datastore] Further refinements to log levels

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
`SELECT 1`, instead `SELECT *`, since we are only interested in presence,
not in the record data itself.
Refer: https://stackoverflow.com/a/7171072/695787
> [aws-datastore] Optimize record lookup

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/AWSPredictionsPluginConfiguration.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/configuration/IdentifyLabelsConfiguration.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/configuration/IdentifyTextConfiguration.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/operation/AWSIdentifyOperation.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSPredictionsService.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSRekognitionService.java
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/AWSPredictionsPluginConfigurationTest.java
- aws-predictions/src/test/resources/configuration-with-identify-labels.json
- aws-predictions/src/test/resources/configuration-with-identify-text.json
- aws-predictions/src/test/resources/configuration-with-text-to-speech.json
* celebrity detection configuration is now taken into account (used to be always enabled even when explicitly turned off in the configuration)
* add "identifyText" configuration
* add "identifyLabels" configuration
* add default behavior for passing in `IdentifyActionType#DETECT_TEXT` instead of `TextFormatType` enum (previously triggered error callback)
* add default behavior for passing in `IdentifyActionType#DETECT_LABELS` instead of `LabelType` enum (previously triggered error callback)
> Add text and label configuration

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java
- core/src/main/java/com/amplifyframework/api/ApiCategoryBehavior.java
- core/src/main/java/com/amplifyframework/api/graphql/GraphQLBehavior.java
- core/src/main/java/com/amplifyframework/api/rest/RestBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxGraphQlBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxRestBehavior.java
1. GraphQlBehavior is renamed to GraphQLBehavior, with a capitol 'L', to
match other such classes.
2. RestBehavior and GraphQLBehavior are moved into .rest and .graphql,
respectively, to live alongside the rest of their component entities.
> [core] Repackage REST and GraphQL Behaviors interfaces

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
In order to support conditional outgoing mutations, we need to allow
multiple mutations to exist in the queue at the same time.
This means there is no longer a notion of a single "pre-existing
mutation" for a model ID, there are n-many such.
All the same, we will concern the _first_ match in the queue, when we
enact business logic about the outbox state.
> [aws-datastore] Permit multiple mutations per model ID

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
A subtle change.
The Mutation Processor responds to changes in storage. There is always a
pending mutation in the outbox when it runs. That's why it is asked to
run.
At the same time, the Merger will check if there is a mutation for a
given model ID, before merging. It will refuse to merge, if there is at
least one.
The previous solution to this was to forcibly clobber data, based on a
"no, but really" flag, passed to the Merger.
Instead, the MutationProcessor is changed to first remove the pending
mutation, before merging it.
This new behavior is subtly different. There might _still_ be a pending
mutation for the model ID in the outbox. It just won't be one that was
just published. So, the merge can still fail, even after we remove the
pending mutation from the outbox.
However, that's …
> [aws-datastore] Remove mutation before merge in MutationProcessor

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationOutbox.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
The behavior of the Mutation Outbox is changed, to include an in-memory,
"in-flight" state for its pending mutations.
Before we start to publish a mutation to AppSync, we will mark it as
"in-flight", in the Mutation Outbox. This signifies that the mutation
will be treated as immutable for the duration of its life in-memory.
The mutation will continue to be marked as "in-process" until one of two
things happen:
1. The mutation is removed from the mutation outbox.
2. The system restarts, and the mutation is loaded from disk, again,
while rebuilding the mutation outbox. While loading, it will appear
as though this mutation did _not_ finish processing successfully,
and so should be retried.
While enqueuing new mutations, existing, in-flight mutations will be
ignored. That is to say, new …
> [aws-datastore] Mark mutations as in-flight while processing

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/StorageObserver.java
Serialize the StorageObserver, so that it will enqueue mutations
into the MutationOutbox in the same order in which the StorageObserver
dispatches them.
> [aws-datastore] Serialized observation of storage

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
Upon merging a model from sync, mutation response, subscription data,
inspect the model version. If the version is equal to or less than the
current version in the system, refuse to merge.
> [aws-datastore] Consider the model version before merging

- testutils/src/test/java/com/amplifyframework/testutils/HubAccumulatorTest.java
`accumulatorReceivesNothingBeforeStart()` tested the following:
1. Publish an event;
2. At the same time, start listening for events.
The test falsely asserted that (2) must happen after (1) always. But in
a multithreaded environment, that is clearly not the case.
Furthermore, there is no clear way to salvage the test into something
that is logically correct, and important for verification.
> [testutils] Remove a logically incorrect HubAccumulator test

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/TestApiCategory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncSigV4SignerInterceptorFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/DefaultCognitoUserPoolsAuthProvider.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncSigV4SignerInterceptorFactoryTest.java
Integrates Auth with API category in a preliminary way where AWSMobileClient is obtained from the Auth escape hatch instead of directly.
Note that integration tests still rely on AWSMobileClient directly.
> Auth Integration for API

- aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/AnalyticsPinpointInstrumentedTest.java
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.java
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginConfiguration.java
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointManagerFactory.java
Integrates Auth into analytics following the pattern agreed on.
AWSMobileClient is still used directly for integration tests for now but will be replaced as a fast follow hence why I didn't create a special class to handle initializing it like was done in other categories.
> Auth integration with Analytics

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- aws-predictions/src/androidTest/java/com/amplifyframework/predictions/aws/TestPredictionsCategory.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/AWSPredictionsPlugin.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSComprehendService.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSPollyService.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSPredictionsService.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSRekognitionService.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSTextractService.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSTranslateService.java
- core/src/main/java/com/amplifyframework/auth/AuthCategory.java
- core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
- core/src/main/java/com/amplifyframework/auth/options/AuthSignOutOptions.java
- Integrates Auth with Predictions
- Updates SignOut to do local by default with an option to explicitly sign out globally which will fail if the device is offline and fall back to local if a global sign out was first done on another device.
- Disables AWS logs to remove some of the confusing clutter in LogCat (AWSMobileClient still does it's own logs which is very annoying).
> Integrates Auth with Predictions, Updates Sign Out, Disables AWS Logs

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/GsonPendingMutationConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/PendingMutationPersistentRecordTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
The `PersistentRecord` was documented as storing a serialized form of the
_`Model`_ itself. However, that is not the case. The `PersistentRecord` stores
a Gson-serialized form of a `PendingMutation`.
This distinction is made more clear by improving the documentation,
method names, and identifiers, to clarify the user of the record fields.
> [aws-datastore] Clarify field naming in PersistentRecord

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
The PR is a follow up to #496. It contains the business logic that handles conflicts when multiple mutations for the same model and enqueued. It takes into account whether a condition was included with the update/delete.
> Implement conflict resolution rules for existing and incoming mutations for the same model

- core/src/main/java/com/amplifyframework/analytics/AnalyticsBooleanProperty.java
- core/src/main/java/com/amplifyframework/analytics/AnalyticsDoubleProperty.java
- core/src/main/java/com/amplifyframework/analytics/AnalyticsEvent.java
- core/src/main/java/com/amplifyframework/analytics/AnalyticsIntegerProperty.java
- core/src/main/java/com/amplifyframework/analytics/AnalyticsProperties.java
- core/src/main/java/com/amplifyframework/analytics/AnalyticsStringProperty.java
An Amplify user may compare these objects, and may use them in collections.
An Amplify user will like to see a string representation of the objects, while debugging their project code.
> [core] Add equals hashCode toString for Analytics data types

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncClientInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AmplifyDisposables.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- rxbindings/src/main/java/com/amplifyframework/rx/AmplifyDisposables.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAdapters.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxHubBinding.java
- testutils/src/main/java/com/amplifyframework/testutils/AmplifyDisposables.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousApi.java
`AmplifyDisposables` is a factory class that generates Rx `Disposable` from
an input Amplify `Cancelable`.
Three copies of this file are added. Unfortunately this is necessary
since `testutils`, `rxbinings`, and `aws-datastore` only share `core` as a
common dependency module. However, `core` does not take a dependency on
Rx, by design. So, this class could not compile, in `core`, nor is `core` an ideal
place for miscellaneous utility code.
> Add AmplifyDisposables utility to each modules using Rx

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncResponseDeserializer.java
When the response to a query is an empty array, the data field of the `GraphQLResponse` is null. That was causing an error in with the base sync query in DataStore. Example of the response that was causing the error:
```
{"data":{"syncTodos":{"items":[],"nextToken":null,"startedAt":1590176322207}}}
```
> [aws-datastore] Handle list responses without any items

- aws-api/src/main/java/com/amplifyframework/api/aws/IterableDeserializer.java
Before the refactor of GsonGraphQLResponseFactory in https://github.com/aws-amplify/amplify-android/pull/488, there were two ways of deserializing Lists:
1. Lists at the top level were deserialized by GsonGraphQLResponseFactory with something like this:
```
private <T> Iterable<T> parseDataAsList(JsonElement jsonData, Class<T> classToCast) {
ArrayList<T> dataAsList = new ArrayList<>();
for (JsonElement current : jsonData.getAsJsonArray()) {
dataAsList.add(gson.fromJson(current, classToCast));
}
return dataAsList;
}
```
2. Lists of objects below the top level (like an array of `Post` objects on a `Blog` object) were parsed with the `GsonListDeserializer`, and for some reason returned null if the list is empty:
```
GsonListDeserializer.java:
if (items.size() == 0) {
return null;
} else { …
```
> Return empty array instead of null for empty items in response

- aws-api/src/main/java/com/amplifyframework/api/aws/GsonVariablesSerializer.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncVariablesSerializer.java
`GraphQLRequest` already implements `equals`, `hashcode`, but it has a VariablesSerializer property which does not.  This adds `equals`, `hashcode` to those classes, so that `GraphQLRequest` should now work properly when checking for equality.
> Add equals, hashcode to VariablesSerializers

- aws-api/src/main/java/com/amplifyframework/api/aws/GsonFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/TemporalDeserializers.java
> Rename AWS* to Temporal* in the TemporalDeserializers

- amplify-tools/amplify-tools-gradle-plugin/src/main/groovy/com/amplifyframework/tools/gradle/plugin/AmplifyTools.groovy
- amplify-tools/gradle.properties
**The reformat changed every line, so please review the individual commits using [this view](https://github.com/aws-amplify/amplify-android/pull/522/files/f85ca6ea394a824d8123c65b8e3e637ccbb008de..111230d40175f92358a9556586b99a906a2972c2)**
*Description of changes:* Fix Windows support in IDE integration
None of this was working. It does now.
- Android Studio Reformat (⌥⌘-L)
- Use master instead of 1.0.0
> Fix Windows support in IDE integration

- aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/AppSyncSigV4SignerInterceptor.java
- aws-api/src/test/java/com/amplifyframework/api/aws/utils/RestRequestFactoryTest.java
AppSyncSigV4SignerInterceptor uses ByteArrayInputStream for both empty and non-empty request body.
Resolves: #379
Issue #, if available:
#379
Description of changes:
AbstractAWSSigner is checking to see if markSupported, but okio Buffer (which is used to copy the bytes into DefaultRequest in https://github.com/awslabs/aws-mobile-appsync-sdk-android/blame/master/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/sigv4/AppSyncSigV4SignerInterceptor.java#L120) does not override the default InputStream definition of return false. This change uses ByteArrayInputStream (which returns true for markSupported) for both empty and non-empty body paths.
> [aws-api] Fix POST requests with non-empty body

- amplify-tools/amplify-tools-gradle-plugin/src/main/groovy/com/amplifyframework/tools/gradle/plugin/AmplifyTools.groovy
*Description of changes:* Don't escape JSON on non-Windows platforms
Windows requires double-quotes to be escaped to be passed on the command
line, but if we do the same everywhere the backslashes will be passed to
the CLI on macOS/Linux and the CLI will blow up.
This change only applies the escaping when on Windows.
- Rename variables to not be CONSTANT_CASE
> fix(amplify-tools): Don't escape JSON on non-Windows platforms

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthSession.java
Removes deprecated credential provider behavior which can lead to customer confusion.
> Remove AWSCredentialsProvider behavior

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLInstrumentationTest.java
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- core/src/main/java/com/amplifyframework/api/rest/RestOptions.java
*Issue #, if available:* #538 
OkHTTP converts POST/PUT requests to GET requests if the payload is null. Addresses this by sending an empty byte array as the payload if the Customer does not specify one.
Also privatizes the constructor of RestOptions since the builder is what should be used
> fix(api): Fix #538 by providing a default empty byte array for REST payload

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionOperation.java
Remove some dead fields and redundant SuppressWarnings.
Rework requestSubscription() to return the subscription ID only via the
onStart consumer, and not by direct method return.
> fix(aws-api): cleanups to subscription endpoint

- .circleci/aggregate-build-artifacts.sh
- .circleci/aggregate-test-results.sh
- .circleci/config.yml
- .gitignore
------------------------
Currently we are not able to see the outputs of unit tests that run in CircleCI.
To enable this, we need to package test results into a fake directory structure that CircleCI expects.
------------------------
> Show build outputs and unit test results in CircleCI Web UI

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java
- aws-api/src/main/java/com/amplifyframework/api/graphql/model/ModelMutation.java
- aws-api/src/main/java/com/amplifyframework/api/graphql/model/ModelQuery.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactoryTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/appsync/SynchronousAppSync.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/SynchronousStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSync.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/model/PredicateInterfaceAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/LocalStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/StorageItemChange.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/SynchronousStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
- core/src/main/java/com/amplifyframework/core/model/query/QueryOptions.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/MatchAllQueryPredicate.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryPredicates.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousApi.java
Around the code-base, a `null` value for a `QueryPredicate` has the
meaning of "don't apply any filter," or, "match everything."
That's sort of clear, maybe.
Instead of having a meaningful `null` value, use a sentinel, instead,
which declares its purpose as `QueryPredicates.matchAll()`.
> fix(core): use sentinel for null query predicate

- aws-api/build.gradle
- build.gradle
- core/build.gradle
- core/src/main/java/com/amplifyframework/core/model/temporal/Temporal.java
- core/src/test/java/com/amplifyframework/core/model/temporal/TemporalTimeTest.java
By updating to Android Gradle Plugin 4.0.0, we can now take advantage of [Java 8+ desugaring support](https://developer.android.com/studio/write/java8-support#library-desugaring), which allows us to use `java.time`.  This PR removes the threetenabp dependency and replaces it with `java.time`.
> chore: Replace threeten backport dependency with java.time

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncPaginatedResult.java
- aws-api/src/main/java/com/amplifyframework/api/graphql/model/ModelPagination.java
- aws-api/src/main/java/com/amplifyframework/api/graphql/model/ModelQuery.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java
- aws-api/src/test/resources/blog-owners-query-results.json
`nextToken` is an AppSync detail, which should not be exposed in the public interface.   There is no way to obtain it from a response directly, so we can remove it from the `ModelPagination` object.
To make a request to get a "next page" of results, customers should obtain a `GraphQLRequest` via the `getRequestForNextPage()` method on the `PaginatedResult` object.  This request object is a copy of the `GraphQLRequest` used in the previous query, but with the `nextToken` added as a variable.   Then, customers can pass this GraphQLRequest directly to `Amplify.API.query(...)`
This also adds an additional factory method, so customers can do `ModelPagination.limit(1000)`, instead of `ModelPagination.firstPage().withLimit(1000)`
By submitting this pull request, I confirm that my contribution is …
> Remove nextToken from ModelPagination since nextToken is never exposed

- core/src/main/java/com/amplifyframework/core/model/AuthRule.java
- core/src/main/java/com/amplifyframework/core/model/AuthStrategy.java
- core/src/main/java/com/amplifyframework/core/model/ModelField.java
- core/src/main/java/com/amplifyframework/core/model/ModelOperation.java
- core/src/main/java/com/amplifyframework/core/model/ModelSchema.java
- core/src/main/java/com/amplifyframework/core/model/annotations/AuthRule.java
- core/src/main/java/com/amplifyframework/core/model/annotations/ModelConfig.java
- core/src/main/java/com/amplifyframework/core/model/annotations/ModelField.java
This adds an `@AuthRule` annotation, so that it can be used in codegen model files.   The annotation can represent an authorization rule if any are specified in a GraphQL schema with the [@auth directive](https://docs.amplify.aws/cli/graphql-transformer/directives#auth).  `ModelConfig` and `ModelField` now include an array of @AuthRule objects.   
Note that this replaces the `boolean hasOwnerAuthorization()` method previously on `ModelConfig`, which was intended to support the basic owner based auth use case.  This PR adds support for *all* use cases allowed by the @auth directive.
Sample `schema.graphql`:
```
type Todo
@model
@auth(rules: [
{ allow: owner },
{ allow: owner, ownerField: "owner", operations: [create, update, delete, read] },
{ allow: owner, operations: [create, delete, …
```
> feat(API): Add AuthRule annotation to support @auth directive

- .circleci/config.yml
- .circleci/retry.sh
- core/src/test/java/com/amplifyframework/util/QuotesTest.java
If the `build` or `integrationtest` CircleCI step fails , try up to 3 times before failing.
Here is an example of the `build` step failing on the first attempt (due to the flaky `clearStopsSyncUntilNextInteraction` test), and succeeding on the 2nd attempt: https://app.circleci.com/pipelines/github/aws-amplify/amplify-android/1830/workflows/9581c719-0eae-47ea-a645-49ac41492da6/jobs/3537/steps
Here is an example of `build` failing 3 out of 3 times, because a unit test was actually broken: https://app.circleci.com/pipelines/github/aws-amplify/amplify-android/1831/workflows/a246c99a-ec03-4f67-8cc9-b685b926bb99/jobs/3538
Here is an example of `integrationtest` failing 3 out of 3 times:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-android/1834/workflows/f1ab5e60-255c-450e-bd50-7 …
> ci: Try build and integrationtest 3 times before failing

- .circleci/config.yml
- gradle/wrapper/gradle-wrapper.properties
Gradle 6.5 is the latest stable Gradle release; use it.
> chore: use latest Gradle version 6 dot 5

- rxbindings/src/main/java/com/amplifyframework/rx/RxAdapters.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAmplify.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxAuthBindingTest.java
Adds Rx bindings covering the entire surface of the AuthCategory
As just one example, instead of calling:
```java
Amplify.Auth.signIn(username, password,
result -> Log.i(TAG, "Sign-in ok"),
failure -> Log.e(TAG, "Failed to sign in.", failure)
);
```
You can get an Rx `Single`, and subscribe to it:
```java
RxAmplify.Auth.signIn(username, password)
.subscribe(
result -> Log.i(TAG, "Sign-in ok"),
failure -> Log.e(TAG, "Failed to sign in.", failure)
);
```
> feat(rxbindings): add bindings for auth

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLPredicateTest.java
*Issue #, if available: #458 
The issue is that the `contains` predicate assumes that the field we're querying is a list. However, when used on a String field, it results in invalid SQL syntax. So for example:
```
Blog.TAGS.contains("something");
```
yields
```sql
"something" IN tags
```  
which results in an error.
At first, I thought fixing it would just be a matter of determining whether the field we’re querying against is a List<> or a String. However, that information is not available from inside the `SQLPredicate` class as it exists today, so I need to explore some options.
Decided to go with the [instr](https://www.sqlite.org/lang_corefunc.html#instr) function to handle string pattern matching operation.
------------
By submitting this pull request, I …
> Fix for contains predicate

- .circleci/config.yml
- .gitignore
- README.md
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageDownloadTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java
- build.gradle
- configuration/coverage.gradle
The command below will run the instrumentation tests, and then produce a
coverage reports that includes *both* the instrumentation and unit test
coverage data, considered across all modules in thie Gradle project.
```sh
./gradlew connectedDebugAndroidTest jacocoFullReport
```
> chore: enable coverage reports

- .circleci/config.yml
- .circleci/retry.sh
- .circleci/run-integration-tests.sh
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLInstrumentationTest.java
With these changes, I was able to get a green checkmark on the `integrationtest` step 4 out of 5 times.  The [one failure](https://app.circleci.com/pipelines/github/aws-amplify/amplify-android/1915/workflows/351584cc-d22c-42e4-a9a3-bfc061a5909c/jobs/3716/steps) was because the emulator didn't start.
- Integration tests now run one module at a time (e.g. `./gradlew aws-api:connectedDebugAndroidTest` instead of `./gradlew connectedDebugAndroidTest`, and retry logic is applied at the module level.  So, if an `aws-api` integration test fails, it only retries `aws-api`, instead of the whole suite. 
- Updated hash for codecov.io/bash script, since there was an update to the script.
I have a hunch that the main reason for the improvement here is actually not because of modularizing retries, but …
> ci: improve integration test retry logic

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java
- aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestRequestFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/utils/RestRequestFactoryTest.java
* Re-enable the REST API integration tests that were previously turned off.
* REST URL constructor will now strip leading slashes in provided path to avoid the [following OkHttp behavior](https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.Builder.html#addPathSegments-java.lang.String-):
* > If `pathSegments` starts with a slash, the resulting URL will have empty path segment.
> fix(aws-api): Fix path with leading slash breaking REST

- core/src/main/AndroidManifest.xml
- core/src/main/java/com/amplifyframework/util/UserAgent.java
*Description of changes:* Changed the package name com.amazonaws.amplify.core to com.amplifyframework.core, since the package com.amazonaws.amplify.core does not exist.
> fix(core): update com.amazonaws.amplify.core package name

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
calling observeOn with the same schedulers wont change the below rxjava stream's running thread.
> fix(DataStore): remove unnecessary observeOn call

- .circleci/config.yml
- gradle/wrapper/gradle-wrapper.properties
> chore: use latest stable gradle

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
fixes #588 
AppSyncRequestFactory uses "simple" plural form creation instead of making use of ModelSchema.pluralName
> [aws-datastore] fix model name plural form creation in AppSyncRequestFactory

- aws-predictions/src/androidTest/java/com/amplifyframework/predictions/aws/AWSPredictionsIdentifyEntitiesTest.java
In regards to our discussion about whether our integration tests should call real services, or instead, mock the responses, I think there is value to both approaches.  Tests that mock responses should be sufficient to verify we don't cause regressions in our Amplify code.  On the other hand, tests that call real services verify that Amplify is useful to customers, and are useful to reference when answering usage questions for customers.
That said, this PR fixes `testIdentifyEntities` in `aws-predictions`, which is an integration test which calls a real service.  The test submits a photo of Jeff Bezos to Rekognition, and verifies that his age (56) is within the predicted range.  Recently, the algorithm must have changed, and the predicted range is now 37-55.   To reduce our reliance on the …
> chore(predictions): Fix testIdentifyEntities by adding a buffer to the ageRange check

- gradle.properties
The "master" branch is deleted, and this term is no longer being used.
We missed the update in gradle.properties, where the default release
name is kept.
The default branch is "main", and the default release name should match, and be "main", too.
> fix: update default release version name

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/TemporalDeserializers.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncResponseDeserializer.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncResponseDeserializerTest.java
- aws-datastore/src/test/resources/meeting-response.json
*Issue #, if available:* https://github.com/aws-amplify/amplify-android/issues/590, https://github.com/aws-amplify/amplify-android/issues/621
*Description of changes:* Adds full support for using [AWS Date scalars](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) with DataStore.  This PR specifically adds support for deserializing them in the response.  Serialization on requests was already fixed in https://github.com/aws-amplify/amplify-android/pull/601.
> fix(datastore) add deserializers for dates

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
If there is no API configured (i.e. DataStore is operating in local-only mode), calls to the DataStore end up timing out. This PR addresses this issue and modified tests to account for the scenario.
> fix(datastore) Set orchestrator status when no API configured

- build.gradle
Fails the build, if the project is not using the latest version of any
one of its dependencies. This is an aggressive configuration, designed
to bring visibility to the Amplify developers around the availability of
security updates. We should rather not ship the code, than to miss a
security update.
> chore: fail build for out of date dependencies

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java
- aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/AppSyncSigV4SignerInterceptor.java
- aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestRequestFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/utils/RestRequestFactoryTest.java
#650 #644 
* The request was being SigV4 signed without adding the query parameters. This was fixed.
*Minor changes:*
* URL is now decoded and re-encoded inside `RestRequestFactory` to ensure correct encoding.
* Signer now distinguishes AppSync and API gateway when signing
> fix(api): now correctly signs requests with query string params

- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- build.gradle
OkHttp & MockWebServer 4.8.0
Desugar Tools 1.0.9
AWS SDK 2.16.13
AGP 4.0.1
Compile & Target SDK 30
Build Tools 29.0.3
----------------------------
AWS SDK 2.16.13 adds some method overloads to `AWSMobileClient` that necessitate some changes in the `AuthComponentTest`, in Amplify. Changes are made to disambiguate between method signatures with the same runtime erasures.
----------------------------
> chore: latest dependency versions

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/StorageObserver.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMocking.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
- testutils/src/main/java/com/amplifyframework/testutils/HubAccumulator.java
fix: daemon style lifecycle for orchestrator
The state machine in the orchestrator is changed. The three possible
states are now:
a. STOPPED      No sync component is running, and local changes are not
being queued into an offline mutations queue.
b. LOCAL_ONLY   Local changes are being buffered into an offline
mutations queue, but are not being transacte with the
cloud
c. SYNC_VIA_API Data is syncrhonizing to and from the cloud.
Logic is added to transition safely between any pair of these states
(there are six possible transitions.)
If the Orchestrator fails to start up cleanly, then tear down any/all
copmonents that were started, and enter offline-only mode.
0. Retry logic is _removed_ from the subscription processor. Instead, if
a subscription fails, the failure is communicated back …
> fix: start orchestrator before any datastore operations

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
Currently Auth isn't sending the proper Amplify user agent because AWSMobileClient overrides it. This works in conjunction with this PR on the SDK branch to enable us to override that user agent with our own: https://github.com/aws-amplify/aws-sdk-android/pull/2024
> Sends proper user agent for Auth

- core/src/main/res/color/switch_state_colors.xml
- core/src/main/res/drawable/switch_track.xml
- core/src/main/res/layout/fragment_file_issue.xml
- core/src/main/res/values/strings.xml
*Description of changes:* Creates the UI for the file issue screen on the developer menu.
File issue screen when first opened:
File issue screen after toggling all three switches to be on:
> Create file issue UI for developer menu

- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
The recent Auth User Agent work broke one of the unit tests - this fixes it.
> Fixes unit test for new Auth User Agent

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java
`GraphQLResponse.Error` object used to only have `message` property. After more properties such as locations and extensions were introduced, the message portion alone did not contain the desired substring. The error type is contained inside `extensions` property now.
This PR fixes the test to use `toString()` to check against the entire error content rather than just the message.
> chore: fix broken integration test assert statement

- core/src/main/java/com/amplifyframework/devmenu/DevMenuEnvironmentFragment.java
- core/src/main/res/layout/dev_menu_fragment_environment.xml
- core/src/main/res/values/dev_menu_strings.xml
*Description of changes:* Creates the UI for the environment information screen on the developer menu, shown in the picture below.
> Create environment info UI for developer menu

- aws-datastore/src/main/java/com/amplifyframework/datastore/model/SystemModelsProviderFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/LastSyncMetadata.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncTimeRegistry.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncType.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
As part of implementing the hub events for DataStore sync (#710), we need to save sync type (BASE or DELTA) as part of the `LastSyncMetadata` system model. This will allow us to decouple the process of tracking the sync metrics from the actual sync process. 
> Adding SyncType to LastSyncMetadata

- build.gradle
- gradle.properties
Increase jvm max heap size to 4Gb to prevent exit value 137 in circleCI.
> chore: increase jvm max heap size

- .gitignore
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageReservedWordTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlKeyword.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteColumn.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
- core/src/main/java/com/amplifyframework/util/Wrap.java
Datastore SQL commands fail if your model has SQLite reserved words in them. see #707
This quotes table and column names to avoid that.
> Fix (datastore) quote sql commands

- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageDownloadTest.java
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.java
- core/src/main/java/com/amplifyframework/storage/StorageCategory.java
- core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java
- core/src/main/java/com/amplifyframework/storage/StorageChannelEventName.java
- core/src/main/java/com/amplifyframework/storage/result/StorageTransferProgress.java
The Storage category in Amplify iOS includes progress listeners, which
can be used to monitor the status of an active download or upload. The
original APIs launched for Amplify Android did not include this
capability.
This commit adds overloads for `uploadFile(...)` and `downloadFile(...)`, in a
non-breaking way. The old signatures are still available. However, a caller may
optionally tap into progress updates by using these newly available forms:
```kotlin
Amplify.Storage.downloadFile(fromRemoteKey, toLocalFile,
StorageDownloadFileOptions.defaultInstance(),
{ Log.i("download", "Progress = ${it.fractionCompleted}") },
{ Log.i("download", "Result = ${it.file.canonicalPath}") },
{ Log.e("download", "Error = ${it.localizedMessage}") }
)
```
Or:
```kotlin …
```
> feature: adds progress callbacks to storage

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- testmodels/src/main/java/com/amplifyframework/testmodels/personcar/RandomVersionModelProvider.java
#595 
Removed caching logic for insert statements:
When the `SQLiteStorageAdapter` was first written, small optimization logic was added to cache insert statements during initialization. These statements were to be re-used whenever new entries were being entered in a table. Currently, no other types of sqlite statements are cached like this, and are generated on the spot whenever they are called. 
When the database was updated with new tables, it caused a chicken-and-egg problem between generating insert statements and updating the database. To prevent this problem, the original optimization logic is removed in this PR so that insert statements are prepared on the spot like the other types of sqlite operations. 
No explicit tests were …
> fix(aws-datastore): remove insert statement cache

- aws-api-appsync/src/main/java/com/amplifyframework/core/model/temporal/Temporal.java
- aws-api-appsync/src/test/java/com/amplifyframework/core/model/temporal/TemporalDateTest.java
- aws-api-appsync/src/test/java/com/amplifyframework/core/model/temporal/TemporalDateTimeTest.java
- aws-api-appsync/src/test/java/com/amplifyframework/core/model/temporal/TemporalTimeTest.java
- aws-api-appsync/src/test/java/com/amplifyframework/core/model/temporal/TemporalTimestampTest.java
This adds support for using `Temporal` date types for comparison in a `QueryPredicate`.
For example, given this schema:
```
type Todo @model {
id: ID!
name: String!
description: String
updatedAt: AWSDateTime
}
```
and the following implementation:
```
Amplify.API.query(
ModelQuery.list(Todo.class, Todo.UPDATED_AT.gt(new Temporal.DateTime(new Date(), 0))),
response -> LOG.info("query completed"),
error -> LOG.error("query failed")) 
```
it fails to compile with this error:
```
error: method gt in class QueryField cannot be applied to given types;
Amplify.API.query(ModelQuery.list(Todo.class, Todo.DATE.gt(dateTime)),
^
required: T
found: DateTime
reason: inferred type does not conform to upper bound(s)
inferred: DateTime
upper bound(s): Comparable<DateTime>
where T is a type-variable:
T …
```
> feat(api) Implement Comparable for Temporal types so they can be used in predicates

- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-predictions-tensorflow/src/main/java/com/amplifyframework/predictions/tensorflow/TensorFlowPredictionsPlugin.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/AWSPredictionsPlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- core/src/main/java/com/amplifyframework/core/Amplify.java
- core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java
- core/src/main/java/com/amplifyframework/core/Resources.java
- core/src/main/java/com/amplifyframework/core/plugin/Plugin.java
- core/src/main/java/com/amplifyframework/devmenu/DevMenuEnvironmentFragment.java
- core/src/main/java/com/amplifyframework/devmenu/DevMenuFileIssueFragment.java
- core/src/main/java/com/amplifyframework/devmenu/DeveloperMenu.java
- core/src/main/java/com/amplifyframework/devmenu/EnvironmentInfo.java
- core/src/main/java/com/amplifyframework/devmenu/PersistentLogStoragePlugin.java
- core/src/main/java/com/amplifyframework/hub/AWSHubPlugin.java
- core/src/main/java/com/amplifyframework/logging/AndroidLoggingPlugin.java
- core/src/main/java/com/amplifyframework/util/Immutable.java
- core/src/main/res/layout/activity_dev_menu.xml
- core/src/main/res/layout/dev_menu_fragment_file_issue.xml
- core/src/main/res/values/dev_menu_strings.xml
- core/src/test/java/com/amplifyframework/core/BadInitLoggingPlugin.java
- core/src/test/java/com/amplifyframework/core/SimpleLoggingPlugin.java
- core/src/test/java/com/amplifyframework/core/category/FakePlugin.java
- core/src/test/java/com/amplifyframework/core/category/SimplePlugin.java
- core/src/test/java/com/amplifyframework/logging/FakeLoggingPlugin.java
*Description of changes:* Displays environment information (Amplify plugin information and developer environment information) on the developer menu. Note that the developer environment information currently contains only simulated values. Also makes the following changes:
- Increases the height of the developer menu.
- Changes the message displayed on the file issue screen and increases the font size of this message.
- Reduces the minimum character count requirement for the issue description on the file issue screen.
- Adds environment information to the issue body generated when the "Copy to Clipboard" or "File Issue" button is pressed on the file issue screen.
Environment information screen (note that the PersistentLogStoragePlugin is part of core and inside …
> Display environment info on developer menu

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- core/src/main/java/com/amplifyframework/auth/result/AuthSignUpResult.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxAuthBindingTest.java
After a successful sign up, the sign up result will now contain the user info.
Note that the user will be null for `resendSignUpCode()` and `confirmSignUp()` operations.
> feat(auth): Adds user info to sign up result

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
topological ordering was being applied to the individual hydration stream, i.e. given classes of model A and Model B, it appears that the original implementation was being applied on the model A hydration observable and Model B hydration observable. As such model A will always be compared to model A and B to B. Which I don't believe we want. What we want is to have models that depend on another hydrate first and so sort the hydration task by that.
Proposing a different implementation that first sorts the hydration tasks by the model's typological sort and then continue with Compete.concat which then handles the completion of each stream sequentially.
By submitting this pull request, I confirm that my contribution is made under the terms …
> fix(datastore): order hydration tasks topologically

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlKeyword.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTable.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
- core/src/main/java/com/amplifyframework/core/model/query/QueryOptions.java
- core/src/main/java/com/amplifyframework/core/model/query/QuerySortBy.java
- core/src/main/java/com/amplifyframework/core/model/query/QuerySortOrder.java
- core/src/main/java/com/amplifyframework/core/model/query/Where.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryField.java
- core/src/test/java/com/amplifyframework/util/WrapTest.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/BlogOwner.java
- This PR adds support for sorting on the `DataStore.query` API.  
- Also, currently customers can only query for pagination if they also provide a predicate.  This PR adds a new `paginated` method on the `Where` builder so that a customer can specify just pagination if desired (`Where.paginated(Page.firstPage())`).
Sample DX:
```
Amplify.DataStore.query(Todo.class,
Where
.matches(Todo.NAME.beginsWith("foo").and(Todo.DESCRIPTION.beginsWith("bar")))
.paginated(Page.firstPage())
.sorted(Todo.NAME.ascending(), Todo.DESCRIPTION.descending(), Todo.ID.ascending()),
response -> { },
error -> { });
```
> feat(DataStore) add sorting

- rxbindings/src/main/java/com/amplifyframework/rx/RxAdapters.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxApiBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreCategoryBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxHubBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxPredictionsBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxAdaptersTest.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxDataStoreBindingTest.java
1. Refactor RxAdapters, to clearly distinguish beteween cancelable and
void behaviors.
2. Update all bindings to make more deliberate use of the updated
RxAdapters
3. Update the RxDataStoreCategoryBehavior and RxDataStoreBinding with
new APIs that had been added to the vanilla category spec, but did
not make their way into the Rx spec.
> chore(rxbindings): cleanup adapters and align datastore apis

- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
Make upload calls progress-aware and return a cancellable operation. Notice the diff is against a feature branch (feature/rxbindings).
> feat(rxbindings) Make uploads progress-aware

- rxbindings/src/main/java/com/amplifyframework/rx/RxApiBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxGraphQlBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxOperations.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxApiBindingTest.java
Created an operation class to address the subscription use case. The callback-style API invokes an onStart consumer with the subscriptionId. To align with iOS that aspect of the functionality will look a bit different the rxbindings for the API category.
The `RxSubscriptionOperation` will have two methods that return observables. 
- observeSubscriptionData: emits one event for each item received via the subscription.
- observeConnectionState: when the onStart callback is triggered by the API category, we will publish a message to the observable and will save the subscriptionId as a property of the `RxSubscriptionOperation`. This will enable customer to listen for a start event if they wish, and also aligns our async functionality with the …
> feat(rxbindings) Create operation for subscription

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java
- aws-api-appsync/src/main/java/com/amplifyframework/core/model/types/JavaFieldType.java
- aws-api-appsync/src/test/java/com/amplifyframework/api/aws/SelectionSetTest.java
- aws-api-appsync/src/test/resources/selection-set-parent.txt
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageCustomTypeTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- aws-datastore/src/test/resources/base-sync-request-document-for-parent.txt
- aws-datastore/src/test/resources/create-parent-request.txt
- aws-datastore/src/test/resources/on-create-request-for-parent.txt
- aws-datastore/src/test/resources/update-parent-with-predicate.txt
- core/src/main/java/com/amplifyframework/core/model/ModelSchema.java
- core/src/main/java/com/amplifyframework/util/FieldFinder.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Address.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/AmplifyModelProvider.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Child.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/City.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Parent.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Phonenumber.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/schema.graphql
This PR fixes a bug in the selection set involving fields of custom types.
#702 
Custom types were not being transversed to build selection sets.  
This PR recursively introspects a custom type and adds its properties to the selection set.
*TODO* 
*Not Handled**
-  there are instances that might lead to infinite recursion, e.g. circular relationships so we may want to set a hard max_depth unrelated to datastore's model association max_depth .
> fix[aws-datastore] selection set for nested custom types

- rxbindings/src/main/java/com/amplifyframework/rx/RxOperations.java
ConnectionStateEvent needs to be public instead of package private.
> fix(rxbindings) Make ConnectionStateEvent public

- core/src/main/java/com/amplifyframework/devmenu/DevMenuFileIssueFragment.java
*Description of changes:* On the developer menu, show a toast when the issue body is copied on the file issue view.
> feat(core): show toast when copying issue on dev menu

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java
- core/src/main/java/com/amplifyframework/auth/AuthException.java
Add `CognitoAuthExceptionConverter` as a utility to centralize error mapping.
Resolve incorrect error messages and recovery suggestions.
Get rid of improper subclass `AWSCognitoAuthException` of `AuthException`. Now all the exception class are children of `AuthException`.
> Categorize auth errors

- .circleci/config.yml
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncClientInstrumentationTest.java
This was originally merged here: https://github.com/aws-amplify/amplify-android/pull/608
And I think it was accidentally reverted probably when resolving merge conflicts to disable coverage reports in this PR: https://github.com/aws-amplify/amplify-android/pull/677
This PR adds it back!
> chore(ci): improve integration test retry logic

- core/src/main/AndroidManifest.xml
*Issue #, if available:* [794](https://github.com/aws-amplify/amplify-android/issues/794)
*Description of changes:* Removes the intent filter from the developer menu activity in the AndroidManifest to avoid creating a second app icon for the developer menu when running the app.
> fix(core): remove dev menu app icon

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
Make `MutationProcessor` also emit `OutboxStatusEvent` hub event after each successful mutation processing.
> fix(aws-datastore): emit outbox status event on mutation process

- aws-api-appsync/src/main/java/com/amplifyframework/core/model/types/JavaFieldType.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/TypeConverter.java
After this gets merged, we should be able to re-merge @saltonmassally 's PR (https://github.com/aws-amplify/amplify-android/pull/730) which adds support for non-model types, as well as https://github.com/aws-amplify/amplify-android/pull/670, which updates the representation of `lastChangedAt` from `long` to `AWSTimestamp`.
> fix(datastore) Add missing converters for AWSTimestamp used by SQLiteStorageAdapter

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java
- aws-api-appsync/src/test/java/com/amplifyframework/api/aws/SelectionSetTest.java
- aws-api-appsync/src/test/resources/selection-set-parent.txt
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageCustomTypeTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- aws-datastore/src/test/resources/base-sync-request-document-for-parent.txt
- aws-datastore/src/test/resources/create-parent-request.txt
- aws-datastore/src/test/resources/on-create-request-for-parent.txt
- aws-datastore/src/test/resources/update-parent-with-predicate.txt
- core/src/main/java/com/amplifyframework/core/model/ModelSchema.java
- core/src/main/java/com/amplifyframework/util/FieldFinder.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Address.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/AmplifyModelProvider.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Child.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/City.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Parent.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/Phonenumber.java
- testmodels/src/main/java/com/amplifyframework/testmodels/parenting/schema.graphql
This reverts commit fbef1e8f9ccfb25e140bbb5199d018b016499958.
This PR is to add back @saltonmassally 's support for non-model types.    This functionality was originally added in https://github.com/aws-amplify/amplify-android/pull/730, but reverted in https://github.com/aws-amplify/amplify-android/pull/777 because the integration tests were failing due to incomplete support for Temporal types, but this support was just added in https://github.com/aws-amplify/amplify-android/pull/783.
> Revert "Revert "fix(aws-datastore): selection set for nested custom types (#730)" (#777)"

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java
Same as https://github.com/aws-amplify/amplify-android/pull/779, but with updated unit tests. 
Fixes https://github.com/aws-amplify/amplify-android/issues/778 and https://github.com/aws-amplify/amplify-android/issues/699.
> fix(api) owner with readonly access should be able to sub to on_delete, on_create, on_update

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
Previous work created a `DataStoreConfiguration`, and created a
two-phase configuration approach, wherein a file-based configuration can
be selectively overridden by a Java/Kotlin-provided configuration.
However, this work did not surface a public API for the user to actually
input their configuration.
As of this commit, it can be done by:
```kotlin
AWSDataStorePlugin(DataStoreConfiguration.builder()
.syncMaxRecords(1_000_000)
.build())
```
> feature: user can provide a datastore config

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java
- aws-api/src/test/resources/request-owner-auth.json
Addresses #749 by ensuring that we send the value of "username" for subscriptions in owner-based auth situations which AppSync is checking against from the Access token.
> fix(API): Fixes owner auth subscribe with email/phone sign-in

- CONTRIBUTING.md
The gradle configuration of mavenLocal should be done in `build.gradle(Module)` rather than `build.gradle(Project)`. The previous description was somehow misleading.
> Fix gradle configuration of mavenLocal in 'Consuming Development Versions'

- .circleci/config.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Gradle -> 6.6.1
OkHttp & MockWebServer -> 4.8.1
Android X AppCompat -> 1.2.0
Android X Test Core & Runner -> 1.3.0
Android X jUnit Extension -> 1.1.2
Espresso Core -> 3.3.0
Robolectric -> 4.4
> chore: use latest dependency versions

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/MobileClientSessionAdapter.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- core/src/main/java/com/amplifyframework/auth/AuthException.java
Changes the order of operations to the same one that iOS uses to avoid the bug in AWSMobileClient where it doesn't return identity id until getAWSCredentials is called.
> fix(Auth): Fixes guest / anonymous user access

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
Currently subscriptions do not work if you have both an owner auth directive with a READ operation and a group auth directive with a READ operation. This fixes that.
> Adds support for mixed owner and group based auth rules

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/TypeConverter.java
Not sure what the original intention of this static map was, but it is not currently used anywhere in the codebase, so this PR removes it.
> chore(datastore) Remove unused AWS_GRAPH_QL_TO_JAVA map

- aws-api-appsync/src/main/java/com/amplifyframework/core/model/types/JavaFieldType.java
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactoryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/TypeConverter.java
- core/build.gradle
- core/src/test/java/com/amplifyframework/core/model/ModelSchemaTest.java
- testmodels/src/main/java/com/amplifyframework/testmodels/personcar/Person.java
Follow up to https://github.com/aws-amplify/amplify-android/pull/839.    
- Removes unused code in `JavaFieldType` and `TypeConverter`
- Updates related tests so that our test models use `Temporal.Date` instead of `java.lang.Date`, since that is what codegen uses.
> chore(api) remove JAVA_DATE since codegen does not generate java.lang.Date

- aws-api-appsync/src/test/java/com/amplifyframework/api/aws/DefaultGraphQLRequestOptions.java
- aws-api/src/main/java/com/amplifyframework/api/aws/ApiGraphQLRequestOptions.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/DataStoreGraphQLRequestOptions.java
Return types on GraphQLRequestOptions wear @NonNull annotations, but the
implementing classes did not also do so.
This is quick touchup to add them to the implementing classes, too.
> chore: carry some annotations down to implementations

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
#854 
* Orchestrator operations now have timeout that depends on the number of models.
* Orchestrator now throws `TimeoutException` if `blockingAwait()` times out.
* Subscription processor operations also have timeout that depends on the number of models.
> fix(aws-datastore): make subscription timeout model count dependent

- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentConfigureTest.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
- core/src/main/java/com/amplifyframework/core/Amplify.java
- core/src/main/java/com/amplifyframework/core/category/Category.java
- core/src/test/java/com/amplifyframework/core/AmplifyTest.java
- core/src/test/java/com/amplifyframework/core/category/CategoryTest.java
- Fixes https://github.com/aws-amplify/amplify-android/issues/868 by throwing a useful exception if customer tries to use a plugin before calling Amplify.configure(). 
- One consequence of this new exception being thrown is that plugins need to be configured in a particular order now.  That is, Auth must be configured _before_ Analytics, API, Storage, and Predictions now.  I accomplished this by moving `Auth` to the top of the list of the `Amplify.buildCategoriesMap()` method.    Previously, the API category was actually being configured before the Auth category.  During configuration of API, it actually grabs a reference to the Auth plugin, and saves a reference to the Auth escape hatch, the `AWSMobileClient`.   At this point, the `AWSMobileClient` is instantiated, but not initialized. …
> (fix) Fail early and throw useful exception if customer forgets to call Amplify.configure

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/ServerSideEncryption.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/options/AWSS3StorageDownloadFileOptions.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/options/AWSS3StorageGetPresignedUrlOptions.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/options/AWSS3StorageListOptions.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/options/AWSS3StorageRemoveOptions.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/options/AWSS3StorageUploadFileOptions.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageUploadFileRequest.java
- core/src/main/java/com/amplifyframework/storage/options/StorageDownloadFileOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageGetUrlOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageListOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageRemoveOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageUploadFileOptions.java
Previously, Storage category did not have operation options available at a plugin level, which made it difficult to implement new options parameters without exposing it at a category level. This PR introduces plugin-level options for Storage operations so that AWS S3 specific parameters such as SSE (see #886) can be passed to an operation at a plugin-level.
> chore(aws-storage-s3): add plugin-specific options

- aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfiguration.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/DataStoreConfigurationTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
The following options are changed on the `DataStoreConfiguration.builder()`:
1. `dataStoreErrorHandler` -> `errorHandler`
2. `dataStoreConflictHandler` -> `conflictHandler`
3. `syncIntervalInMinutes` -> `syncInterval` (with required TimeUnit arg)
The corresponding accessor methods on the `DataStoreConfiguration` are also updated.
**Note:** This is technically a breaking change, but we don't have the `DataStoreConfiguration` usage documented anywhere, yet. So this is a good time to make the change, before we do.
Related: https://github.com/aws-amplify/docs/pull/2547
> fix: align datastore config builder methods to ios

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java
Owner-based auth currently works only for Cognito User Pools. This PR lets the plugin determine which auth provider to obtain the JWT token from instead of always assuming Cognito User Pools.
> feat(aws-api): support owner-based auth with oidc

- aws-api/src/test/java/com/amplifyframework/OwnerBasedAuthTest.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java
- aws-api/src/test/java/com/amplifyframework/api/aws/auth/FakeJWTToken.java
- aws-api/src/test/java/com/amplifyframework/api/aws/auth/OwnerBasedAuthTest.java
- aws-api/src/test/resources/request-owner-auth.json
- core/src/main/java/com/amplifyframework/core/model/AuthRule.java
* Refactor `AuthRule` (remnant from #903)
* Isolated the owner-based auth related tests from `AWSApiPluginTest`
* Refactor test structure to allow testing for different types of auth modes
* Implement `FakeJWTToken` generator to replace potentially sensitive actual ID tokens
* Add unit tests to confirm that owner field is added correctly for OIDC usecase
> chore(aws-api): refactor owner-based auth unit tests

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java
- aws-api-appsync/src/test/java/com/amplifyframework/api/aws/SelectionSetTest.java
- aws-api-appsync/src/test/resources/selection-set-ownerauth.txt
- aws-api/src/test/resources/request-owner-auth.json
- testmodels/src/main/java/com/amplifyframework/testmodels/ownerauth/OwnerAuthExplicit.java
- testmodels/src/main/java/com/amplifyframework/testmodels/ownerauth/schema.graphql
This PR fixes a bug where subscriptions will not be received at all for the schema below.    The fix is to modify the request for mutations to include the owner field to the selection set.  This ensures that when the mutation is broadcast out to the subscription listeners, the owner field will be hydrated, so it won't be filtered out, because it will be able to validate that the user is authorized to view this object.
```
type Post @model @auth(rules: [{ allow: owner }])
{
id: ID!
title: String!
}
```
> fix(api): Add owner field to selection set if implicitly defined

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/TestHubEventFilters.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreChannelEventName.java
- testutils/src/main/java/com/amplifyframework/testutils/HubAccumulator.java
The `DataStoreChannelEventName` enumeration contained two generations of
event names:
1. An initial set, which included `RECEIVED_FROM_CLOUD`, and
`PUBLISHED_TO_CLOUD`;
2. A larger set, containing many more, exposing various internal
details of the synchronization engine.
The later work partly duplicated the original work.
This commit *removes* the `PUBLISHED_TO_CLOUD`, which was duplicated by
the `OUTBOX_MUTATION_PROCESSED`,  and *renames* the
`RECEIVED_FROM_CLOUD` event to `SUBSCRIPTION_DATA_PROCESSED`.
> chore(aws-datastore): clarify hub event names

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/ItemChangeMapper.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/ItemChangeMapperTest.java
The `AWSDataStorePlugin` contained some logic to map from
`StorageItemChange` to `DataStoreItemChange`. This logic is needed to
convert between the `LocalStorageAdapter` APIs and the customer-exposed
`DataStoreCategoryBehavior` APIs.
In an effort to reduce the scope of responsibilities in
`AWSDataStorePlugin`, this conversion logic is split out into a new
`ItemChangeMapper` utility in the storage package.
> chore(aws-datastore): split out change type mapping

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/main/java/com/amplifyframework/api/aws/auth/AuthRuleProcessor.java
- aws-api/src/main/java/com/amplifyframework/api/aws/auth/AuthRuleRequestDecorator.java
- aws-api/src/test/java/com/amplifyframework/api/aws/auth/AuthRuleRequestDecoratorTest.java
- aws-api/src/test/java/com/amplifyframework/api/aws/auth/FakeJWTToken.java
Simple refactor to move the owner-based auth logic out of API plugin.
> chore(aws-api): move owner-based auth logic out of plugin

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategory.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategoryBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxDataStoreBindingTest.java
- testutils/src/main/java/com/amplifyframework/testutils/VoidResult.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousDataStore.java
Summary
- Added `void DataStore::start(Action onComplete, Consumer<DataStoreException> onError)` API 
- Added `void DataStore::stop(Action onComplete, Consumer<DataStoreException> onError)` API
- Added `Completable RxDataStore::start()` and `Completable RxDataStore::stop()` API
- Modified `DataStore::configure()` so that it does not call start anymore
- Modified `DataStore::clear()` so that it does not call start anymore
- The following scenarios now bubble up an exception to the user provided `Consumer<DataStoreException>`, instead of just logging a warning:
- [Timeout acquiring lock in Orchestrator::start()](https://github.com/aws-amplify/amplify-android/blob/89ed53d3f2b887c6b23439c776be133fa1ac0819/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java#L …
> feat(datastore) Add start and stop, and stop starting on configure and clear

- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncExtensions.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
- core/src/main/java/com/amplifyframework/AmplifyException.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreException.java
When a user is not authorized to read a model, an Unauthorized error is returned when trying to start a subscription.   This error is emitted on the `SubscriptionProcessor` buffer, which results in all subscriptions being cancelled.  To allow these users to still use DataStore, with a subset of models, this PR modifies this behavior to swallow Unauthorized errors before they reach the buffer.   Other types of errors will still be emitted and result in the same behavior.   
Specific changes:
- Added a subclass of `DataStoreException`, `DataStoreException.GraphQLResponseException`, so we can hold the `List<GraphQLResponse.Error>` objects from the response.
- When the subscription's `onFailure` callback is called, emit it to the buffer iff it's _not_ an Unauthorized exception.
- Updated …
> feat(datastore) swallow unauthorized errors for subscriptions

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
The SQLCommandFactory had required model instances to form SQL commands.
However, these conditions may be specified by passed conditions,
instead, and the model instances aren't necessary.
Applies additional null-safety guaranteed in the SQLiteCommandFactory
implementation.
> chore: simplify sqlcommandfactory

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/ModelUpgradeSQLiteInstrumentedTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/TestStorageAdapter.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/syncengine/MutationPersistenceInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/TopologicalOrderingTest.java
- core/src/main/java/com/amplifyframework/core/model/ModelSchemaRegistry.java
The ModelSchemaRegistry currently has a method named load(...). But, its
a ModelSchemaRegistry, not a ModelSchemaLoader.
Fix the naming.
> chore(aws-datastore): rename model registration method

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/LocalStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
The `DataStoreCategoryBehavior` provides a `delete(...)` method which
evaluates a predicate condition. This condition was never being passed
to the `LocalStorageAdapter`, though. It was just ignored.
This fix wires the predicate into the `LocalStorageAdapter` so that it
will actually be considered.
> fix: consider deletion predicate when requested

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/LocalStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/PersistentModelVersion.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncTimeRegistry.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
In the `DataStoreCategoryBehavior`, it is useful to have different
versions of save, delete, query, that consider or do *not* consider
query predicates.
However, `LocalStorageAdapter` is an internal interface. It does *not*
need convenience overloads in the same way that the public API does.
Instead, we can absorb the small inconvenience of passing
`QueryPredicates.all()` to a predicate-aware `save(...)` API, on the
`LocalStorageAdapter`, to the benefit of having a smaller, more
manageable API.
> chore(aws-datastore): remove superfluous save overload

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
A common `DataStore` use case is to call `DataStore.query` after the `READY` event has fired, like this:
```
Amplify.Hub.subscribe(HubChannel.DATASTORE,
{ DataStoreChannelEventName.READY.toString().equals(it.name) },
{ query() }
)
fun query() {
Amplify.DataStore.query(Blog::class.java,
{ LOG.debug("query succeeded") },
{ LOG.error("Error querying: " + it.message, it) }
)
}
```
This results in an infinite loop though, because `query` calls `start`, which publishes another `READY` event, etc.
This PR modifies the `start` method to not fire the `READY` event if DataStore has already been previously started, so the READY event will only be fired once.
> fix(datastore) only fire DataStore Hub READY event if not already started

- core/src/main/java/com/amplifyframework/core/model/AuthRule.java
PR for Datastore module of Amplify Flutter 
Provides a public constructor for AuthRule. 
When transmitting ModelSchema from Dart to Android, we need to recreate the AuthRule object.  However the existing API only allows AuthRule objects to be created from the annotation object..
> Add Builder for AuthRule

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
Currently joins only transverse the first level for nested models. This PR attempts to make SQLiteCommandFactory build joins for models with more than one level of nesting.
A potential gotcha for deeply nested models is the performance hit so we may want to make how deep we follow nesting configurable in DatastoreConfiguration and set and document a default limit.
A related Important fix here is the order of the limit and order by clause "The ORDER BY clause should appear before the LIMIT clause" or it results in an error
> recursively build joins for multilevel nested models

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
The SQL statement generated after merging #892 requires that we seed some test data to satisfy the join conditions (See diff below). I modified a couple of the tests to create Blog and BlogOwner records.
**Before**
```sql
SELECT `Post`.`id` AS `Post_id`, 
`Post`.`rating` AS `Post_rating`, 
`Post`.`status` AS `Post_status`, 
`Post`.`title` AS `Post_title`, 
`Post`.`postBlogId` AS `Post_postBlogId`, 
`Blog`.`id` AS `Blog_id`, 
`Blog`.`name` AS `Blog_name`, 
`Blog`.`blogOwnerId` AS `Blog_blogOwnerId` 
FROM `Post` LEFT JOIN `Blog` ON `Post`.`postBlogId`=`Blog`.`id` 
WHERE ((rating >= ? AND rating < ?) OR (rating = ? AND rating != ?));
```
**After**
```sql
SELECT `Post`.`id` AS `Post_id`, 
`Post`.`rating` AS `Post_rating`, 
`Post`.`status` AS …
```
> fix(aws-datastore): checkstyle and integration tests fix

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncClientInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfiguration.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreSyncExpression.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSync.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/QueryPredicateProvider.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/DataStoreConfigurationTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncClientTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMocking.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMockingTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/QueryPredicateTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
- aws-datastore/src/test/resources/sync-request-with-predicate.txt
This PR adds the selective sync feature to DataStore, which consists of the following parts:
- **Configuration**: Clients configure a `DataStoreSyncExpression`, which can resolve a `QueryPredicate`. 
- **Sync**: Sync requests sent to AppSync include this `QueryPredicate`, so that data is filtered out server side.
- **Subscriptions**:  AppSync's subscription operation does not currently support a `filter` argument, so this PR filters out incoming subscriptions that don't match the predicate on the client side.  In the future, if AppSync adds this, we can switch to server-side filtering, which will help reduce network traffic on the subscription socket.
- **Runtime Modification**: Clients can force a re-evaluation of their `DataStoreSyncExpression` at runtime by calling `DataStore.stop()`, …
> feat(datastore) selective sync

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSRekognitionService.java
- core/src/main/java/com/amplifyframework/predictions/models/Label.java
Exposed bounding boxes for objects of identified label. This property is already available in [iOS](https://github.com/aws-amplify/amplify-ios/blob/eb5b7ff98ae9ac090dc8c71e374b8f3bcb0ee472/Amplify/Categories/Predictions/Result/IdentifyLabelsResult.swift#L23) and [JS](https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/predictions/src/types/Predictions.ts#L236) libraries, but was not included in Android library as an undersight.
>  fix(aws-predictions): expose label instances' bounding boxes

- rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
Some of the `rxbindings` tests occasionally fail because progressConsumer emits 4 values instead of expected 5.  I believe this is due to some race condition, perhaps internal to `RxJava` where the `resultConsumer` completes before the last item is emitted to the `progressConsumer`.  This PR simplifies the implementation a bit.  I ran it 10+ times locally and can't get them to fail now, so hopefully this fixes the issue.
> chore(rxbindings): attempt to fix transient test failures

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactoryTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridCloudSyncInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- core/src/main/java/com/amplifyframework/core/model/ModelSchema.java
- core/src/test/java/com/amplifyframework/core/model/ModelSchemaTest.java
Version 1.6.3 of Amplify fixed an issue where associated/connected
models failed to sync down from AppSync, when being used with
Flutter-style `ModelSchema`.
Unfortunately, 1.6.3 stopped short of supporting associated models when
syncing *up* to AppSync, from the client.
This current change expands the `HybridCloudSyncInstrumentationTest`, to
demonstrate successful sync up and down from AppSync.
To support this, request-forming logic is extracted from the
`ModelSchema`, and split across the `AppSyncRequestFactory` (for DataStore)
and the `AppSyncGraphQLRequestFactory` (for API category). The DataStore
flavor of the factory is expanded to properly build requests when
dealing with associations in Flutter-style `SerializedModel`s.
By submitting this pull request, I confirm that my …
> fix: associated Flutter models can sync to cloud

- rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
The `awaitCount` method doesn't allow you to specific a timeout, but it does timeout after 5 seconds.  
> chore(rxbindings) second attempt to fix transient test failures

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
Currently, any error on the `save(...)` or `delete(...)` methods will cause
the observation channel to terminate. Better would be to keep it alive, so
that it can continue to emit new updates. If and when there is an error
saving or deleting, that error will be communicated by the error
callback on at the call site. Future work may add a new error event type
that could be emitted by the `observe(...)` API.
Resolves: https://github.com/aws-amplify/amplify-android/issues/984
> fix(aws-datastore): keep observations active despite errors

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
Resolves: https://github.com/aws-amplify/amplify-android/issues/977
> fix(aws-datastore): Prevent NPE while inspecting GraphQL errors

- core/src/main/java/com/amplifyframework/core/model/ModelField.java
When the formerly-existing `type` member was renamed to
`javaClassForValue`, the label in `toString()` was not updated.
Here's a fix for that.
> fix: fix field label in toString() of ModelField

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/ModelSyncMetricsAccumulator.java
When deletions are merged to the local store, the storage adapter might
throw an error, if there's nothing left to delete.
The existing code tries to work around this by first checking if there
is a matching instance before attempting to delete it.
Instead, we will swallow deletion failures and log a verbose message.
Resolves: https://github.com/aws-amplify/amplify-android/issues/1011
> fix(aws-datastore): idempotent deletions from merger

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/DataStoreHubEventFilters.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridAssociationSyncInstrumentationTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridTemporalSyncInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/OutboxMutationEvent.java
When the `MutationProcessor` successfully processes an item from the
Mutation Outbox, it will publish an `OutboxMutationProcessed` event to the
Hub.
The AppSync response itself contains no information about *what type* of
model has just been published. That information is only available before
making the request.
As a consequence, we cannot inspect the model name from the AppSync
response, and instead, we should pull it out of the `MutationProcessor`'s
request context.
To validate this fix, the various instrumentation tests are updated to
use the `getModelName()` code path on the `OutboxMutationProcessed` event.
Resolves: https://github.com/aws-amplify/amplify-android/issues/1012
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix(aws-datastore): null modelName in OutboxMutationProcessed

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java
- aws-api-appsync/src/test/java/com/amplifyframework/api/aws/SelectionSetTest.java
When building selection sets to be dispatched to AppSync, the native
branch of the code was applying owner auth rules, but the Flutter branch
was not.
Resolves: https://github.com/aws-amplify/amplify-android/issues/1019
> fix(aws-datastore): Add owner to SelectionSet for Flutter

- amplify-tools/amplify-tools-gradle-plugin/src/main/groovy/com/amplifyframework/tools/gradle/plugin/AmplifyTools.groovy
CLI requires that we use `forcePush` if we want to deploy changes during the init command. This PR incorporates this change into the build tools to address issues users found while walking through the getting started guide.
> fix(amplify-tools): Add --forcePush to init

- .github/ISSUE_TEMPLATE/bug_report.md
A few questions for the Android team:
1. A meta-proposal: _should_ we even bother with a template?
2. If so, is this the right amount of direction to provide, or is it too wordy, already?
You can see a rendered version of the template [here](https://github.com/aws-amplify/amplify-android/blob/ae3f599d2e1b9d2c51469adae9ba911a72155a7e/.github/ISSUE_TEMPLATE/bug_report.md).
> chore: add a bug report template

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- Fixes #1010 ("Unable to acquire orchestrator lock. Transition currently in progress") (also reported in https://github.com/aws-amplify/amplify-android/issues/977#issuecomment-737041548). Previously, if you call two DataStore operations right after each other, the second one would usually fail.  Each operation calls start, which previously required obtaining a semaphore, within a 2 second timeout.  Previously, the semaphore was locked until the API sync completed, but with this PR, the lock is released as soon as the storage observer is initialized (which only takes a few milliseconds).  
> fix(datastore) release startStopSemaphore when start returns, not when API sync completes

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignOutOptions.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthWebUISignInOptions.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- core/src/main/java/com/amplifyframework/auth/options/AuthSignOutOptions.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
This ability was added to AWSMobileClient [in this PR ](https://github.com/aws-amplify/aws-sdk-android/pull/2152)so adding options in Amplify Auth to be passed through and gain the same capability. 
Fulfills #678 
> feat(Auth): Adds the ability to specify a custom browser for web UI sign in/out

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterDeleteTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
SQLiteStorageAdapter now checks if item exists before attempting delete. If not, then operation "succeeds" and returns a dummy item change instance, but does not publish any change.
> fix(aws-datastore): deleting nonexistent model instance no longer fails

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterSaveTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
Conditional write is useful for making sure that no data is written without being sure of the condition of existing data. This also means that _conditional insert_ cannot be performed since insertion only happens when there _is_ no existing data.
Currently, Android DataStore ignores user-provided predicates when performing an insertion and successfully carries out the operation. This PR modifies the behavior so that an insertion triggers error callback if _any_ condition has been provided by the user.
Resolves: https://github.com/aws-amplify/amplify-android/issues/1034
> fix(aws-datastore): conditional insert no longer succeeds

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/OutboxMutationFailedEvent.java
`Objects#hash(Object...)` is unavailable for SDK < 19, so this PR replaces it with `ObjectsCompat`.
> chore: use objects compat hash function

- aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/AppSyncSigV4SignerInterceptor.java
`OkHttp3` sets the body of a `DELETE` call to a byte array of length 0. The
v4 signer interceptor only checks if the body is null and if its not it sets the
content type to `application/json`. This causes an invalid REST request to
be created. Fixed by expanding the check to also make sure the body has a
content length greater than 0.
Github Issue: https://github.com/aws-amplify/amplify-android/issues/1028
Tested in the app that had the original problem and verified to fix the issue.
> [aws-api] Fix DELETE calls not working with v4 signer

- core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java
- core/src/main/java/com/amplifyframework/core/Resources.java
- core/src/main/java/com/amplifyframework/devmenu/EnvironmentInfo.java
The Amplify documentation suggests to configure the library with this
call:
```kotlin
Amplify.configure(applicationContext)
```
When configured in this way, the library will attempt to load a file
from the the user's application project. The file is expected to live at
`app/src/main/res/raw/amplifyconfiguration.json`.
If this file is *not* present, the previous error message was not very
helpful. This commit updates the error message, to give the user a
direct call to action.
This PR also updates a few related resource loading messages, to make
their error cases more clear.
> chore: improve missing config error messages

- aws-api-appsync/src/main/java/com/amplifyframework/core/model/types/JavaFieldType.java
- aws-api-appsync/src/main/java/com/amplifyframework/util/GsonObjectConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AWSAppSyncScalarType.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteDataType.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/TypeConverter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncConflictUnhandledErrorTest.java
The Amplify DataStore leverages GraphQL to define its data models.
Therefor, our intention is to support a strict superset of the primitive
types described by the GraphQL specification.
While implementing the DataStore, we overlooked that the GraphQL "Float"
type is a double-precision value. The SQL adapter is able to accomodate
this, currently. However, our Java codegen stores a float value, and we
look for values of Float type while serializing and deserializing object
data.
Unfortunately, we need to continue to support that behavior, since
customers will have Float values in their models. None-the-less, the
Flutter consumer of this library rightly wants to use the actual GraphQL
scalar types, and see the same behavior accross iOS and Android. As a
result of these constraints, we must …
> fix(aws-datastore): store schema float as a java double

- scripts/pull_backend_config_from_s3
As a developer, I want the integration test config files to be
downloaded quickly. To help with this, we can grab them all in parallel,
and then wait to terminate the script until the last job has completed.
> feature: parallelize integ test config downloads

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/OutboxMutationEvent.java
DataStore Hub [event documentation](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/android#outboxmutationprocessed) states that the OutboxMutationProcessed event will contain a `_lastChangedAt` field of type `Int`. Currently the event is being sent with `_lastChangedAt` as type `Temporal.Timestamp`. This PR switches that to sending a Unix epoch (type `java.lang.Long`) instead.
*Notes:*
- This is a breaking change to existing Android apps. The odds do seem extremely low that any Android app has been digging deep into the internals of the OutboxMutationProcessed DataStore hub event.
- This now matches the iOS format.
- Fixes a crash in the Amplify Flutter SDK that is assuming the value passed matches the documentation. I'm not sure this event …
> fix(aws-datastore): Send Unix epoch in OutboxMutationEvent instead of Temporal.Timestamp

- README.md
It hasn't been working for a few months. An out-of-date badge that always shows poor coverage isn't helping anyone.
> chore: remove codecov bade from readme

- .idea/codeStyles/Project.xml
- CONTRIBUTING.md
Specify the editor codestyle configuration for the import order and line length to match our checkstyle rules.
> chore: add IDE codestyle to match checkstyle expectations

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/utils/ErrorInspector.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
- core/src/main/java/com/amplifyframework/util/Error.java
Partially addresses #1013 
By ignoring foreign key constraint violation during sync, #1013 issue no longer crashes DataStore.
Even with the best effort to ensure that the foreign key constraints are met on the client side, it is possible that the remote storage simply does not enforce foreign key violation. This guarantees the possibility of encountering a foreign key constraint violation during sync to be non-zero (e.g. cascading deletion failed halfway while publishing; a race condition arose from multi-device operation; or an entry was inserted directly to remote store). There are two options to deal with a failure during initial sync:
1. Issue a DELETE mutation on the orphaned remote model that caused the crash.
2. Ignore the error.
The first option is not …
> fix(aws-datastore): ignore foreign key error during sync

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLOperation.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- core/src/main/java/com/amplifyframework/api/graphql/GraphQLOperation.java
- core/src/main/java/com/amplifyframework/api/graphql/GraphQLResponse.java
No functional changes, just a small refactor to simplify the `GraphQLOperation`.
> chore(api) remove responseType from GraphQLOperation, since we already know it from the GraphQLRequest

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
Several customers (and internal team members) have been concerned about log messages like:
```
Column with name posts does not exist
```
which are logged when querying for a Post object.   
For a typical Blog / Post / Comment schema, the Blog table does not contain any references to its `Post`'s because each `Post` contains a reference to its `blogID`.
This log could be useful if there is in fact a missing field that should be there.  For this reason, I'm going to leave it, but change the log level to verbose.
> chore(datastore) missing column name should be a verbose log since it is expected for relationship fields

- aws-analytics-pinpoint/build.gradle
- aws-api-appsync/build.gradle
- aws-api/build.gradle
- aws-auth-cognito/build.gradle
- aws-datastore/build.gradle
- aws-predictions/build.gradle
- aws-storage-s3/build.gradle
- build.gradle
- core/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- rxbindings/build.gradle
AWS SDK => 2.20.1.
AndroidX Navigation 2.3.2.
Gradle => 6.7.1.
Robolectric was already upgraded to 4.4. However, the AutoValue
annotations workaround is no longer needed for Robolectric as of 4.4.
So, we are able to remove that from the dependencies blocks, too.
AGP is being held at 4.0.1. We are going to skip 4.1.x and move directly
to 4.2.
> chore: update dependencies

- aws-api/src/main/java/com/amplifyframework/api/aws/operation/AWSRestOperation.java
- aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestRequestFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/operation/AWSRestOperationTest.java
iOS doesn't fire any terminal event when a REST operation is canceled.
When an Rx subscription is disposed, neither onError nor onComplete is
called.
In those cases, there is no notification of cancelation/disposal.
This commit aligns Android's behavior, so that an operation will
terminate silently, when canceled.
> fix(aws-api): dont fire error if rest op canceled

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
When DataStore is started, the sync downloads all items, even deleted ones.   An attempt is made to delete these from the local store.   If it's a fresh install, or the app is already in sync, a warning is logged that the item is already deleted.  This isn't really a warning or anything to be concerned about, so this PR raises the log level to verbose.
> chore(datastore) verbose log instead of warn when deleting a non existent item

- aws-api/src/androidTest/assets/create-comment.graphql
- aws-api/src/androidTest/assets/create-event.graphql
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLInstrumentationTest.java
- configuration/instrumentation-tests.gradle
A few tweaks related to get the `subscriptionReceivesMutationOverApiKey` test passing again. The previous backend being used was created using the console and relied on some custom resolvers (Events app sample from the AppSync console). These changes allow the test to work with the resolvers generated by the CLI. 
Updated the name of the Amplify app used by the DataStore tests.
> chore(api): Fix integration tests

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
Previously, there was an issue where mutation responses were not merged because the merge was attempted before the item was removed from the queue.  This was fixed in #1051 by wrapping the merge in `Completable.defer()`.   Thanks @kjones!
This PR moves the `Completable.defer()` into the merge method itself.  This ensures that the fix will be effective for any calls to the `merge` method, such as calls from the `SyncProcessor`.  This PR also adds a test that fails without this fix, or the fix from #1051.
> fix(datastore) Defer merger.merge to avoid failure if outbox has mutation

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- core/src/main/java/com/amplifyframework/auth/AuthException.java
During sign-in with the Cognito hosted web UI, a Chrome Custom tab will
pop up. The user may fill in their sign-in information. However, they
may also exit out of the tab, in which case the sign-in will be
cancelled.
The current behavior is to fire an exception on the onError callback
when this occurs. That exception looks like this:
```
AuthException{
message=Sign in with web UI failed
cause=[...mobile client...] AuthNavigationException{
message=user cancelled
}
recoverySuggestion=See attached exception for more details
}
```
This commit updates the exception that gets returned, to something more
specific, that a user could catch explicitly:
```
ActionCancelledException{
message=The user cancelled the sign-in attempt, so it did not complete.
cause=[...mobile client...] …
```
> chore: add explicit error for signin cancelation

- aws-api-appsync/src/main/java/com/amplifyframework/util/GsonFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncClientTest.java
- aws-datastore/src/test/resources/update-blog-owner-with-predicate.txt
- aws-datastore/src/test/resources/update-meeting.txt
Fixes https://github.com/aws-amplify/amplify-android/issues/1054
> fix(api) serialize nulls on requests to support setting fields to null

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/LocalStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/PersistentModelVersion.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
Small simplification to the `LocalStorageAdapter` and it's subclasses - this removes the `query` helper method which takes no predicate.  Code which previously used this method now just uses the `query` method that does take a predicate, and just passes `Where.matchesAll()`.
> chore(datastore) remove overloaded query method in favor of just one

- configuration/consumer-rules.pro
Numerous consumers report missing symbols when using the library in a
release build (where R8 shrinking is enabled.)
Customers have reported success by keeping the com.amazonaws.** and
com.amplfyframework.** classes, as well as enums.
Resolves: https://github.com/aws-amplify/amplify-flutter/issues/156
Resolves: https://github.com/aws-amplify/amplify-flutter/issues/286
Resolves: https://github.com/aws-amplify/amplify-flutter/issues/188
> fix: export proguard rules for consumers

- core/src/main/java/com/amplifyframework/core/Amplify.java
- core/src/test/java/com/amplifyframework/core/AmplifyTest.java
Resolves: https://github.com/aws-amplify/amplify-android/issues/1108
> Throw AlreadyConfiguredException on reconfiguration attempt

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/SynchronousStorageAdapter.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterDeleteTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/LocalStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLPredicateTest.java
- core/src/main/java/com/amplifyframework/core/NoOpAction.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategory.java
- core/src/main/java/com/amplifyframework/datastore/DataStoreCategoryBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreCategoryBehavior.java
* Added method to `DataStoreCategoryBehavior` interface for deleting models by type & predicate
* Implemented it on DataStore plugin and local storage engine
* Added tests
> datastore(feat): support delete by model type with predicate

- aws-api-appsync/src/main/java/com/amplifyframework/core/model/temporal/Temporal.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageReservedWordTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreErrorHandler.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/TypeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/RetryStrategy.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- configuration/checkstyle-rules.xml
- core/src/main/java/com/amplifyframework/analytics/AnalyticsPlugin.java
- core/src/main/java/com/amplifyframework/api/ApiPlugin.java
- core/src/main/java/com/amplifyframework/auth/AuthPlugin.java
- core/src/main/java/com/amplifyframework/core/NoOpConsumer.java
- core/src/main/java/com/amplifyframework/core/async/NoOpCancelable.java
- core/src/main/java/com/amplifyframework/datastore/DataStorePlugin.java
- core/src/main/java/com/amplifyframework/devmenu/PersistentLogStoragePlugin.java
- core/src/main/java/com/amplifyframework/hub/AWSHubPlugin.java
- core/src/main/java/com/amplifyframework/hub/HubPlugin.java
- core/src/main/java/com/amplifyframework/logging/LoggingPlugin.java
- core/src/main/java/com/amplifyframework/predictions/PredictionsPlugin.java
- core/src/main/java/com/amplifyframework/predictions/result/IdentifyResult.java
- core/src/main/java/com/amplifyframework/storage/StoragePlugin.java
- core/src/main/java/com/amplifyframework/util/FieldFinder.java
- core/src/main/java/com/amplifyframework/util/Immutable.java
- core/src/test/java/com/amplifyframework/core/BadInitLoggingPlugin.java
- core/src/test/java/com/amplifyframework/logging/FakeLoggingPlugin.java
- core/src/test/resources/logging-config.json
- rxbindings/src/main/java/com/amplifyframework/rx/RxApiCategoryBehavior.java
- testutils/src/main/java/com/amplifyframework/testutils/EmptyAction.java
* Allow empty methods to be concisely written as `{}` without triggering `WhitespaceAround` check.
* Make empty classes, empty methods, and empty constructors use more concise pattern.
> chore: allow empty methods in checkstyle

- .github/ISSUE_TEMPLATE/bug_report.md
The latest version of the CLI now outputs logs in `~/.amplify/logs/amplify-cli-<date>.log`.  This PR adds a reference to this on our bug template so that customers can include these logs, if applicable.
> chore: Add reference to CLI logs on bug report template

- core/src/main/java/com/amplifyframework/devmenu/LogEntry.java
- core/src/main/java/com/amplifyframework/devmenu/PersistentLogger.java
- core/src/test/java/com/amplifyframework/devmenu/PersistentLogStoragePluginTest.java
The developer menu logging functionality used `java.time.LocalDateTime` to store time of log messages.  The `java.time` library either requires API 26 or above, or requires customers to be on Android Studio 4.0 and above, and make changes in their `build.gradle` to enable desugaring.  There no particular reason to use `java.time.*` over `java.util.Date` in this case, so this PR changes the dev menu to use `java.util.Date`.
> chore(devmenu) use java.util.Date instead of java.time for dev menu logging

- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelConverter.java
- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModel.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterSaveTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/StorageItemChange.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/StorageObserver.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/ItemChangeMapperTest.java
- aws-datastore/src/test/resources/update-blog-owner-only-changed-fields.txt
Currently when performing an update mutation, all fields are sent in the request to AppSync.  This prevents customers from being able to benefit from the AutoMerge conflict resolution strategy.  If AppSync receives a mutation with an outdated version, it attempt to intelligently merge the update, if the fields that have changed do not overlap with the fields that changed in the conflicting mutation.  However, since the client sends all fields, the benefits of AutoMerge will never occur.   Instead, all mutations with outdated versions will silently fail.  The update will not occur, and the original model is returned back to the client.
This PR updates DataStore so that only the fields that have _changed_ will be sent to the server.   A comparison is done with the current version of the …
> feat(datastore) only include changed fields in update mutations

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
The `deleteModelTypeWithPredicateCascades` and `deleteModelTypeWithPredicateDeletesData` integration tests are currently failing on the `main` branch due to `patchItem` being null in one scenario.  This PR fixes the issue.   I believe it was broken when https://github.com/aws-amplify/amplify-android/pull/1110 was merged.   Even though the tests passed on the PR, they failed after the changes were squashed and merged to `main`.
> fix(datastore) fix crash caused by null patchItem

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMockingTest.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/MatchAllQueryPredicate.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/MatchNoneQueryPredicate.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryPredicates.java
Clients should use the `QueryPredicates.all()` and `QueryPredicates.none()`.  The underlying `MatchAllQueryPredicate` and `MatchNoneQueryPredicate` classes should be package-private.
> Make MatchAll/NoneQueryPredicate classes private

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterSaveTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
https://github.com/aws-amplify/amplify-android/issues/908#issuecomment-766284487
Using `Where.id()` internally to match model ID broke query function for models that had `@BelongsTo` relationship with another model. This PR reverts that change and adds a test case.
> fix(datastore): dont use where.id() function

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/VersionRepository.java
- core/src/main/java/com/amplifyframework/core/model/query/QuerySortBy.java
- core/src/main/java/com/amplifyframework/core/model/query/Where.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryField.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryPredicateOperation.java
Add an additional parameter to `QueryField` instance called `modelName` so that SQL queries can be constructed without ambiguous column names.
This PR aims to address #908 without introducing breaking changes for existing customers. While this PR itself does not yet fix the issue, it allows for model codegen to be enhanced to support better usage of built-in query fields from code-generated models. This way, the enhanced codegen will fix the issue and allow all customers to rely directly on the built-in query fields instead of needing to construct their own.
> fix(core): query field now stores model name

- README.md
- rxbindings/README.md
Amplify Android has moved from 1.6.11 to 1.16.11.
See [the Amplify Android 1.16.11 release notes](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.16.11) for more details.
> chore: publicize 1.16.11 in the README.md.

- aws-api-appsync/src/main/java/com/amplifyframework/core/model/query/predicate/GsonPredicateAdapters.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLPredicateTest.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/NotContainsQueryOperator.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryField.java
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryOperator.java
- core/src/test/java/com/amplifyframework/core/model/query/predicate/OperatorTest.java
- core/src/test/java/com/amplifyframework/core/model/query/predicate/PredicateTest.java
Adds support for `notContains` query operator.  [Our documentation](https://docs.amplify.aws/start/getting-started/integrate/q/integration/android#query-todos) indicates that we do support this, but it looks like it was missed during the initial implementation.   This PR adds support for it.
On amplify-ios, it is also [not supported](https://github.com/aws-amplify/amplify-ios/blob/e2f7f64e2a501f3b2807481ca921e71710c82b22/Amplify/Categories/DataStore/Query/QueryField.swift#L34-L44), so I opened https://github.com/aws-amplify/amplify-ios/issues/1049.
On amplify-js, it [is supported](https://github.com/aws-amplify/amplify-js/blob/6e28eaf37525ce231d7793bf82a960046fc7f8f4/packages/datastore/src/types.ts#L295-L299).  
Note: I also discovered there are 3 other AppSync operators not supported by …
> feat(datastore) add support for notContains query operator

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Author.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Blog.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/BlogOwner.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Comment.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Post.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/PostAuthorJoin.java
DataStore's `query` supports filtering by field of a related model (e.g. "Filter `Blog` by `BlogOwner`'s name"). However, we don't currently support sorting queried result by related model (e.g. "Sort `Blog` by `Blog`'s name" is *supported* but "Sort `Blog` by `BlogOwner`'s name" is *not*). This PR uses new `QueryField` property to allow this.
> feat(datastore): support sorting by related models

- core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
The Rx Bindings were missing getUrl() with and without options. Added
them, and made some very minor nearby cleanups. Added unit tests for
new bindings.
> chore: add missing storage apis to rxbindings

- aws-datastore/src/main/AndroidManifest.xml
When running the DataStore on versions of Android prior to API level 21,
it will be necessary for the customer to add MultiDex support to their
project, explicitly.
This is a platform limitation covered in depth in the Android
documentation:
https://developer.android.com/studio/build/multidex#mdex-pre-l
The DataStore's AndroidManifest.xml selected one of the three documented
approaches. However, applications which set their own application class
name will get a build error:
> Manifest merger failed : Attribute application@name [...] is also
> present at [com.amplifyframework:aws-datastore ...
This is easy to resolve by adding:
> 'tools:replace="android:name"'
However, newcomers may not understand what is causing this error. It
would be better for us to step out of the way and let users …
> fix: remove MultiDexApplication from DataStore manifest

- rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
The Rx storage upload and download operations are "hot" operations,
which emit progress events as soon as the operations are started.
There is a short period of time wherein it is possible that no one is
listening to the progress updates yet, until a subscription is formed.
Therefore, it's possible to "miss" an update.
To improve the resilience of our tests, we add a short (100ms) delay
before the first emission, which allows time to setup the subscriber, so
that it can be sure to receive all of the progress values in a
repeatable way.
> fix: add a small initial delay to failing rxbinding test

- rxbindings/src/main/java/com/amplifyframework/rx/RxAmplify.java
Even though there are no actual Rx-enabled methods in the Logging or
Analytics categories, it is convenient to have all of the various
Amplify categories available in the single RxAmplify facade. Doing so
means that a user can use RxAmplify at all times, without having to mix
in miscellaneous calls to the original Amplify facade as well.
> chore: add logging and analytics to rx bindings

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
Improve error messaging, to make https://github.com/aws-amplify/amplify-android/issues/1163 easier to debug.
> fix(datastore) include cause on error thrown when observing storage times out

- core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java
Disable the dev menu by default.
Customers can still enable and use the dev menu with the follow code:
```
val config = AmplifyConfiguration.builder(ctx)
.devMenuEnabled(true)
.build()
Amplify.configure(config, ctx)
```
> chore(devmenu) set dev menu disabled by default

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
*Description of changes:* Model instances are of always of type `SerializedModel` when the requests are coming from flutter and so always fail to retrieve modelSchema when querying based on instance type. This PR replaces the use of `getModelSchemaForModelInstance` with `getModelSchemaForModelClass`
> fix: Delete relationships fix for flutter

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
*Issue #, if available:* Followup https://github.com/aws-amplify/amplify-android/pull/1168
> fix(datastore): save root instance instead of creating multiple iterators

- rxbindings/src/main/java/com/amplifyframework/rx/RxAdapters.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxOperations.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxAdaptersTest.java
Resolves: https://github.com/aws-amplify/amplify-android/issues/1119
> fix(rxbindings): don't emit errors to disposed subscriber

- build.gradle
- configuration/publishing.gradle
- core-kotlin/gradle.properties
- gradle.properties
By default, modules will use the `VERSION_CODE` and `VERSION_NAME` in `amplify-android/gradle.properties`.
Individual modules may override this value, if they use their own versioning. Such modules must populate `VERSION_CODE` and `VERSION_NAME` in _their own_ `gradle.properties`, e.g. `core-kotlin/gradle.properties`. 
> chore: enable per-module versioning by override

- README.md
- gradle.properties
- rxbindings/README.md
This release contains the Kotlin extensions, which is definitely a feature big enough for a minor version bump, but since they are versioned separately (starting with `0.1.0`),  I don't think it makes sense to bump the minor, so I only bumped the patch.
> release: 1.16.14

- configuration/publishing.gradle
When trying to build an app that depends on `implementation 'com.amplifyframework:aws-datastore:1.16.14'`, the following build error occurs:
```
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find amplify-android:core:unspecified.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/amplify-android/core/unspecified/core-unspecified.pom
- https://jcenter.bintray.com/amplify-android/core/unspecified/core-unspecified.pom
Required by:
project :app > com.amplifyframework:aws-datastore:1.16.14
> Could not find amplify-android:aws-api-appsync:unspecified.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/amplify-android/aws-api-appsync/unspecified/aws-api-appsync-unspecified.pom
- …
```
> ci: fix maven publishing

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/TestApiCategory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/main/java/com/amplifyframework/api/aws/OkHttpConfigurator.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java
- aws-api/src/test/java/com/amplifyframework/api/aws/auth/OwnerBasedAuthTest.java
While constructing the AWSApiPlugin, the customer may now apply
additional configurations to the OkHttpClient instance that is used
internally.
For example, a user may like to add custom headers to outgoing requests:
```java
AWSApiPlugin plugin = AWSApiPlugin.builder()
.customizeClient("apiName", okHttpClientBuilder -> {
okHttpClientBuilder.addInterceptor(chain -> {
return chain.proceed(chain.request()
.newBuilder()
.addHeader("specialKey", "specialValue")
.build();
);
});
})
.build();
```
The same facility may be used to set custom timeouts, e.g.:
```java
AWSApiPlugin plugin = AWSApiPlugin.builder()
.customizeClient("apiName", okHttpClientBuilder -> {
okHttpClientBuilder.connectTimeout(10, TimeUnit.SECONDS);
})
.build();
```
Resolves: …
> feat(aws-api): Support Custom OkHttp Configurations

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java
This PR fixes the issue causing our build to fail on the `main` branch.  It broke after https://github.com/aws-amplify/amplify-android/pull/1149/ was merged, which is strange, because the build on that PR passed.    The reason for this though, is because https://github.com/aws-amplify/amplify-android/pull/1121/ was merged in between, which refactored part of `SQLiteModelTree` such that the body of the try block was no longer ever throwing a `DataStoreException`. 
> chore: remove DataStoreException from catch since try body never throws

- build.gradle
- core-kotlin/gradle.properties
- gradle.properties
Per the [documentation for `versionCode`](https://developer.android.com/studio/publish/versioning), it's only use is to prevent users from downgrading to an APK with a lower `versionCode` than the version currently installed.  Since `amplify-android` is a library, and not an app, this doesn't apply.
I believe we can remove `versionCode` to simplify our release process.  Let's give this a try during our next release and see if it works. 
> chore: remove versionCode

- .github/workflows/release_pr_approval_count.yml
This workflow checks the number of approvals for a PR with the following characteristics:
- base = main
- head = release
- PR title starts with "chore(release)"
This workflow will be configured as a required check against the main branch. PRs not meeting the above criteria will be exempt from this check.
> chore(ci): create workflow to check approval count

- aws-api/src/main/java/com/amplifyframework/api/aws/operation/AWSRestOperation.java
- aws-api/src/test/java/com/amplifyframework/api/aws/operation/AWSRestOperationTest.java
- core-kotlin/src/test/java/com/amplifyframework/kotlin/api/KotlinApiFacadeTest.kt
- core/src/main/java/com/amplifyframework/api/rest/RestResponse.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxApiBindingTest.java
> fix(rest-api) Expose HTTP headers in RestResponse

- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModel.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlCommand.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlKeyword.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
- core/src/main/java/com/amplifyframework/core/model/Model.java
Performance Improvements:
- Querying pages of results from the API now happens in parallel with saving items to local storage.   This improves performance by about 0.5 seconds.  The benefit is small right now, only because SQL write performance is still pretty bad. 
- For `save` and `delete` without a predicate (e.g. `QueryPredicates.all()`), I eliminated a redundant query to see if the model exists for a given predicate, by short circuiting if the provided predicate is `QueryPredicates.all()`
- Use `SELECT EXISTS(SELECT 1 FROM tableName...` to check if a modelExists instead of doing a full query and checking if the Cursor has any results.   Improves performance from ~1.5ms to ~0.5ms for checking if a model exists.  
Other Improvements:
- Reduced `SQLiteStorageAdapter` thread pool size to …
> fix(datastore) improve storage adapter performance

- scripts/devicefarm-test-runner-buildspec.yml
To troubleshoot integration tests, we need to ensure that the reports are exported correctly after execution. In certain instances, tests are failing and the reports are not getting generated. It's not clear why this is happening, but by creating the report output directory before running the build, we can at least allow the post-build event to run successfully.
> chore(ci): create test report dir before execution

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncExtensions.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
AppSync doesn't support runtime filtering for subscriptions today.  This means there's no way to limit the network traffic transmitted via subscriptions, and for some applications, the amount of traffic could overwhelm a client.   Some customers wish to disable subscriptions on the backend, but allow DataStore to proceed with sync queries, and continue working, just without real-time updates.
Customers can throw an `OperationDisabled` error in their VTL response mapping template which will be ignored by the DataStore `SubscriptionProcessor`.    Note: This is subject to be removed in the future, and should not be used without prior consultation with AWS.
> chore(datastore): ignore OperationDisabled subscription errors

- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
Fixes transient unit tests.   Integration tests are still failing for an unrelated issue.
> chore: fix transient syncCanHandle1000Pages test by increasing timeout

- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelConverter.java
- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModel.java
- aws-api-appsync/src/test/java/com/amplifyframework/datastore/appsync/ModelConverterTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/GsonPendingMutationConverter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/InMemoryStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/GsonPendingMutationConverterTest.java
- testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Blog.java
There were two bugs introduced by https://github.com/aws-amplify/amplify-android/pull/1110, which changed the update mutation behavior to only send fields that had _changed_.  To do that, we convert the Java models to `SerializedModel` objects, because it allows us to represent the absence of a field, since the field is stored as a `Map`:
1. Items saved while offline (and thus persisted into the `PendingRecord` SQLite table) were not persisted correctly, and the mutations ended up getting sent to AppSync with all of the fields set to null, except for "id". (https://github.com/aws-amplify/amplify-android/issues/1199).  I've fixed this by updating the `PendingMutationConverter` to actually work for `SerializedModel` objects.
2. Mutations for models with children weren't created properly. …
> fix(datastore) Make PendingMutationConverter work for SerializedModel

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncClientInstrumentationTest.java
The `AppSyncClientInstrumentationTest::testAllOperations` test was broke by https://github.com/aws-amplify/amplify-android/pull/1249, because `createdAt` and `updatedAt` fields were added to the `BlogOwner` model.    Those fields are now requested in the selection set, but we weren't expecting them in the response previously.  
There's not really a way we can know what to _expect_ for these fields, since they are set by the server, so instead, this PR sets them to null on the actual object returned from AppSync.  Then, when we compare it to the expected value, it succeeds.
> chore(datastore): fix integration test failure due to new timestamp fields

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- aws-datastore/src/test/resources/base-sync-request-with-predicate-group.txt
- aws-datastore/src/test/resources/base-sync-request-with-predicate-operation.txt
- aws-datastore/src/test/resources/sync-request-with-predicate.txt
- core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryPredicateGroup.java
When a filter is provided on a sync operation, AppSync will attempt to optimize the request by performing a DynamoDB query, rather than a scan.  A query is only possible if the filter contains the hash key, or the hash key and the sort key.     To perform this optimization, the [AppSync resolver requires the presence of a top level "and"](https://github.com/aws-amplify/amplify-cli/blob/018548a772cab14a1f99fb3d2413eb720142a562/packages/graphql-key-transformer/src/KeyTransformer.ts#L1105) group.   
This PR wraps the sync expression filter with an AND group if the predicate provided by the customer is just a predicate operation, rather than a group.
> fix(datastore): optimize sync queries with predicates by wrapping in an AND group

- aws-datastore/src/test/resources/base-sync-request-with-predicate-group.txt
- aws-datastore/src/test/resources/base-sync-request-with-predicate-operation.txt
When https://github.com/aws-amplify/amplify-android/pull/1225 was merged, the associated unit tests started failing, because they hadn't been updated to include the createdAt and updatedAt timestamps yet, introduced by https://github.com/aws-amplify/amplify-android/pull/1249.
This PR fixes those tests.
> chore(datastore): fix unit tests by adding createdAt updatedAt

- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/Auth.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
Calling `Amplify.Auth.getCurrentUser` while using the core-kotlin facade will crash if signed out with this error:
```
java.lang.NullPointerException: delegate.currentUser must not be null
at com.amplifyframework.kotlin.auth.KotlinAuthFacade.getCurrentUser(KotlinAuthFacade.kt:278)
at com.amplifyframework.kotlin.auth.KotlinAuthFacadeTest.getCurrentUserSucceedsWhenSignedOut(KotlinAuthFacadeTest.kt:788)
```
This PR eliminates the crash by making the return type nullable.
> fix(kotlin): getCurrentUser return type should be nullable

- CONTRIBUTING.md
- build.gradle
- configuration/publishing.gradle
- scripts/codebuild_build.sh
- scripts/maven-release-publisher.yml
Create a CodeBuild definition (buildspec file) that executes the `uploadArchives` gradle task. This build definition will run inside a CodeBuild project, which will be defined in the `amplify-ci-support` repo in a separate PR.
The buildspec is fairly straightforward. The one callout is that it pulls in any sensitive information from Secrets Manager by using the `secrets-manager` section and makes them available via environment variables. These environment variables are prefixed with `ORG_GRADLE_PROJECT_` which automatically sets gradle project properties. This ensures that at no point, that information is passed in via the command line. 
See [CodeBuild docs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-s …
> chore(build): add buildspec for publishing to maven

- .github/workflows/release_pr.yml
- scripts/fastlane/Fastfile
- Modified `Fastfile` to use shared lane from `amplify-ci-support`. As part of this process, we import the shared lane and override `build_parameters`
- `build_parameters` is expected to return a hash with the repo-specific settings for the release. One thing to note for this repo is that we return multiple items under the `releases`. This allows us to version different submodules differently (if necessary).
> chore: use shared lane file

- core/src/main/java/com/amplifyframework/core/Amplify.java
- core/src/test/java/com/amplifyframework/core/AmplifyTest.java
fix: throws AlreadyConfiguredException when addPlugin called after configuration.
> fix: throws AlreadyConfiguredException when configured == true

- rxbindings/build.gradle
- rxbindings/src/main/java/com/amplifyframework/rx/RxOperations.java
> fix: Use ObjectsCompat since Objects is API 19+

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmSignInOptions.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/Auth.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
- core/src/main/java/com/amplifyframework/auth/AuthCategory.java
- core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
- core/src/main/java/com/amplifyframework/auth/options/AuthConfirmSignInOptions.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
Adds ConfirmSignInOptions for Auth.confirmSignIn API. 
> fix: adds ConfirmSignInOptions for confirmSignIn API method

- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionOperation.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/DataStoreCategoryConfigurator.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridOfflineInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
In preparation for some of the upcoming multiauth work. 
Added a builder for the DataStore plugin since we're going to be adding a new parameter. Rather than keep the constructor growing, I figured I might as well refactor if. No change in functionality. Users will have the option to use the builder or continue to use the constructors, which are marked as deprecated, but are still around. 
Simplified the builder for SubscriptionOperation. Rather than the multi-interface approach, I'm just following the same pattern we do for all the other builders throughout our codebase. No change in functionality
> chore: add builders for DS and SubscriptionOperation

- core/src/main/java/com/amplifyframework/core/model/annotations/AuthRule.java
- testmodels/src/main/java/com/amplifyframework/testmodels/ownerauth/OwnerAuthNonDefaultProvider.java
Part of the multi-auth project. This PR focuses solely on adding a string field to the AuthRule annotation. This is an optional string field which will default to blank for backwards compatibility.
> chore(core): add provider to auth rule annotation

- aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfiguration.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/DataStoreConfigurationTest.java
Customers today can configure DataStore syncExpressions like this: 
```
Amplify.addPlugin(new AWSDataStorePlugin(DataStoreConfiguration.builder()
.syncExpression(Post.class, () -> Post.RATING.gt(5))
.build()));
```
Support for sync expressions is now being added to Flutter, but in Flutter, there are no generated Java model classes.  We need to provide an alternative way of specifying sync expressions.    This PR adds a new method to the `DataStoreConfiguration.Builder` so that sync expressions can be declared using a `ModelSchema`, instead of a `Class<? extends Model>`.    This will enable Flutter to do something like this:
```
ModelSchema postModelSchema = ...
Amplify.addPlugin(new AWSDataStorePlugin(DataStoreConfiguration.builder()
.syncExpression(postModelSchema, () -> …
```
> fix(datastore): add syncExpression method to configuration builder that takes a ModelSchema

- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModel.java
*Issue #, if available:* https://github.com/aws-amplify/amplify-android/issues/1340
Fixes bug introduced in https://github.com/aws-amplify/amplify-android/pull/1319/
> fix(api): check for null ModelSchema to prevent crash in SerializedModel toString method

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/AuthorizationType.java
- core/src/main/java/com/amplifyframework/core/model/AuthRule.java
- core/src/main/java/com/amplifyframework/core/model/AuthStrategy.java
- core/src/test/java/com/amplifyframework/core/model/ModelSchemaAuthRulesTest.java
This PR replaces #1314, which was moving `AuthorizationType` to core. This PR does the following instead:
- Adds an enum (`AuthStrategy.Provider`) to represent the `provider` field of an @auth rule.
- Adds an `authProvider` field to the `AuthRule` model. This field transforms the string value from the `AuthRule` annotation interface into one of enum values. If the `AuthRule` annotation has an empty string for its `provider` field, we use the default provider for the strategy.
- Creates a method on the `AuthorizationType` enum to translate an `AuthStrategy.Provider` into an `AuthorizationType`.
**NOTE** I made the `Provider` enum nested to `AuthStrategy` to make their association clearer. I though creating an `AuthProvider` enum would …
> refactor:add enum to represent auth rule provider

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- testutils/src/main/java/com/amplifyframework/testutils/Await.java
*Issue #, if available:* #1263
- Move the onSuccess callback outside of the for loop so that it is only invoked one time
> fix(Auth): prevent multiple invocations of success callback for updateUserAttributes

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequest.java
- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/AuthModeStrategyType.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMocking.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- core/src/main/java/com/amplifyframework/core/model/ModelSchema.java
This PR does the following:
- **aws-api-appsync**
* Adds `AuthModeStrategyType` that represents the auth mode strategies supported by the API plugin. Current values are MULTIAUTH and DEFAULT.
* Adds an `authModeStrategyType` field to the `AppSyncGraphQLRequest` object. This will effectively serve as the flag that indicates whether an API request should be handled in multi-auth mode or not. Not setting this field when constructing the request means using the DEFAULT strategy which is the current behavior.
- **aws-datastore**
* Adds a field called `authModeStrategy` (to be consistent with the JS implementation) of type `AuthModeStrategyType`. Customers will be able to set this value via the `AWSDataStore.Builder` when constructing the …
> feat: add supporting types for multi-auth

- aws-api/src/main/java/com/amplifyframework/api/aws/auth/ApiRequestDecoratorFactory.java
#1350 
`ApiRequestDecoratorFactory` would throw if no `AWSCredentialsProvider` was explicitly provided when configuring the API plugin, but the intended behavior was to use `AWSMobileClient` by default. This additional logic is added in this PR.
(Also changed to switch statements for slight performance boost :) )
> fix(api): default to mobile client for iam auth mode

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/activities/HostedUIRedirectActivity.java
Adds redirect activity with `com.amplifyframework.auth` namespace.
It does the exact same thing as `com.amazonaws.mobile.client.activities.HostedUIRedirectActivity`.
See https://github.com/aws-amplify/aws-sdk-android/pull/2472 for information on what it does.
Doc update:
https://github.com/aws-amplify/docs/pull/3285
> fix(auth): add hosted-ui redirect activity with amplify namespace

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmSignUpOptions.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/Auth.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
- core/src/main/java/com/amplifyframework/auth/AuthCategory.java
- core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
- core/src/main/java/com/amplifyframework/auth/options/AuthConfirmSignUpOptions.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
**Issue #, if available:**
Part 1 of fix for `amplify-flutter` issue [#575](https://github.com/aws-amplify/amplify-flutter/issues/575).
`amplify-flutter` depends on this fix to implement capability of passing `clientMetadata` via `confirmSignUp` API.
**Description of changes:**
* Replicate `ConfirmSignUpOptions` for `confirmSignUp` API method that is supported by [amplify-ios auth plugin](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin%2BClientBehavior.swift#L29).
> fix: Add ConfirmSignUpOptions for confirmSignUp API method

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.java
- testutils/src/main/java/com/amplifyframework/testutils/Await.java
*Issue #, if available:* https://github.com/aws-amplify/amplify-android/issues/1345
- Remove invocation of error callback in the download/upload state change listener
- Add test for duplicate error callbacks 
> fix: remove duplicate error callback in storage

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmSignInOptions.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
https://github.com/aws-amplify/amplify-flutter/issues/576
Allows userattributes in confirmSignIn
> feat(aws-auth-cognito): Allows userattributes in confirmSignIn

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java
- core-kotlin/src/main/java/com/amplifyframework/kotlin/datastore/KotlinDataStoreFacade.kt
- core/src/main/java/com/amplifyframework/auth/AuthException.java
*Issue #, if available:*  #1102 
Throw AuthException with correct message and recovery suggestion mapped to Cognito exception instead of generic exception.
> fix(auth): throw correct auth exception for code mismatch

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
**Issue #, if available:**
Flutter open issues: [#615](https://github.com/aws-amplify/amplify-flutter/issues/615)
**Description of changes:**
`amplify-flutter` relies on `ModelProvider.modelSchemas` to leverage `amplify-android` functionality. The original subscription timeout period incrementing mechanism doesn't cover `modelSchemas`, thus, we saw subscription timeout issues when attempting subscribe more than 5 models in Flutter.
Changed to use  `modelSchemas` method to get the number of models. This change should be safe, as `ModelProvider` has the [default method](https://github.com/aws-amplify/amplify-android/blob/891ae1c5fdd5bf008315f82c343ed1868739d635/core/src/main/java/com/amplifyframework/core/model/ModelProvider.java#L49) that ensures the coherence of `models` and …
> fix(datastore): fix subscription timeout period not increasing

- aws-datastore/src/androidTest/AndroidManifest.xml
- aws-storage-s3/src/main/AndroidManifest.xml
Resolves https://github.com/aws-amplify/amplify-android/issues/896
`WRITE_EXTERNAL_STORAGE` was deprecated in Android 10.  It was used for accessing files on an external disc, or other locations outside of the app sandbox.  As far as I know, we don't need it, and I'm not sure why it was added in the first place.  If we did need it, any customer building an app that targets Android 10 (released almost 2 years ago) or above would have reported an issue to us about it, and that hasn't happened.
> chore: remove deprecated WRITE_EXTERNAL_STORAGE permission

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterCustomPrimaryKeyTest.java
- core/src/main/java/com/amplifyframework/core/model/SerializedModel.java
- testmodels/src/main/java/com/amplifyframework/testmodels/ecommerce/AmplifyModelProvider.java
Currently, when you do a `DataStore.save(…)`, we query for the item in SQLite, and compute the difference in fields.  Then, when the mutation gets sent to AppSync, it only sends the fields that have changed, as well as the partition key and all sort keys, since those are always required.   
If the model being saved defines a custom primary key other than `id`, an error occurs on [this line](https://github.com/aws-amplify/amplify-android/blob/release_v1.18.0/aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModel.java#L90) in the method that computes the difference of fields.    Essentially, since `id` is not part of the primary key, it isn’t getting included, but `SerializedModel` actually still requires a hardcoded `id` field. 
This PR resolves the issue by …
> fix(datastore): explicitly include id field for update mutations, to support types with custom primary keys

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
*Issue #, if available:* https://github.com/aws-amplify/amplify-android/issues/1388
*Description of changes:* Increases timeout in `SubscriptionProcessor` to the same timeouts used in the `Orchestrator` to account for slow network connections.
> fix: increase timeout for subscriptions to be established on slow networks

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridOfflineInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/642
- update the creation of serialized models to recursively create nested serialized models with the queried data
> feat(datastore): Return nested data for belongsTo associations in datastore

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignUpOptions.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
Adds clientMetadata to AWSCognitoAuthSignUpOptions
> feat(aws-auth-cognito): Adds clientMetadata to AWSCognitoAuthSignUpOptions

- scripts/Gemfile
- scripts/Gemfile.lock
Fixing dependabot alerts received for `addressable` gem
> chore:fix dependabot alert for addressable gem

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousDataStore.java
Added tests for immediate and consecutive DataStore save operations.
> chore: Added tests for consecutive saves

- aws-api/src/test/java/com/amplifyframework/api/aws/auth/AuthRuleRequestDecoratorTest.java
- core/src/main/java/com/amplifyframework/core/model/AuthStrategy.java
The CLI does not support the `AWS_LAMBDA` auth type yet, but will soon.  When it does, the code-generated models will have this annotation:  
`@ModelConfig(authRules = { @AuthRule(allow = AuthStrategy.CUSTOM, provider = "function") })`
The following table shows the allowed combinations of authorization strategies and providers.
|  | owner | groups | public | private | custom |
| --- | --- | --- | --- | --- | --- |
| userPools | X | X |  | X |  |
| oidc | X | X |  |  |  |
| apiKey |  |  | X |  |  |
| iam |  |  | X | X |  |
| function |  |  |  |  | X | 
This PR adds the CUSTOM case to the `AuthStrategy` enum, which the code generated models will rely on.
> feat(api) add CUSTOM case to AuthStrategy

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequest.java
Selection set could not be specified in `AppSyncGraphQLRequest` could not be set by the builder because its setter was never exposed. Added public `AppSyncGraphQLRequest.Builder#selectionSet(SelectionSet)` method.
> fix(api): expose selectionSet in request builder

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLOperation.java
#1273 
Fix crash due to attempting to invoke client of already canceled call.
- added  isCanceled() check in start to guard against calls that were canceled but still in queue
- added isCanceled() check in failure callback (for calls that hit 20sec socket timeout)
> fix: check for canceled call to fix RxJava crash

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthResendUserAttributeConfirmationCodeOptions.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthUpdateUserAttributeOptions.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthUpdateUserAttributesOptions.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/Auth.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
- core/src/main/java/com/amplifyframework/auth/AuthCategory.java
- core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
- core/src/main/java/com/amplifyframework/auth/options/AuthResendUserAttributeConfirmationCodeOptions.java
- core/src/main/java/com/amplifyframework/auth/options/AuthUpdateUserAttributeOptions.java
- core/src/main/java/com/amplifyframework/auth/options/AuthUpdateUserAttributesOptions.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
- Add options/metadata to updateAttribute
- Add options/metadata to updateAttributes
- Add options/metadata to resendUserAttributeConfirmationCode
*Testing Info:*
I have manually tested that metadata added to each of these methods is accessible in Lambda triggers. I have also tested the edge cases listed below, by first confirming the behavior of each method in v1.22.0, and then confirming the behavior is the same with these changes.
**updateAttribute & updateAttributes**
- No Network → AuthException, cause = AmazonClientException
- Non-existent attribute → AuthException, cause = InvalidParameterException
- Invalid Attribute value → AuthException, cause = InvalidParameterException
- Lambda Exception → AuthException, cause = …
> feat(auth): add options for updateAttribute, updateAttributes, resendUserAttributeConfirmationCode

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlKeyword.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLPredicateTest.java
*Issue #, if available:* #1434
Predicate logic was not handling null values for equal and not equal operations.
This PR addresses this bug bug checking for null values when the operator is EQUAL or NOT EQUAL and constructs the SQL statement accordingly.
> fix: handle null values for predicates

- .github/workflows/release_pr.yml
By switching to using `${{secrets.GITHUB_TOKEN}}`, we have one less secret to rotate.
> chore: use GH-generated token

- aws-predictions/src/androidTest/java/com/amplifyframework/predictions/aws/AWSPredictionsIdentifyCelebritiesTest.java
This test doesn't appear to be valid anymore. I don't see any docs confirming this, but the service no longer throws an exception for image resolutions below 80x80. I tried even 1x1 and no exception is thrown.
> fix(predictions):remove invalid test

- aws-geo-location/build.gradle
- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/Credentials.kt
- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/MapsApiTest.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/AWSLocationGeoPlugin.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/Errors.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/AmazonLocationService.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/GeoService.kt
- core/src/main/java/com/amplifyframework/geo/GeoCategory.java
- core/src/main/java/com/amplifyframework/geo/GeoCategoryBehavior.java
- core/src/main/java/com/amplifyframework/geo/models/MapStyleDescriptor.java
- core/src/main/java/com/amplifyframework/geo/options/GetMapStyleDescriptorOptions.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousGeo.java
* Added `getMapStyleDescriptor` API to Geo category for fetching map style document.
* Implemented `getMapStyleDescriptor` in plugin using `AmazonLocationClient`
* Added instrumentation test
> feat(geo): add getMapStyleDescriptor API to Geo

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
#1489
`AWSCognitoAuthPlugin` erroneously assumed that `username` will be non-null as long as `userId` is non-null. This resulted in a NPE when constructing a new `AuthUser` object. This PR adds null-check for `username` before doing so, returning a `null` for current user if either value is `null`. This is in alignment with the [current iOS behavior](https://github.com/aws-amplify/amplify-ios/blob/3f700ac8b16dbfed3d7d40b461d508d6e0f7d1ab/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter.swift).
> fix(auth): null-check username when getting current user

- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModelAdapter.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/ModelUpgradeSQLiteInstrumentedTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/syncengine/MutationPersistenceInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/GsonPendingMutationConverterTest.java
- core/src/main/java/com/amplifyframework/core/model/ModelConverter.java
Fix an issue discovered here: https://github.com/aws-amplify/amplify-flutter/pull/847#pullrequestreview-751534593
* Ensure the serialized model sent along with mutation box enqueued event containing nested model schema
* Updated a few unit tests that involve `SchemaRegistry` to ensure the testing schemas to be cleared after tests
----
> fix(datastore): ensure attaching nested model schema to SerializedModel

- aws-geo-location/build.gradle
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/AWSLocationGeoPlugin.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/Errors.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/AmazonLocationService.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/GeoService.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/AmplifyMapLibreAdapter.kt
Added `setStyle` convenience method that sets map style on maplibre map instance using correct thread types for different tasks.
Previously, user would have to:
1. launch the map getter (`MapView#getMapAsync()`) from the _main UI thread_, 
2. fetch style from the worker thread (`Geo#getMapStyleDescriptor()`) from the _worker thread_,
3. and then apply style on the map (`MapboxMap#setStyle()`) from the _main UI thread_
This resulted in making one simple step of loading a style on the map quite complicated. This PR adds a service executor to the plugin to enforce that network requests are made from a worker thread, and adds a convenience method that behaves like MapLibre's `setStyle()` method.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> feat(geo): add convenience method for setting map style

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/MultiAuthSyncEngineInstrumentationTest.java
Some of the multi-auth tests were failing sporadically likely due to the amount of data being sync'd. The sync expression should prevent that.
> chore: add sync expression to multi-auth test

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- aws-datastore/src/test/resources/base-sync-request-with-predicate-match-none.txt
#987
Add match none predicate check to AppSync request predicate parser logic.
To match none, we use the assumption that every model requires an ID and filters for models whose `ID = null`.
> feat(datastore): Add support for parsing match none predicate in AppSync request builder

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
*Issue #, if available:* [Comment on 1268](https://github.com/aws-amplify/amplify-android/issues/1268#issuecomment-862718673)
*Description of changes:* When querying with Where.id, adds the model name to the primary key field in the where clause of the query to address the SQLite ambiguous column exception that occurs when the model has a foreign key.
> fix(datastore): Specify model name when querying with Where.id

- scripts/pull_backend_config_from_amplify
- scripts/pull_backend_config_from_s3
Test setup scripts `pull_backend_config_from_s3` and `pull_backend_from_amplify` no longer store configuration files inside `amplify-android` project directory. They will be generated in an external location and be referenced by a symlink. 
Note: for this change to take place, the existing configuration files must be deleted and the script must be executed again.
> chore: config files no longer get generated inside project directory

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLOperation.java
#1444
The `onGoingCall` object of `Call` type can be null if the `start()` is either not called or fails before initializing `onGoingCall`. Hence, adding null check before calling `cancel` on it is necessary. 
Note: NPE check is necessary but might not be satisfactory fix to the mentioned issue.
> fix(api): Add null check before cancelling Call object.

- aws-geo-location/gradle.properties
- maplibre-adapter/gradle.properties
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/view/MapLibreView.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/view/support/AttributionInfoView.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/view/support/ViewFadeVisibility.kt
- maplibre-adapter/src/main/res/drawable/ic_twotone_info_24.xml
- maplibre-adapter/src/main/res/drawable/map_attribution_text_background.xml
- maplibre-adapter/src/main/res/values/colors.xml
- maplibre-adapter/src/main/res/values/dimens.xml
- maplibre-adapter/src/main/res/values/strings.xml
- force-disable MapLibre's logo and attribution info by overriding the map options
- introduce a support view to display an info icon and toggle the content attribution text (see attached screenshots for reference)
- the icon comes from the standard Android library to respect platform UX guidelines
- the visibility state toggle performs a cross-fade between icon and text for a smooth UX
- text functionality is not exposed as a public API (i.e. cannot be overridden by developers)
**Default state (icon):**
**Expanded state (text):**
---
> fix(maplibre-adapter): add content attribution info to map view

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
reduce latency by initializing datastore once to enhance test reliability
> chore: initialize datastore once for sync test suites

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java
https://github.com/aws-amplify/amplify-flutter/issues/767
Currently, implicit belongs to relationship in the GraphQL schema (e.g. `Blog` has many `Comment`, but `Comment` does not have an explicit belongs to field) does not form foreign key relationship in the SQLite database. This causes cascading deletion logic to fail with an NPE. This error will be swallowed with this change to prevent unexpected crashes.
> fix(aws-datastore): halt cascading delete if foreign key not found

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
#1613 fixed an issue where other test cases will fail as well in `BasicCloudSyncInstrumentationTest` but one test case continues to fail occasionally. It may potentially be related to the bug with `HubAccumulator`.
> chore: ignore unstable test case

- aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java
- aws-api-appsync/src/test/java/com/amplifyframework/api/aws/JustIDGraphQLRequestOptions.java
- aws-api-appsync/src/test/java/com/amplifyframework/api/aws/SelectionSetTest.java
- aws-api-appsync/src/test/resources/selection-set-post-nested.txt
*Issue #, if available:* https://github.com/aws-amplify/amplify-android/issues/1610
- Update `getModelFields` method for flutter support to match the version used for native apps. The changes are identical to the changes in https://github.com/aws-amplify/amplify-android/pull/1585/files, but are applied to the version of `getModelFields` that is used for flutter support
> fix(aws-api-appsync): update getModelFields for flutter support

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
*Issue #, if available:* #1606
*Description of changes:* When configuring the AWSApiPlugin for REST with `AMAZON_COGNITO_USER_POOLS` as the authorization type, configuration fails due to trying to fetch auth tokens when creating the `RequestDecorator`. This PR moves the creation of the `RequestDecorator` inside the interceptor so the auth tokens aren't retrieved when configuring the AWSApiPlugin.
> fix(api): create RequestDecorator in interceptor

- build.gradle
- core-kotlin/build.gradle
Currently we are not publishing JavaDoc for core-kotlin for Amplify-Android and the SDK and hence adding Dokka to publish it.
- Added Dokka and corresponding configuration
- Applied it in core-kotlin package
> [FIX][651]Adding Dokka to the core-kotlin module

- aws-storage-s3/build.gradle
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/configuration/AWSS3PluginPrefixResolver.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/configuration/AWSS3StoragePluginConfiguration.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageGetPresignedUrlOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageListOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageRemoveOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadInputStreamOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/utils/S3Keys.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/StorageComponentTest.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/configuration/AWSS3StoragePluginConfigurationTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperationTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageGetPresignedUrlOperationTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageListOperationTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageRemoveOperationTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperationTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadInputStreamOperationTest.kt
- maplibre-adapter/build.gradle
#910 
- Add support for custom prefix resolver for storage category.
```
Amplify.addPlugin<Plugin<*>>(AWSS3StoragePlugin(AWSS3StoragePluginConfiguration {
awsS3PluginPrefixResolver = object: AWSS3PluginPrefixResolver {
override fun resolvePrefix(
accessLevel: StorageAccessLevel,
targetIdentity: String?,
onSuccess: Consumer<String>,
onError: Consumer<StorageException>
) {
/*
* Add code to resolve custom prefix
* */
onSuccess.accept("custom/bucket/path/")
}
}
}))
```
> feat: Add support for custom prefix resolver

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- core/src/main/java/com/amplifyframework/core/model/SerializedCustomType.java
- core/src/main/java/com/amplifyframework/core/model/SerializedModel.java
- core/src/test/java/com/amplifyframework/core/model/SerializedModeTest.java
- core/src/test/resources/serialized-model-nests-custom-type-data.json
https://github.com/aws-amplify/amplify-flutter/issues/1370
Ensure `SerializedModel` and `SerializedCustomType` to return an empty list for non-nullable field with type `[ACustomType]` to support amplify-flutter use cases.
> fix(datastore): SerializedModel returns null for non-nullable list field

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/util/CognitoAuthExceptionConverter.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/Auth.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
- core/src/main/java/com/amplifyframework/auth/AuthCategory.java
- core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
- core/src/main/java/com/amplifyframework/auth/AuthChannelEventName.java
- core/src/main/java/com/amplifyframework/auth/AuthException.java
- maplibre-adapter/build.gradle
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxAuthBindingTest.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
*Description of changes:* Adds the deleteUser API to Amplify.Auth to delete a user from the user pool.
**Note:** This PR is not ready to be merged in yet.
> feat(auth): Add deleteUser API

- aws-datastore/src/androidTest/assets/schemas/phonecall/call.json
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterModelConverterTest.java
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java
- testmodels/src/main/java/com/amplifyframework/testmodels/phonecall/Call.java
- testmodels/src/main/java/com/amplifyframework/testmodels/phonecall/schema.graphql
*Issue #, if available:* #1621
*Description of changes:* When querying a model with an AWSDateTime or AWSTime field(s) and a predicate of the same type, places those fields in a consistent format so they can be accurately compared to return the correct query results.
> fix(datastore): compare datetime values in consistent format when querying

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
[1667](https://github.com/aws-amplify/amplify-android/issues/1667)
Fixing the crash on connectivity error caused because rx subscription is already disposed.
> Connectivity crash fix

- aws-api/src/main/java/com/amplifyframework/api/aws/auth/IamRequestDecorator.java
DELETE REST API calls have the "content-type: application/json" header added to them. The AWS backend does not allow this for requests with an empty body. This issue was originally fixed in the AppSyncSigV4SignerInterceptor but was reintroduced due to a switch to the new system of signing requests.
Resolves: https://github.com/aws-amplify/amplify-android/issues/1683
Added a check to see if the `contentLength()` of a request body is more then 0 to the `isEmptyRequest` definition. (Same as the original fix)
> [aws-api] Fix DELETE rest calls not working with IamRequestDecorator

- aws-geo-location/gradle.properties
- maplibre-adapter/gradle.properties
- maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/Credentials.kt
- maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewTestActivity.kt
- maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewTestActivityTest.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/view/AmplifyMapView.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/view/ClusteringOptions.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/view/MapLibreView.kt
*Description of changes:* Adds the ability to enable clustering on the map and customize various properties of the clusters (e.g., cluster color). Also fixes an issue where calling MapLibreView.setStyle(...) would remove the symbol on click listener, meaning the popup with place info would not show up when clicking on a place on the map.
Clustering enabled with the default clustering options:
> feat(maplibre-adapter): add clustering to map view

- aws-api-appsync/src/main/java/com/amplifyframework/api/graphql/GsonResponseAdapters.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- aws-api/src/test/resources/error-null-message.json
#1599 
com.amplifyframework.api.graphql.GraphQLResponse.Error#Error expects message parameter to be NonNull.
In case, the MESSAGE_KEY (="message") is not passed in error JSON, it is not initialized.
This change adds a default string in such exceptional cases.
Note: This is pulled from [fork](https://github.com/millsjustin/amplify-android/tree/jm/provide-default-message-when-null)
> Provide default message for GraphQLResponse.Error when null/missing

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageListOperation.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/StorageService.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/utils/S3Keys.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/StorageComponentTest.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/operation/AWSS3StorageListOperationTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/utils/S3KeysTest.java
*Issue #1697*
Updated the logic to strip off the prefix appended to S3 service keys. Previously the string removed from the service keys was based on the accesslevel but with the addition of [custom prefix](https://github.com/aws-amplify/amplify-android/pull/1659) this logic is not always valid. To fix this issue, prefix append is passed to extractAmplifyKey function and removed from the sericeKey. 
- Added unit test.
- Integration tests are passing.
- No
> fix: Update logic to extract S3 keys from list api response

- aws-api-appsync/src/main/java/com/amplifyframework/core/model/temporal/Temporal.java
- aws-api-appsync/src/test/java/com/amplifyframework/core/model/temporal/TemporalDateTimeTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
*Issue #, if available:* 1584
Updated DateTimeParseException to parent class Exception which was added in Api 1 and will not crash the app and has no bearing on the result as we do not actually do anything with the exception.
I checked the unit tests to ensure they did not fail and fixed the one that did
- [ x] Updated Unit Tests
- [ x] No
> fix(datastore): #1584 When DateTimeParseException is not available for lower apis

- .github/workflows/notify_comments.yml
Notify new comments on closed issues.
> chore: notify comments on closed issues

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterDeleteWithCpkTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- core/build.gradle
- testmodels/src/main/java/com/amplifyframework/testmodels/customprimarykey/AmplifyModelProvider.java
Delete with class and predicate as parameters support for custom primary key
- [X ] Added Unit Tests
- [ X] Tested on frontend (Add Screenshots)
- [ X] Successful logs (Attach them to the PR)
2022-05-28 22:32:30.118 8305-8348/com.example.mydatastoreapp I/MyAmplifyApp: Deleted a Team11
2022-05-28 22:32:30.155 8305-8349/com.example.mydatastoreapp I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=SerializedModel{id='"May27 11:010.8900713438174679project11id"#"May27 11:01 project11"', serializedData={name=May27 11:01 project11, createdAt=null, project11TeamId=null, id=May27 11:010.8900713438174679project11id, updatedAt=null}, …
> Delete with class and predicate as parameters support for custom primary key

- scripts/Gemfile.lock
Fix error: Dependabot only supports uninterpolated string arguments to eval_gemfile. Got plugins_path
> chore: upgrade jmespath to version 1.6.1

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
*Issue #, if available:* 1729
The Delete api does allow for a request to be passed in and therefore this check was removed to accommodate that.
- [ x] No
> Fix for adding data back to the delete request if it contains data as that is allowed for the Delete api

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
*Issue #, if available: 1485*
Added a hub event when the session is expired and user is signed in.
- [ x] Added Unit Tests
- [ x] Successful logs (Attach them to the PR)
`2022-06-15 03:53:44.971 13225-13225/com.example.myapplication I/Tutorial: Initialized Amplify
2022-06-15 03:53:45.081 13225-13264/com.example.myapplication I/Tutorial: Auth session just expired
2022-06-15 03:53:45.082 13225-13287/com.example.myapplication I/Tutorial: Auth session = AWSCognitoAuthSession{isSignedIn=true, awsCredentials=AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, …
> Fix/1485 : Fix for sending the session expired hub event when all credentials are expired

- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/ObserveQueryExecutorTest.java
- aws-geo-location/build.gradle
- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/MapsApiTest.kt
- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/SearchApiTest.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/AWSLocationGeoPlugin.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/Errors.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/auth/CognitoCredentialsProvider.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/models/AmazonLocationPlace.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/AmazonLocationService.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/GeoService.kt
- build.gradle
- maplibre-adapter/build.gradle
- maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewTestActivity.kt
- maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewTestActivityTest.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/http/AWSRequestSignerInterceptor.kt
Replace `aws-android-sdk-location` with `aws.sdk.kotlin:location` as a dependency for `Geo` category and `maplibre-adapter` module.
Note: These changes are just refactoring of existing code to migrate from Java based dependencies to Kotlin. The existing API's and behaviors are left intact.
> Refactor Geo category to use AWS Kotlin SDKs Location.

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTable.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java
- core/src/main/java/com/amplifyframework/core/model/annotations/ModelConfig.java
- testmodels/src/main/java/com/amplifyframework/testmodels/customprimarykey/Comment.java
Suppress creation of index based on @index annotation when the index fields occur in belongs to association as there is an index created on foreign key already.
- [X ] Added Unit Tests
> Suppress belongsto index

- aws-analytics-pinpoint/build.gradle
- aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/AnalyticsPinpointInstrumentedTest.java
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.java
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AnalyticsChannelEventName.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AnalyticsHubEventNames.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AutoEventSubmitter.java
- Send hub events with all the successfully submitted events on flushEvents.
- [PR](https://github.com/aws-amplify/aws-sdk-android/pull/2934) with AWS SDK Changes
- Added instrumentation test to assert hub event is send after calling flush events.
- Testing using sample app.
> feat: Add flushEvents HubEvent for analytics

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
N/A
Let orchestrator fail more gracefully if emitter is disposed
To create the error, I had an online system that was constantly adding new records to 20 different tables. I walk out of wifi range, and then walk back into wifi range. Prior to the fix if the emitter on the orchestrator was already disposed then startSubscription() could leak an async exception event causing the orchestrator to continue accepting records as if the subscriptions were okay.
Combined with #1743 I was able to **finally** have datastore restart sync operations without having to restart the entire application. Please accept these two fixes to make datastore much more resilient …
> fix orchestrator failing if emitter is disposed

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverterTest.java
- core/src/main/java/com/amplifyframework/util/UserAgent.java
https://app.asana.com/0/1202377353696664/1202489222481362/f
When converting TIME and DATE_TIME types for flutter, do not format them, just pass the string through.
- [x ] Added Unit Tests
- [ x] Tested on sample app
- [ x] Successful logs (Attach them to the PR)
- [x ] No
Successful log:
```I/flutter (18643): [ModelWithAppsyncScalarTypes {id=51290c77-94ac-4a29-b451-7f0629e2c640, stringValue=null, altStringValue=null, listOfStringValue=null, intValue=null, altIntValue=null, listOfIntValue=null, …
```
> test(datastore): Flutter update

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
processOutBoxItem should be wrapped to catch exceptions from the method as the blocking await only catches the timeout and returns false. otherwise the exception ends up uncaught
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling
N/A
Catch pending mutation exceptions while draining the outbox.
> catch exceptions from processOutboxItem

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
This was throwing a null pointer which got
silently eaten up by RxJava.
- [x ] PR title and description conform to [Pull 
Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
Expanded a catch clause that was swallowing a null pointer error.  RxJava will silently eat unchecked 
exceptions 😱
Manual testing in debugger confirmed we could see the NPE
- [x ] No
> fix(datastore): Expand a catch to catch a null pointer error

- aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/CognitoUserPoolsAuthProvider.java
- aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/DefaultCognitoUserPoolsAuthProvider.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/AuthenticationCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/JWTParser.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/AmplifyCredential.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/data/AWSCognitoAuthCredentialStoreTest.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/Auth.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
- core/src/main/java/com/amplifyframework/auth/AuthCategory.java
- core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
- core/src/main/java/com/amplifyframework/auth/AuthException.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxAuthBindingTest.java
This change will make Auth.getCurrentUser an asynchronous call using our state machines that way it should be.
*Note* the documentation change will happen once this PR is merged in
This change was tested both from a unit test perspective and from the sample app perspective. Sample app change will come once this is released.
- [ x] Added Unit Tests
- [ x] Tested on frontend (Add Screenshots) 
> feat(auth):Make Current user an Asynchronous call (Breaking change)

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/main/java/com/amplifyframework/api/aws/operation/AWSRestOperation.java
*Issue #, if available:* #1818
*Description of changes:* When an exception occurs in the process of making a REST API request that isn't an IOException (e.g., user needs to be signed in to make the request but isn't signed in), the exception will be uncatchable and crashes the app. This PR adds an additional catch block to the interceptor used for REST API requests in order to catch those exceptions and propagate them back to the client, without crashing the app.
> fix(api): catch exceptions when making rest request

- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/MapsApiTest.kt
- Ignore Geo test that randomly fails in build server
> chore(geo): ignore failing test

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/Auth.kt
- core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/auth/KotlinAuthFacadeTest.kt
- core/src/main/java/com/amplifyframework/auth/AuthCategory.java
- core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
- core/src/main/java/com/amplifyframework/auth/result/step/AuthResetPasswordStep.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java
- rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java
- rxbindings/src/test/java/com/amplifyframework/rx/RxAuthBindingTest.java
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
- Add username as a parameter to `confirmResetPasswordAPI`
> chore(auth): add a username param to confirm reset password api.

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- gradle.properties
Flutter fix for back ticks in sql query where predicate.*How did you test these changes?*
> fix(datastore): Fix for flutter backtick

- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/MapsApiTest.kt
- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/SearchApiTest.kt
- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
- remove multiple plugin configures to prevent attaching multiple auth state listeners
- calling plugin configure multiple times, initializes the auth state machine multiple times which results in inconsistent final state.
> fix(test): fix geo and datastore integration tests

- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadAccessLevelTest.java
Some tests which are failing frequently with "invalid auth state" has been ignored.
These tests are being investigated for root cause and will be un-ignored with the fix.
> chore: ignore storage tests failing with invalid auth state

- scripts/generate_df_testrun_report
Test report generator does not support multiple devices run in same suite. The naming convention being used overrides Testcase and report file generated by another test in same suite. 
This change adds suffix to the test case and report to differentiate.
The suffix being generated uses index of job in jobs array.
> chore: add device run suffix to test report generator

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java
Fixing test failure because of list ordering.
> Fix(datastore) pk field list ordering in cascade delete.

- scripts/generate_df_testrun_report
- scripts/run_test_in_devicefarm.sh
Testing all PRs on 3 devices (Pixel or Samsung) with different OS versions now, instead of just 1.
Android 7
Android 10
Android 12
Also raised threshold to check every 20 seconds instead of 5. Will probably bump further in future PR.
> chore: Add more devices to integration testing

- CHANGELOG.md
- README.md
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
- build.gradle
- core-kotlin/CHANGELOG.md
- core-kotlin/gradle.properties
- gradle.properties
- rxbindings/README.md
Manual cherry-picked release.  Please check thoroughly, comparing to [1.37.2](https://github.com/aws-amplify/amplify-android/commit/6a38bf92799c4c63e7739a24fce3fa77dca89359).
> Manual release: Amplify Android 1.37.3

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthExceptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTests.kt
- core/src/main/java/com/amplifyframework/auth/AuthException.java
Allowed for signup, signin, confirmsignup, resendsignupcode to be able to function if authentication state is in signedout state.
> fix(auth): fix auth states when invoking signup related APIs

- build.gradle
- scripts/maven-release-publisher.yml
- Use latest snapshot build for AWS Sdk from main branch.
- Update release publisher to use explicitly use release AWS sdk.
- Tested locally
- NA
> chore: Update gradle to use latest snapshot release for main

- .github/CODEOWNERS
N/A
Reduce codeowner scope of @aws-amplify/amplify-data to only packages related to DataStore and API. I followed a similar strategy to the iOS repo: https://github.com/aws-amplify/amplify-ios/blob/main/.github/CODEOWNERS.
N/A
> chore: reduce codeowner scope of @aws-amplify/amplify-data

- .circleci/config.yml
Enhancement for the getting started workflow in circleCI(https://github.com/aws-amplify/amplify-android/pull/1770). We added cloudwatch monitoring for the workflow, so the devops team could get notified right away if there's any issues with the workflow. The change should not alter any existing behavior. 
Ran in personal circleci project, and ran successfully 
> chore(ci): add cloudwatch monitoring for getting started smoke test

- testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
*Description of changes:* Increases the timeout for auth operations during tests in SynchronousAuth, matching the timeout in dev-preview.
> chore: increase auth test timeout

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/DeviceSRPCognitoSignInActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/FetchAuthSessionCognitoActions.kt
- add user context data for cognito ASF to initiateAuth and respondToAuthChallenge requests
> fix(auth): add user context data for cognito ASF

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCustomActions.kt
- [ x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
*Description of changes:*: When there is an error inside Custom Auth we currently fail silently without telling the sign in state that an error has occurred. This PR fixes that.
Tested Manually
- [x ] No
> Fix(Auth): Fix for error propagation when sign in fails inside Sign In Custom Auth Action

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/FetchAuthSessionCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/MigrateAuthCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCustomActions.kt
- use stored device key for refresh tokens and custom auth
- use namespaced imports for NotAuthorized exception
- update username for hosted UI signed in data
> fix(auth): device key param for refresh tokens and custom auth

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/AuthorizationCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/DeleteUserActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/actions/AuthorizationActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/AuthorizationState.kt
- [ x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
There was a bug when we wanted to delete a user it was not entering the delete user state machine. This is now fixed with this PR.
Manually tested
> Fix(Auth): Fix for when we want to delete the user

- build.gradle
- core-kotlin/build.gradle
Generate multi-module docs with `./gradlew dokkaHtmlMultiModule`
Generated docs currently reside in root build/dokka
Open build/dokka/htmlMultiModule/index.html in browser
Excluded test modules
> chore(all): dokka multi-module support

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/AuthorizationState.kt
Auth Hub events fired on API calls, not SM changes
Fix clear federation
> fix(auth): Auth hub events fired from api calls instead of SM

- build.gradle
Jcenter no longer receives updates. If gradle cache does not contain the dependencies, it may fail to be downloaded from `jcenter`. Replaced with `mavenCentral`.
> chore: replace jcenter with mavenCentral

- amplify-tools/amplify-tools-gradle-plugin/src/main/groovy/com/amplifyframework/tools/gradle/plugin/AmplifyTools.groovy
- use [standard project property][1] `projectDir` for plugin
In java11 gradle may not have userDir set correctly leading to the project.file not resolving correctly.
https://github.com/gradle/gradle/issues/5991
Pain source: https://youtrack.jetbrains.com/issue/IDEA-265203/Gradle-run-configuration-might-not-use-project-dir-as-working-directory-for-a-task#focus=Comments-27-4834821.0-0
- [ X] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
- [ X] No
By submitting this pull request, I confirm that my contribution …
> fix(amplify-tools): use projectDir for project.file relative paths

- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/internal/core/util/DateUtil.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/internal/core/util/SharedPreferencesUtil.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/LocaleSerializer.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/targeting/endpointProfile/EndpointProfileDemographic.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/targeting/endpointProfile/EndpointProfileLocation.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/targeting/endpointProfile/EndpointProfileUser.kt
ran unit/integration tests locally; remaining public classes are the plugin itself, Hub channel/event, and AWSPinpointUserProfile if users want to include additional attributes when calling `IdentifyUser()`
> Analytics API visibility

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/CredentialStoreClient.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/result/AWSCognitoAuthSignOutResult.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/StateMachine.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTests.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/statemachine/StateMachineListenerTests.kt
It is possible for the state machine listener to be invoked on a background thread prior to the token value being returned on the calling thread. Passing the token in resolves this race condition.
> fix(auth): Fix State Machine token race condition

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthService.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthEnvironment.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginFeatureTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthServiceTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTestBase.kt
Rename SDK escape hatch from `AWSCognitoAuthServiceBehavior` to `AWSCognitoAuthService`.
> chore(auth): fix escape hatch name

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthService.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthEnvironment.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/exceptions/service/GlobalSignOutException.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginFeatureTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthServiceTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTestBase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/JsonGenerator.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/SerializationTools.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/authstategenerators/AuthStateJsonGenerator.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/FetchAuthSessionTestCaseGenerator.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/GetCurrentUserTestCaseGenerator.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/SignOutTestCaseGenerator.kt
- aws-auth-cognito/src/test/java/featureTest/utilities/APICaptorFactory.kt
- aws-auth-cognito/src/test/java/featureTest/utilities/AuthOptionsFactory.kt
- aws-auth-cognito/src/test/resources/feature-test/states/SignedIn_UserPoolSessionEstablished.json
- aws-auth-cognito/src/test/resources/feature-test/states/SignedOut_IdentityPoolConfigured.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/fetchAuthSession/Test_that_API_is_called_with_given_payload_and_returns_successful_data.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_globalSignOut_returns_partial_success_with_revoke_token_error.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_global_signOut_error_returns_partial_success_with_global_sign_out_error.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_signOut_returns_partial_success_with_revoke_token_error.json
- build.gradle
- Retry the test if it fails
- Set maximum number of *total* failures
- Set that test result is still fail even when a test passes on retry
- Sign Out test cases 
> chore: Test Additions and Faulty Test Detection

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/DeviceSRPCognitoSignInActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/FetchAuthSessionCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/MigrateAuthCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SRPCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInChallengeCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCustomCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmResetPasswordOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmSignInOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmSignUpOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthResendSignUpCodeOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthResendUserAttributeConfirmationCodeOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthResetPasswordOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignInOptions.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignOutOptions.java
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignUpOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthUpdateUserAttributeOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthUpdateUserAttributesOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/FederateToIdentityPoolOptions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/DeviceSRPSignInEvent.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SRPEvent.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SignInChallengeEvent.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTestBase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/options/APIOptionsContractTest.java
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/options/APIOptionsKotlinContractTest.kt
> fix(auth): add missing client and analytics metadata

- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/TransferOperations.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperation.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadInputStreamOperation.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageDownloadFileRequest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageGetPresignedUrlRequest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageListRequest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageRemoveRequest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageUploadRequest.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferListener.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferObserver.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferStatusUpdater.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/BaseTransferWorker.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/StorageComponentTest.java
- core/src/main/java/com/amplifyframework/core/async/AmplifyOperation.java
- core/src/main/java/com/amplifyframework/storage/operation/StorageDownloadFileOperation.java
- core/src/main/java/com/amplifyframework/storage/operation/StorageUploadOperation.java
- OnProgress, OnSuccess & OnError callbacks for uploads were not invoked when attached using operation returned by GetTransfer API
- TransferState for single part uploads and download was not marked correctly when a paused transfer is cancelled.
- Terminating Download file operation due to network disconnection throws SocketException, marking it as retryable exception since download needs to restart again when network is available.
> fix: callbacks not invoked when attached using getTransfer api

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/data/EncryptedKeyValueRepository.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/data/EncryptedKeyValueRepositoryTest.kt
EncryptedSharedPreferences are backed up with the rest of SharedPreferences files depending on app backup settings. As a library, we can't control backup configurations as it would conflict with app developers config.
As a workaround, we create a UUID installationIdentifier in noBackupDir to add as a suffix to our EncryptedSharedPreferences, ensuring that file we are attempting to read was not created from a backup.
> fix(auth): Prevent attempting to read backed up EncryptedSharedPreferences

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/CredentialStoreCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/data/AWSCognitoLegacyCredentialStore.kt
Fix device metadata migration for device SRP skip MFA from legacy store using stored last auth user. 
> fix(auth): device metadata migration

- CHANGELOG.md
- README.md
- core-kotlin/CHANGELOG.md
- gradle.properties
- rxbindings/README.md
- Release Amplify Library for Android V2
> release: Amplify Android 2.0.0

- configuration/publishing.gradle
- gradle.properties
- scripts/maven-release-publisher.yml
> chore: Remove deprecated maven plugin

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferStatusUpdater.kt
- While canceling a transfer, transferState is first persisted to db before updating the local cache, which results in TransferWorkerObersver not reading the updated state, which causes it not to abort the S3 multi-part upload. Fix is to change the order where the state is first persisted locally before updating the DB.
- [ x] Added Integration Tests
- [ x] No
> fix: Cancel multi-part upload integration test.

- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/CredentialStoreState.kt
We were seeing failures in our integration tests that showed that Credential Store success in an idle state may potentially be called twice. This PR fixes that issue.
> Fix(Auth): Fix for when move to idle state is called twice in the credential store

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/JsonGenerator.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/SignUpTestCaseGenerator.kt
- aws-auth-cognito/src/test/java/featureTest/utilities/CognitoMockFactory.kt
- aws-auth-cognito/src/test/resources/feature-test/testsuites/fetchAuthSession/AuthSession_object_is_successfully_returned_after_refresh.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/fetchAuthSession/AuthSession_object_is_successfully_returned_for_Identity_Pool.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/fetchAuthSession/AuthSession_object_is_successfully_returned_for_UserAndIdentity_Pool.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/fetchAuthSession/AuthSession_object_is_successfully_returned_for_User_Pool.json
- aws-auth-cognito/src/test/resources/feature-test/testsuites/signUp/Sign_up_finishes_if_user_is_confirmed_in_the_first_step.json
Sign up if successful should return DONE instead of Confirm sign up
> Fix(Auth): Sign up if successful should return DONE instead of Confirm sign up

- .gitignore
- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelMetadata.java
- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelWithMetadata.java
- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelWithMetadataAdapter.java
- aws-api-appsync/src/test/java/com/amplifyframework/datastore/appsync/ModelWithMetadataAdapterTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/ConflictResolverIntegrationTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/MutationProcessorRetryTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncConflictUnhandledErrorFactoryTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncConflictUnhandledErrorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMocking.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMockingTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/TestModelWithMetadataInstances.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/ConflictResolverTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/VersionRepositoryTest.java
https://github.com/aws-amplify/amplify-android/issues/1925
https://github.com/aws-amplify/amplify-android/issues/2066
This PR takes option 2 to remove `__typename` from ModelMetadata table, see https://github.com/aws-amplify/amplify-android/issues/2066#issuecomment-1300680387 . It essentially reverts one of the changes in the [CPK PR](https://github.com/aws-amplify/amplify-android/pull/1650) at the [file](https://github.com/aws-amplify/amplify-android/pull/1650/files#diff-5cdf2885642e1d230ebe77616604dc89e3ed4deb7975f34b69159e0affd9dc27)  (FYI @poojamat)
The changes introduced in CPK include an expectation that there exists a `__typename` field on each model table.  But when an existing customer upgrades without clearing their local …
> fix(datastore): remove typename from ModelMetadata (#2122)

- scripts/nightly-buildspec.yml
Adds a buildspec.yml file for nightly builds into source control.
> chore: Add a buildspec file for nightly tests

- CHANGELOG.md
- README.md
- gradle.properties
- rxbindings/README.md
> release: Amplify Android 2.1.0 (manually created)

- .github/pr-title-checker-config.json
- .github/workflows/pr_title_checker.yml
- CONTRIBUTING.md
Adds a check that the PR title conforms to our contribution guidelines.
> chore: Add PR checker workflow

- aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsInstrumentationTest.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/CredentialStoreClient.kt
*Description of changes:* Fix for when loading credentials the success/error is fired twice it returns an already resumed error in the continuation
> fix(auth): Fix for when loading credentials the success/error is fired twice

- testutils/src/main/java/com/amplifyframework/testutils/FileAssert.java
- replace md5 with sha-256 for file data validation
- NA
- NA
> chore: replace md5 with sha-256 for file data validation

- aws-datastore/build.gradle
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/StartStopInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- [x ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
Fix lock contention issue when running DataStore.start() from the callback of DataStore.stop(), as suggested in the Amplify documentation here: DataStore.start() from the callback of DataStore.stop()
- [ x] Manual testing
- [ x] No
> fix(datastore): Fix lock contention issue when running DataStore.start() from the callback of DataStore.stop()

- aws-analytics-pinpoint/build.gradle
- aws-api-appsync/build.gradle
- aws-api/build.gradle
- aws-auth-cognito/build.gradle
- aws-geo-location/build.gradle
- aws-predictions-tensorflow/build.gradle
- aws-predictions/build.gradle
- aws-storage-s3/build.gradle
- build.gradle
- configuration/publishing.gradle
- core-kotlin/build.gradle
- core/build.gradle
- maplibre-adapter/build.gradle
- rxbindings/build.gradle
Version and group are specified for each subproject. These are required for building the dependencies section of the pom file. Adding the group in each build.gradle avoids errors when using the framework as an included build.
- Published artifacts to maven local and ensured the dependencies sections were correct
- Pulled framework into test app as an included build and ensured app built correctly
> chore: Add group and version back to all subprojects

- scripts/fastlane/Fastfile
Removed this block from the fastfile as the kotlin-core library is now versioned together with the rest of Amplify
> chore: Remove the release-kotlin_v block from prepare release script

- .github/workflows/release_pr.yml
- When creating a release PR the branch name will now be e.g. `bump_version_v1` or `bump_version_main.` This allows us to have v1 and v2 release PRs in progress concurrently.
> chore: Modify the bump_version branch name to be specific to the base branch

- build.gradle
#2250
- Bumped MapLibre SDK from 9.5.2 to 9.6.0. This resolves duplicate class errors for apps using `androidx.core:core-ktx:1.7.0` and above.
- Ensured maps work as expected after dependency update
- Ensured app with `androidx.core:core-ktx:1.7.0` and `mapslibre-adapter` dependency built and ran with no duplicate class errors.
> fix(geo): Bump MapLibre SDK to 9.6.0

- aws-analytics-pinpoint/build.gradle
#2249 
Removes test dependencies from the `implementation` configuration, adding them to the proper `testImplementation` or `androidTestImplementation` configurations instead.
Verified that module still built and unit and integration tests still passed.
> fix(analytics): Remove test dependencies from implementation configuration

- .github/workflows/release_pr.yml
- When calling the `create_next_release_pr` we specify the base branch selected when running the github action. This will be used in the lane to set the base branch when opening the PR. See https://github.com/aws-amplify/amplify-ci-support/pull/131
> chore: Supply base_branch when calling `create_next_release_pr` lane

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLOperation.java
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/MultiAuthAppSyncGraphQLOperation.java
- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
- aws-api/src/main/java/com/amplifyframework/api/aws/auth/ApiKeyRequestDecorator.java
- aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java
- aws-api/src/test/resources/non-json-gql-response.json
- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfiguration.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/ConflictResolver.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/RetryHandler.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/DataStoreConfigurationTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/MutationProcessorRetryTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMocking.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/RetryHandlerTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
- Fixes: #1637
- Fixes: #1794
- Fixes: #1865 
- Fixes: #2077 
- Call errorHandler on mutation errors
- ~Log network responses~
- Don't die on non-json responses
- Remove unused constant
- ~Log WebSocket incoming/outgoing messages~
- ~Remove~ Deprecate `isSyncRetryEnabled` from `AWSDataStorePlugin`
-  ~Remove~ Deprecate `doSyncRetry` from `DataStoreConfiguration`
- Log ConflictHandler calls
- Adjust non-retryable errors in `MutationProcessor` and `SyncProcessor`
- Align RetryHandler logic with other platforms
- ~Remove optional retry of errors in sync~ Log a warning when disabling sync retries
- Wrote additional unit tests
- Manual testing with emulator
- Simulation of different network conditions via a …
> feat(datastore): Add recoverability improvements

- core/build.gradle.kts
Fixes problem where Gradle could not sync when amplify-android was included into a composite build.
Built application pulling in amplify-android from source using includeBuild
> chore: Fix using amplify-android in a composite build

- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/DeviceTrackingApiTest.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/AWSLocationGeoPlugin.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/AmazonLocationService.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/tracking/LocationTracker.kt
- aws-geo-location/src/test/java/com/amplifyframework/geo/location/tracking/LocationTrackingServiceTest.kt
Use the `EncryptedSharedPreferences` used for DB encryption passphrase in order to also store device ID
> chore(geo): Device tracking -- use encrypted shared prefs for device ID

- aws-datastore/src/androidTest/assets/schemas/phonecall/phone.json
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterQueryTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java
- testmodels/src/main/java/com/amplifyframework/testmodels/phonecall/Phone.java
- testmodels/src/main/java/com/amplifyframework/testmodels/phonecall/schema.graphql
*Issue #, if available:* #2035
*Description of changes:* When there are multiple tables of the same type in a query, the columns are given an alias to make them unique. In the case of a column like `Phone.ownerOfPhone`, only replace the first occurrence of the table name `Phone` with the aliased table name to avoid an unknown column name error.
Updated an existing integration test to also test for the specific case described in the issue.
> fix(datastore): Fix aliasing of column names

- core/src/main/java/com/amplifyframework/devmenu/DeveloperMenu.java
*Issue #, if available:* #2293
*Description of changes:* Adds null checks for the logging plugin used in the developer menu.
Tested with a sample app.
> fix(core): add null checks for dev menu logs

- aws-push-notifications-pinpoint-utils/src/main/java/com/amplifyframework/pushnotifications/pinpoint/utils/PushNotificationsUtils.kt
- create default notification channel when plugin is configured to prompt permissions dialog
> fix(notifications): create notification channel when plugin is configured

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthService.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SRPCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SRPEvent.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTestBase.kt
> fix(auth): Fix for missing session variable when custom auth is performed

- annotations/src/main/java/com/amplifyframework/annotations/InternalAmplifyApi.kt
- annotations/src/main/java/com/amplifyframework/annotations/RestrictToAmplify.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- build.gradle.kts
*Description of changes:* Add an annotation similar to Android's RestrictTo since RestrictTo does not work for Kotlin classes and APIs.
Tested the annotation in a sample app.
> chore: Add annotation to restrict API usage

- maplibre-adapter/build.gradle.kts
> chore: Force maplibre to use at least Amplify gson version

- settings.gradle.kts
*Description of changes:* Update the MapLibre version to avoid duplicate class exceptions with androidx and android support libraries.
Ran existing maplibre-adapter tests and tested in a sample app.
> fix(maplibre-adapter): update MapLibre version

- .idea/codeStyles/Project.xml
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
*Issue #, if available:* #2263
*Description of changes:* Add a `doOnError` operator to release the semaphore if Orchestrator encounters an error during start or stop. This restores the prior behaviour of `doFinally` that was removed here: https://github.com/aws-amplify/amplify-android/pull/2209/files#diff-eaf24d0ba1fee6a80c5684eccb0f02cdeea76297bf4b41047b2ea9728deb8127L186
*How did you test these changes?* Unit test
> fix(datastore): Release semaphore if an error occurs while starting or stopping the Orchestrator

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/TextractResultTransformers.java
- build.gradle
*Description of changes:* TABLE_TITLE was added as a new block type that can be returned by Amazon Textract when identifying a table in an image. This block type may not have a row or column index so this PR adds a null check for these values when transforming the blocks to an Amplify type.
Tested in a sample app.
> fix(predictions): Fix processing for table title blocks

- aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestRequestFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/utils/RestRequestFactoryTest.java
*Issue #, if available:* #1932
*Description of changes:* When a delete request was executed with no body, Amplify defaulted to executing a get request instead. This PR adds a check for no body when creating the delete request so that a delete request is still created whether there is a body or not.
Updated existing unit tests and tested in a sample app.
> fix(api): Handle delete request with no body

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/ReachabilityMonitor.kt
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/ReachabilityMonitorTest.kt
Reverts aws-amplify/amplify-android#2197
> Revert "fix(datastore): Fix MutationProcessorRetryTest"

- .github/workflows/notify_comments.yml
correct form:
```json
{
"body": "Example text",
"issue": "Example text"
}
```
> fix: revert JSON format changes, notify_comments needs to be in this form

- .github/workflows/release_pr.yml
- The `ref_name` from the [GitHub Context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) has the short name of the branch the workflow is being run from (e.g. `main`). The ref from the event was the fully formed ref (e.g. `refs/heads/main`) which is not what we want. 
> chore: Use the short branch name when creating the release branch

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationQueue.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationQueueTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
*Issue #, if available:* #1869
*Description of changes:* Modifies the PersistentMutationOutbox to load pending mutations one at a time, rather than storing all pending mutations in a queue, to reduce memory usage.
Ran existing tests and tested in a sample app.
> fix(datastore): Load pending mutations one at a time from outbox

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/ReachabilityMonitor.kt
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/ReachabilityMonitorTest.kt
- aws-push-notifications-pinpoint-common/build.gradle.kts
- settings.gradle.kts
*Issue #, if available:* #2430
*Description of changes:* Repeatedly saving many items with DataStore caused a ConnectivityManager.TooManyRequestsException due to registering a network callback each time there was a new subscriber. This PR registers the network callback once.
Tested in a sample app and added a new unit test.
> fix(datastore): register network callback only once in reachability monitor

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationQueue.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationQueueTest.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
*Issue #, if available:* #1869
*Description of changes:* Modifies the PersistentMutationOutbox to load pending mutations one at a time, rather than storing all pending mutations in a queue, to reduce memory usage.
Ran existing tests and tested in a sample app.
> fix(datastore): Load pending mutations one at a time from outbox (v1)

- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactoryTest.java
*Issue #, if available:* 
#2431
Don't throw an exception if an association field is null when creating a mutation.
This is because it is valid for the field to be null if it's not required. Codegen does not mark such fields as required in the generated models. If it _is_ required then attempting to submit the mutation with a null value will result in an error response.
Checked that the schema provided in the original issue could now create a Note class without a customer association.
> fix(api): Allow null associations on non-required fields.

- aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
*Description of changes:* Ignore the AWSDataStorePluginTest class due to tests inconsistently failing on CI. This test class has also been disabled in Amplify Android v2 (more info [here](https://github.com/aws-amplify/amplify-android/pull/2262#issuecomment-1409148931)).
> chore: Ignore AWSDataStorePluginTest

- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverterTest.java
A custom type field may contain a single custom type, or a list custom type, the [original code change](https://github.com/aws-amplify/amplify-android/pull/2350) fails to handle the latter. This PR fixes this issue.
This change is isolated to Flutter use cases only.
* Added unit tests
* Ran integration tests in amplify-flutter 
> fix(datastore): Flutter: fail to serialize list of custom type values

- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/http/AWSV4Signer.kt
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/http/AWSV4SignerTest.kt
Use English Locale instead of default.  Tested that this fixes the websocket error when device language is set to Arabic.  Swift version is [here](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Predictions/AWSPredictionsPlugin/Signing/SigV4Signer.swift#L137-L154).
> fix(predictions): Use English locale for date/time

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/DeviceSRPCognitoSignInActions.kt
*Issue #, if available:* 2504
*Description of changes:* Currently the respondToAuth api for device SRP does not include the secret hash param and this PR adds that.
> fix(auth): Fix for adding missing parameter for resolving device SRP

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthEnvironment.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/FetchAuthSessionCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/exceptions/service/InvalidGrantException.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/HostedUIHttpHelper.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/FetchAuthSessionTestCaseGenerator.kt
- aws-auth-cognito/src/test/resources/feature-test/testsuites/fetchAuthSession/AuthSession_object_is_successfully_returned_after_refresh.json
*Issue #, if available:* #2481
*Description of changes:* When we get an invalid_grant exception back from cognito we do not send the session expired hub event but we should as that means your session is no longer valid. This PR fixes that. Cognito also sends the error_description which was not captured
> fix(auth): Fix for sending session expired when an invalid grant exception is received

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInChallengeCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SignInChallengeEvent.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignInChallengeState.kt
> fix(auth): Fix for when authstate goes to an invalid state on confirmSignIn when it should accept the error state as is

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/ConflictResolver.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/ConflictResolverTest.java
#2261 
If a conflict occurs during a deletion and a retry local strategy is used in the conflict handler then we want to invoke a delete operation. This was previously always doing an update operation, which would result in the deletion being lost.
- Followed these reproduction steps:
- Configure DataStore with a `conflictHandler` that always returns a `retryLocal()` decision.
- Sync a model to the device
- Put the device into airplane mode
- Delete the model on the device
- In DynamoDB, increase the version number of that model
- Turn off airplane mode on the device
When the device tries to publish the pending mutation it will result in a conflict because the version numbers do not match. The conflict …
> fix(datastore): Fix retry local after a deletion

- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedCustomTypeAdapter.java
- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModelAdapter.java
- aws-api-appsync/src/test/java/com/amplifyframework/datastore/appsync/SerializedModelAdapterTest.java
- aws-api-appsync/src/test/resources/serialized-model-with-nested-custom-type-se-deserialization.json
- core/src/main/java/com/amplifyframework/core/model/SerializedCustomType.java
Fixes: https://github.com/aws-amplify/amplify-flutter/issues/3472, https://github.com/aws-amplify/amplify-flutter/issues/3482
The issue of ser/deseralizing custom types was partially fixed by #2350. However, once this was released, customers quickly noticed new issues. The prior fix did not handle arrays of custom types which this PR addresses.
This PR adds verbose logging alongside the fix. The actual code change/fix is here: https://github.com/aws-amplify/amplify-android/pull/2545/files#diff-2add64014d3bad6c0614a14c3bf6f5b84660fdf5393008933484082fb4cd47ddR143
> fix(datastore/flutter): Custom type list serde

- .github/workflows/closed_issue_message.yml
- .github/workflows/codecov_code_coverage.yml
- .github/workflows/gradle.yml
- .github/workflows/maven_release_publisher.yml
- .github/workflows/release_pr.yml
- .github/workflows/release_pr_approval_count.yml
- .github/workflows/stale.yml
*Description of changes: Pin github actions by commit-hash instead of tags
> chore: pin github actions by commit hash

- aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/AWS4Signer.kt
- aws-core/build.gradle.kts
- aws-logging-cloudwatch/src/main/java/com/amplifyframework/logging/cloudwatch/DefaultRemoteLoggingConstraintProvider.kt
- maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/http/AWSRequestSignerInterceptor.kt
- settings.gradle.kts
* Upgrade Kotlin SDK to resolve S3 EOF exception which is fiex in this [PR](https://github.com/awslabs/smithy-kotlin/pull/896)
> fix(storage): Upgrade SDK to fix EOF exception

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/CognitoAuthExceptionConverter.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/exceptions/service/UserLambdaValidationException.kt
*Issue #, if available:* #2523
*Description of changes:* UserLambda exception was not present in the converter and instead we were sending an unknown exception back to the customer. This fixes that.
> fix(auth): Fix for missing exception type for sign in

- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
#1690 
- Ensure that a websocket that is in the process of being closed is not re-used to start new subscriptions. This fixes the following code sample from [our docs](https://docs.amplify.aws/lib/datastore/sync/q/platform/android/#reevaluate-expressions-at-runtime):
```kotlin
Amplify.DataStore.stop(
{
Amplify.DataStore.start(
{ Log.i("MyAmplifyApp", "DataStore started") },
{ Log.e("MyAmplifyApp", "Error starting DataStore", it) }
)
},
{ Log.e("MyAmplifyApp", "Error clearing DataStore", it) }
)
```
**NB**: There is a caveat that this fix works as expected for the above code snippet, but it does **not** necessarily work if there are _multiple_ levels of `stop`/`start` calls nested within each other.
- …
> fix(datastore): Prevent stop from interrupting subsequent start call

- aws-api/build.gradle.kts
- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/main/java/com/amplifyframework/api/aws/MultiAuthSubscriptionOperation.java
- aws-api/src/main/java/com/amplifyframework/api/aws/MutiAuthSubscriptionOperation.java
- aws-api/src/test/java/com/amplifyframework/api/aws/MultiAuthSubscriptionOperationTest.kt
- aws-api/src/test/java/com/amplifyframework/util/MockExecutorService.kt
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessorTest.java
- gradle/libs.versions.toml
*Issue #, if available:* 
#2399
- Api category emits an `ApiAuthException` from `MultiAuthSubscriptionOperation` if authTypes are exhausted when trying to establish a subscription (this is already how the multi-auth sync worked, and appeared to be the intended implementation based on existing code comments).
- Datastore ignores `ApiAuthException` encountered when starting the `SubscriptionProcessor` and the `SyncProcessor`. This effectively skips those models and allows syncing/subscribing to continue for other models.
- Used schema from issue and verified that DataStore starts normally after fix.
By submitting this pull request, I confirm that my contribution is made under the …
> fix(datastore): Ignore ApiAuthExceptions when subscribing or syncing models

- aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModelAdapter.java
- aws-api-appsync/src/test/java/com/amplifyframework/datastore/appsync/SerializedModelAdapterTest.java
- aws-api-appsync/src/test/resources/serde-for-blog-in-serialized-model.json
- aws-api-appsync/src/test/resources/serde-for-meeting-in-serialized-model.json
- aws-api-appsync/src/test/resources/serialized-model-with-nested-custom-type-se-deserialization.json
https://github.com/aws-amplify/amplify-flutter/issues/3575
When a custom type array is not required and `null` is returned from AppSync, deserialization will fail since `getAsJsonArray` will throw for `null` values.
This resolves the issue by checking if a field is `null` before attempting deserialization.
Added test case for `null` custom type array.
> fix(flutter/datastore): Nullable custom type arrays

- build.gradle.kts
Add License validation as part of build step.
> chore: Add License Validation

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/FaceTargetMatchingParameters.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/ChallengeConfig.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/RunFaceLivenessSession.kt
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/http/LivenessEventStreamTest.kt
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/http/LivenessWebSocketTest.kt
Read facematch timeout from server -- add it to the JSON structure that we're deserializing from.
> fix(liveness): Read facematch timeout from server event JSON

- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointManager.kt
- aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginBehaviorTest.kt
- aws-pinpoint-core/src/main/java/com/amplifyframework/pinpoint/core/EventRecorder.kt
- aws-pinpoint-core/src/main/java/com/amplifyframework/pinpoint/core/TargetingClient.kt
- aws-pinpoint-core/src/main/java/com/amplifyframework/pinpoint/core/endpointProfile/EndpointProfile.kt
- aws-pinpoint-core/src/test/java/com/amplifyframework/pinpoint/core/ConstructTargetingClasses.kt
- aws-pinpoint-core/src/test/java/com/amplifyframework/pinpoint/core/TargetingClientTest.kt
- aws-push-notifications-pinpoint/src/main/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsPlugin.kt
Issue #1
During Amplify's configuration, a call is made to the FirebaseMessaging sdk to grab the token. However, this call is asynchronous (FirebaseMessaging.getInstance().token.addOnCompleteListener) and if a Amplify.Notifications.Push.identifyUser() call is made before the token is returned, it will not locate the token and send OptOut = NONE.
Issue #2
Amplify Push Notifications and Amplify Analytics are appearing to conflict with one another. Each library updates the same endpoint/profile. Each time an analytics endpoint is sent (or even configured), it will send an endpoint update without the token and push channel type. This results in OptOut = All getting set. I was able to observe this by creating a sample app with 2 buttons. The …
> fix(push): Prevent Unintended OptOuts

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/MigrateAuthCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SRPCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCustomCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/AuthHelper.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthValidationTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/SignInTestCaseGenerator.kt
- aws-auth-cognito/src/test/resources/feature-test/testsuites/signIn/Test_that_Custom_Auth_signIn_invokes_proper_cognito_request_and_returns_password_challenge_when_alias_is_used.json
*Issue #, if available:* #2609
When a user signs in with their alias instead of a username and the userpool is not configured to sign in with username, cognito assigns a username to that user (generally a generated UUID). However this breaks the current flow in a way that device ID gets generated each time as there is no stored device information for the new generated username for when we have to do respondToAuthChallenge we use the username returned from the service and not the username that was entered by the user. 
This PR will fix that flow for Custom Auth (with/without SRP and SRP).
Important to note: 
This fix does not fix device tracking for when AuthFlow is `USER_PASSWORD_AUTH ` as InitiateAuth in user_password_auth does not have access to deviceTracking. …
> fix(auth): Fix for when alias is used to sign in and deviceKey is stored with the entered username instead of retrieved username

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLLazySubscribeInstrumentationTest.kt
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/StorageCanaryTest.kt
Prevents API Subscribe instrumentation tests from conflicting with each other when running at the same time.
> chore: Prevent Instrumentation Test device conflicts

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/http/LivenessWebSocket.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/LivenessResponseStream.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/UnrecognizedClientException.kt
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/http/LivenessWebSocketTest.kt
changes since #2615:
manual tests:
> fix(liveness): correct websocket retry logic

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInChallengeCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/actions/SignInChallengeActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SignInChallengeEvent.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignInChallengeState.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTestBase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTests.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/actions/SignInChallengeCognitoActionsTest.kt
https://github.com/aws-amplify/amplify-android/issues/2622
> fix(auth): Add userAttributes to confirmSignIn call

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/http/LivenessWebSocket.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/RunFaceLivenessSession.kt
- core/src/main/java/com/amplifyframework/predictions/models/FaceLivenessSession.kt
Liveness can pass error code to websocket on close.  [UI PR](https://github.com/aws-amplify/amplify-ui-android/pull/106).
Local testing with breakpoint in `destroy()` to make sure close code is being sent; sending session ids to liveness team.
> chore(liveness): add close codes to websocket apis

- CHANGELOG.md
- README.md
- gradle.properties
- rxbindings/README.md
manually-created release PR because Ruby GH action isn't working (see #2659)
> release: Amplify Android 2.14.8

- build.gradle.kts
- Recent PR changed the exclude rule to exclude all META-INF files, this is incorrect.
- Ensured `kotlin_module` was included in build artifacts
> chore(all): Do not exclude all meta-inf

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
peek() also uses a blockingAwait which can cause an exception if in progress when DataStore is cleared.
> fix(datastore): Fix DataStore peek exception

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
#2701 
- `name` property is now set in `AuthDevice` when calling `fetchDevices`.
This change is based on #2690, please merge that first.
- Ensured device name was set in AuthDevice
> fix(auth): Populate name in AuthDevice

- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
I believe the change from InMemoryRepository to SQLite repository in Robolectric slowed our tests down a bit here where sync time record window needs bumped. I also improved logging to ensure that if this fails again, we can see if it was a reasonable amount of time, or proof of incorrect sync.
> fix(datastore): Fix test failure introduced with slower test runs from SQLite

- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/StorageStressTest.kt
Use parameter for 10 uploads/downloads instead of 50
ran stress test with correct amplifyconfiguration.json
> fix(storage): upload/download fewer files in storage stress test to avoid S3 throttling exception

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/SubscriptionEndpointTest.java
- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java
When DataStore is started, Create, Update, Delete subscriptions are made for each model. If I have 10 models, this results in 30 subscriptions established. Subscriptions are established over a single websocket connection by sending a websocket event per subscription. We wait until all subscriptions have been established (ws response message for each subscription) before we proceed with syncing/merging items.
An errant `synchronized` is causing subscription events to being be processed 1 at a time, and not in parallel.
If I have 10 models (30 subscriptions) and each ws event takes the server 200ms to acknowledge, establishing subscriptions would take the current build ~ 6 seconds. Allowing ws events in parallel will complete this effort in …
> fix(datastore): Remove unnecessary synchronized causing subscription slowness

- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
Continuation of https://github.com/aws-amplify/amplify-android/pull/2718
The previous PR was inadvertently creating multiple websockets. This is because the websocket lock had a check 
`if (webSocketListener == null || webSocketListener.isDisconnectedState())` which would create a new ws. Because we were rapidly sending, every subscription request was in a disconnected state. 
This PR waits for the ws connection to open, before it adds the subscriptions
Additionally, I also discovered that disconnecting the websocket takes too long due to the same issue we observed in https://github.com/aws-amplify/amplify-android/pull/2718 with the creation of the subscriptions.
(Please add a line here how the changes …
> datastore(fix): Fixes previous PR which was inadvertently creating multiple websockets.

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/http/LivenessWebSocket.kt
We send video and client events over the liveness websocket. Video events and client events are sent from different threads. If a video and client event are sent at identical time, prior signatures may get mixed up, causing an invalid signature event. This approach uses a coroutine channel queue to ensure outbound websocket events are processed 1 at a time.
Manual testing
> fix(Predictions): Fix Liveness InvalidSignatureException

- aws-auth-cognito/build.gradle.kts
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoLegacyCredentialStoreInstrumentationTest.kt
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/CredentialStoreStateMachineInstrumentationTest.kt
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/testutils/AuthConfigurationProvider.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthService.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthConfiguration.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthEnvironment.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/CredentialStoreClient.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/data/AWSCognitoAuthCredentialStore.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/data/AWSCognitoLegacyCredentialStore.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/AuthConfiguration.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/IdentityPoolConfiguration.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/OauthConfiguration.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/UserPoolConfiguration.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/AuthEvent.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/AuthenticationEvent.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginFeatureTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthServiceTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthValidationTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTestBase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/actions/SetupTOTPCognitoActionsTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/actions/SignInChallengeCognitoActionsTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/data/AWSCognitoAuthCredentialStoreTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/data/AWSCognitoLegacyCredentialStoreTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/statemachine/codegen/data/AuthConfigurationTest.kt
Amplify previously exposed raw JSON via `getPluginConfiguration` for Authenticator to consume. This change instead exposed a pre-parsed `AuthConfiguration`.
- Added `signupAttributes`, `usernameAttributes`, `verificationMechanisms`, and `passwordProtectionSettings` to `AuthConfiguration`
- Exposed `AuthConfiguration` and related types with `@InternalAmplifyApi` annotations.
- Deprecated existing `getPluginConfiguration` function.
- Moved `AuthConfiguration` to `com.amplifyframework.auth.cognito` package. This is a more appropriate location for this class.
Equivalent Swift PR is here: https://github.com/aws-amplify/amplify-swift/pull/3566
- Tested consuming new internal API in Authenticator 
*Documentation …
> feat(auth): Expose AuthConfiguration directly

- annotations/src/main/java/com/amplifyframework/annotations/AmplifyFlutterApi.kt
- core/src/androidTest/java/com/amplifyframework/core/util/UserAgentConfigurationTest.java
- core/src/main/java/com/amplifyframework/core/Amplify.java
- core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java
- Add a new API for Flutter to set its user agent string. This is to move away from AmplifyConfiguration for Gen2.
- Add new annotation to mark APIs that are consumed by Flutter.
> feat(all): Add a new API for Flutter to set user agent

- aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java
- aws-predictions-tensorflow/src/main/java/com/amplifyframework/predictions/tensorflow/TensorFlowPredictionsPlugin.java
- aws-predictions/build.gradle.kts
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/AWSPredictionsPlugin.java
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/AWSPredictionsPluginTest.kt
- aws-push-notifications-pinpoint/build.gradle.kts
- aws-push-notifications-pinpoint/src/main/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsConfiguration.kt
- aws-push-notifications-pinpoint/src/main/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsPlugin.kt
- aws-push-notifications-pinpoint/src/test/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsConfigurationTest.kt
- aws-storage-s3/build.gradle.kts
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/AWSS3StoragePluginTest.kt
- build.gradle.kts
- core/src/main/java/com/amplifyframework/logging/LoggingCategory.java
- testutils/src/main/java/com/amplifyframework/testutils/configuration/AmplifyOutputsDataBuilder.kt
Adds configuration code for the following plugins using AmplifyOutputs
- Logging category (no-op, logging configuration is not included in Gen2)
- Storage
- DataStore (no-op, no datastore configuration in Gen2)
- PushNotifications
- Predictions (throws exception, Predictions not supported in Gen2)
The remaining plugins (API, Auth, and Geo) will be separate PRs as they are each more complex than these simple cases.
> feat(all): Configure plugins with AmplifyOutputs

- .gitignore
- aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsCanaryTestGen2.kt
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AuthCanaryTestGen2.kt
- aws-datastore/src/androidTest/java/com/amplifyframework/datastore/DatastoreCanaryTestGen2.kt
- aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/GeoCanaryTestGen2.kt
- aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/StorageCanaryTestGen2.kt
- configuration/instrumentation-tests.gradle
- scripts/pull_backend_config_from_s3
Add a Gen2 version of each Canary Test class. This is a straight copy/paste of the existing Canary Test (with one exception, see below) except the configuration has been replaced with using `amplify_outputs`.
One exception: The Auth canary test used a REST API to use backend functions for confirming and deleting users. This isn't supported in the v1 Gen2 schema, so this Gen2 canary test uses an API plugin directly with a Gen1 config to replicate this behaviour. This can be updated once amplify_outputs schema adds support for REST API.
The Analytics canary test is currently disabled because the auth backend is configured to require a client secret, which is not supported in Gen2 config.
The test classes are duplicated due to their need to …
> chore(all): Create Gen2 canary tests

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthConfiguration.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthConfigurationTest.kt
- core/src/main/java/com/amplifyframework/core/configuration/AmplifyOutputsData.kt
- core/src/test/java/com/amplifyframework/core/configuration/AmplifyOutputsDataTest.kt
- testutils/src/main/java/com/amplifyframework/testutils/configuration/AmplifyOutputsDataBuilder.kt
`authentication_flow_type` is being removed from the Gen2 config. The default will be `USER_SRP_AUTH` unless the customer overrides it.
> fix(auth): Remove authenticationFlowType from Gen2 config

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthConfiguration.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthConfigurationTest.kt
- core/src/main/java/com/amplifyframework/core/configuration/AmplifyOutputsData.kt
- testutils/src/main/java/com/amplifyframework/testutils/configuration/AmplifyOutputsDataBuilder.kt
Backend is reverting back to using a single domain field for oauth configuration.
> chore(auth): Revert cognito/custom domain back to one field

- core/src/main/java/com/amplifyframework/auth/result/AuthSignUpResult.java
https://github.com/aws-amplify/amplify-android/issues/2775
userId is not returned in `AuthSignUpResult` for `confirmSignUp` as it is not returned to us from the API. Cognito will only return userId on `signUp` calls. 
We can't be more specific on this class, because `AuthSignUpResult` is in core, and a non-Cognito auth library may have different behavior as to when userId is and isn't returned.
> fix(auth): Fix incorrect statement about when userId is returned in AuthSignUpResult

- aws-storage-s3/build.gradle.kts
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferDB.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferDBHelper.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferManager.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferStatusUpdater.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/transfer/TransferDBTest.kt
#2720 
TransferDB is supposed to be a singleton but it was implemented incorrectly. Having multiple instance of this class causes multiple database connections, which can lead to the exception described in the issue.
Also made some minor cleanup in related classes.
Unit test to verify the fix.
> fix(storage): Fix multiple instances of TransferDB leading to SQLiteDatabaseLockedException

- aws-analytics-pinpoint/api/aws-analytics-pinpoint.api
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.kt
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginConfiguration.java
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointManager.kt
- aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginConfigurationTest.kt
- aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/OptionsTest.kt
- aws-pinpoint-core/src/main/java/com/amplifyframework/pinpoint/core/AnalyticsClient.kt
- aws-pinpoint-core/src/test/java/com/amplifyframework/pinpoint/core/AnalyticsClientTest.kt
- aws-push-notifications-pinpoint/src/main/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsPlugin.kt
- Adds `trackLifecycleEvents` to analytics plugin options
- Re-adds code that had been removed to read `trackLifecycleEvents` from Gen1 config
- Fixes implementation to respect the value of `trackLifecycleEvents`
> fix(analytics): Re-add option to track lifecyle events

- aws-api/api/aws-api.api
- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java
- aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPluginConfigurationReader.java
- aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginConfigurationReaderTest.kt
Gen2 doesn't have a concept of API names when using defineData, so we hardcode a default name to use instead.
We realized that you need to supply an API name to configure okhttp clients, so customers will need to supply this hardcoded default. Exposing this constant will avoid having customers need to copy/paste a string from documentation.
```kotlin
val plugin = AWSApiPlugin.builder()
.configureClient(GEN2_DATA_API_NAME) { clientBuilder ->
// ...
}
.build()
```
Also aligned the value of the constant with Swift to be `gen2DataApiName`.
By submitting this pull request, I confirm that my contribution is …
> fix(analytics): Expose a constant for the API name used for Gen2 defineData

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/data/AWSCognitoLegacyCredentialStore.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/SessionHelper.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/data/AWSCognitoLegacyCredentialStoreTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/helpers/SessionHelperTests.kt
*Issue #, if available:* https://github.com/aws-amplify/amplify-android/issues/2789
*Description of changes:* 
V1 was storing session expiration timestamp as epoch milliseconds and V2 was reading/storing it as epoch seconds. The migration code did not account for this and users that migrated would store a session expiration that would be many many years in the future.
This change adds some logic to the migration code to detect this and covert from milli to sec for new users that still need to migrate.
This change also adds a check in the isValidSession function for users who have already migrated and needs a way to fix themselves.
By submitting this pull request, I confirm that my contribution is made …
> fix(auth): Fix timestamp issue with v1 to v2 migration

- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java
Improve logging of errors returned from AppSync. We previously erroneously reported a response with errors as an "empty response" which limits ability to diagnose the error. We will now include the actual error in the log message.
Before:
```
IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
```
After:
```
IrRecoverableException{message=Received errors from AppSync: GraphQLResponse.Error{message='Not Authorized to access syncGuests on type Query', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncGuests'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}, cause=null, recoverySuggestion=Report to AWS team.}
```
*How did …
> fix(datastore): List errors that are returned from AppSync

- aws-analytics-pinpoint/api/aws-analytics-pinpoint.api
- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.kt
*Issue #, if available:* #2802
Analytics Options Builder should have had a public build method. While it's not needed for Kotlin it is needed for Java.
> fix(analytics): Make Analytics Options Builder build function public for Java to call

- build.gradle.kts
- configuration/publishing.gradle
Migrated publishing to use the [publishing DSL](https://developer.android.com/build/publish-library/configure-pub-variants#single-pub-var). This is a pre-requisite to upgrading to Gradle 8+.
The publishing DSL adds `scope` information and publishes Gradle metadata by default. Although those are beneficial, they could potentially impact customers and should not be added in a minor version, so I've disabled/removed both of those. They can be enabled in a future major version release.
> chore: Move to using the Maven Publish DSL

- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/actions/SetupTOTPCognitoActionsTest.kt
- aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
- core/api/core.api
- core/src/main/java/com/amplifyframework/logging/Logger.java
- core/src/test/java/com/amplifyframework/logging/AndroidLoggingPluginTest.java
- core/src/test/java/com/amplifyframework/logging/FakeLogger.java
- core/src/test/java/com/amplifyframework/logging/LoggerTest.kt
*Issue #, if available:* 
#2730
While evaluated `observeQuery` performance we noted that we were spending quite a lot of time constructing strings for verbose log messages. This PR adds an API to lazily perform potentially expensive log message construction, which can make a significant impact for some log statements.
> feat(core): Add APIs to lazily evaluate log statements

- core-kotlin/build.gradle.kts
- core-kotlin/src/main/java/com/amplifyframework/kotlin/api/KotlinApiFacade.kt
- core-kotlin/src/test/java/com/amplifyframework/kotlin/api/KotlinApiFacadeTest.kt
While testing subscription auth modes I found that exceptions during subscription would get replaced with a NPE when using the Kotlin Facade. Resolved the error so that the underlying exception gets propagated to the caller.
- Unit test
- Verified issue could not be reproduced after change
> fix(api): Fix the handling of exceptions when subscribing with Kotlin Facade

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
https://github.com/aws-amplify/amplify-android/issues/2816
If a subsequent auth call is called from within an auth onSuccess/onError callback with `runBlocking`, it can cause a deadlock because. While this is a rare scenario, we can avoid with the changes in PR.
```
Amplify.Auth.fetchAuthSession( 
{
runBlocking {
AmplifyKt.Auth.fetchAuthSession() 
} 
},
{}
)
```
> fix(auth): Prevent Rare Deadlock Scenario

- aws-api/api/aws-api.api
- aws-api/src/main/java/com/amplifyframework/api/graphql/model/ModelSubscription.kt
In conversion of ModelSubscription file from Java to Kotlin, JvmStatic annotations were missed, which make calling from Java more difficult. Adding JvmStatic back to re-introduce calling without requiring `ModelSubscription.INSTANCE`
> fix(api): Add missing JvmStatic annotations

- scripts/Gemfile.lock
Updates the REXML gem to address dependabot vulnerability
> chore: Update rexml gem

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignOutState.kt
https://github.com/aws-amplify/amplify-android/issues/2598
Prevents `signOut` lockup if a user cancels hosted ui sign out from the browser. The common scenario for this is no internet.
> fix(auth): Fix HostedUI signout cancellation issue

- aws-api/api/aws-api.api
- aws-api/src/main/java/com/amplifyframework/api/aws/ApiLazyModelReference.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.kt
- aws-api/src/main/java/com/amplifyframework/api/graphql/model/ModelQuery.kt
- aws-api/src/test/java/com/amplifyframework/graphql/model/ModelQueryTest.kt
Updated ModelQuery class to accept authMode parameter
> feat(api): Add authMode to ModelQuery

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthConfiguration.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthConfigurationTest.kt
#2835 
https://github.com/aws-amplify/amplify-ui-android/issues/154
The correct values for the Gen1 configuration password settings are `REQUIRES_UPPERCASE`/`REQUIRES_LOWERCASE`.
- Verified that all settings were respected with a config generated from the CLI.
> fix(auth): Fix parsing of REQUIRES_UPPERCASE/REQUIRES_LOWERCASE password settings in Gen1

- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSync.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
- aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/VersionRepository.kt
- aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/VersionRepositoryTest.kt
https://github.com/aws-amplify/amplify-android/issues/2151#issuecomment-2135346064
**The app should not crash when DataStore cannot retrieve the version for update and delete mutations. DataStore should attempt to send the mutation without a version and handle the response.**
This PR is looking to address the following crash that customers are experiencing
```
DataStoreException{message=Wanted 1 metadata for item with id = e7eb4237-c0d4-4ce6-8800-3b9d5fb603b8, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:91)
at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$findModelVersion$0$co …
```
> fix(DataStore): should not crash on missing version metadata

- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/exceptions/FaceLivenessUnsupportedChallengeTypeException.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/http/LivenessWebSocket.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/ChallengeEvent.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/FaceMovementClientChallenge.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/FaceMovementServerChallenge.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/LivenessResponseStream.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/liveness/ServerChallenge.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/RunFaceLivenessSession.kt
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/http/LivenessWebSocketTest.kt
- aws-predictions/src/test/java/com/amplifyframework/predictions/aws/service/RunFaceLivenessSessionTest.kt
- core/src/main/java/com/amplifyframework/predictions/models/FaceLivenessChallengeType.kt
- core/src/main/java/com/amplifyframework/predictions/models/FaceLivenessSession.kt
- core/src/main/java/com/amplifyframework/predictions/models/FaceLivenessSessionInformation.kt
This adds support for a no-light challenge to the Prediction plugin's Face LIveness feature and adds telemetry tracking as requested by the Rekognition team. There's no API change to the core plugin API and **additive** changes to the `FaceLivenessSessionInformation` data class that's used as part of the API.
Notable callouts:
- `FaceLivenessSessionInformation`
- Changed the `String` `challenge` parameter to be nullable. This is required to allow backward compatibility with the existing Liveness UI component library.
- Added a new parameter `challengeVersions` to replace the previous `challenge` which takes in a `List<Challenge>`. These `Challenge`s represent both the challenge name and the version for that challenge. 
- Added a new …
> feat(predictions): Add support for a no light freshness challenge

- aws-api/src/main/java/com/amplifyframework/api/aws/AWSGraphQLOperation.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/ApiLazyModelReference.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/ApiModelListTypes.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java
- aws-api/src/main/java/com/amplifyframework/api/aws/LazyLoadingContext.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/LazyTypeDeserializers.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/ModelPostProcessingTypeAdapter.kt
- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
- aws-api/src/test/java/com/amplifyframework/api/aws/ApiLazyModelListTest.kt
- aws-api/src/test/java/com/amplifyframework/api/aws/ApiLazyModelReferenceTest.kt
- aws-api/src/test/java/com/amplifyframework/api/aws/MultiAuthSubscriptionOperationTest.kt
When loading a lazy model/list with an authMode we pass that through and use it to also load the referenced models.
> feat(api): Add authMode support to lazy loaded models

- CHANGELOG.md
- README.md
- gradle.properties
- rxbindings/README.md
Amplify Android 2.20.0
This is a manual PR because one of the commit messages fails the conventional commits syntax. 
The changelog should call out all of the commits from the last release (2.19.1) to today as listed out here: https://github.com/aws-amplify/amplify-android/commits/main/?since=2024-06-19&until=2024-07-11
Since there's a new feature commit in the changelog, doing a version bump to 2.20.0
> release: Amplify Android 2.20.0

- aws-storage-s3/src/main/AndroidManifest.xml
Noted that storage plugin was requesting foreground service permission. This is a leftover from Amplify V1 and is unused - there is no Service (or foreground Service) used in Storage V2, we use Work Manager instead.
Listing permissions you don't actually use is bad form, so I've removed it.
> fix(storage): Remove unused foreground service permission

- aws-push-notifications-pinpoint-common/src/main/java/com/amplifyframework/pushnotifications/pinpoint/PushNotificationsUtils.kt
None
Fix to catch exception when icon image download fails from notification payload.
If an exception is thrown, the image data is treated as null.
This has not been checked as there is no back-end available.
The following commands were executed, but originally failed.
`./gradlew clean build`
> fix(notifications): Catch Exception when download icon image of pinpoint notification

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
Related issue in Amplify UI Android for Authenticator: https://github.com/aws-amplify/amplify-ui-android/issues/145
* Update getCurrentUser to check and return `SessionExpiredException` to handle cases where users are signed in but the session has expired.
* manually tested with test app with Authenticator
* verified unit test passed
> chore(auth): update getCurrentUser to check for SessionExpiredException

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/options/AWSS3StorageGetPresignedUrlOptions.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/AWSS3StoragePluginTest.kt
- core/api/core.api
- core/src/main/java/com/amplifyframework/core/configuration/AmplifyOutputsData.kt
- core/src/main/java/com/amplifyframework/storage/BucketInfo.kt
- core/src/main/java/com/amplifyframework/storage/InvalidStorageBucketException.kt
- core/src/main/java/com/amplifyframework/storage/StorageBucket.kt
- core/src/main/java/com/amplifyframework/storage/options/StorageGetUrlOptions.java
- core/src/main/java/com/amplifyframework/storage/options/StorageOptions.java
- core/src/test/java/com/amplifyframework/core/configuration/AmplifyOutputsDataTest.kt
- testutils/src/main/java/com/amplifyframework/testutils/configuration/AmplifyOutputsDataBuilder.kt
**Multi-bucket support part 1**
This the first part of a series of changes/pull request to support multi-bucket in the S3 Storage Plugin.  The series of changes will be reviewed and merged into a feature branch and combined into a single pull request to be reviewed and merged into `main` branch.
Changes in this pull request includes:
* Update `AmplifyOutputsData` to support multi-bucket configuration
* Add new data structures and update `StorageOption` to specify S3 bucket
* Update `AWSS3StoragePlugin` to support interfacing with unique bucket/region by creating and maintaining multiple `AWSS3StorageService` instances.  Creating multiple `AWSS3StorageService` at the plugin level is the least invasive change to support multiple …
> feat(storage): update AWSS3StoragePlugin to support multiple buckets

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/AWSS3StoragePluginTest.kt
Fix issue with the Storage list api always defaulting to the default storage service instead of using the storage service based on whether a different bucket is passed in as part of the options parameter.
Failed integration tests now passes.
> chore: fix storage list with multiple buckets

- apollo/apollo-appsync/build.gradle.kts
- build.gradle.kts
- configuration/publishing.gradle
The signing key was only being set for Android projects, resulting in no signature generating for `apollo-appsync`. You need signature files to publish the artifacts to maven central. Therefore I moved the setting of the required extras outside the check for the Android plugin.
> chore(apollo): Fix publishing errors with apollo-appsync

- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- testutils/src/main/java/com/amplifyframework/testutils/CountdownLatchExtensions.kt
I noticed that unit tests in RealAuthCognitoPluginTest were frequently failing on CI. Inspecting the failing tests show that they were not necessarily waiting for the callbacks to be invoked before proceeding with verification.  Adding additional latches should resolve the issue.
Longer term this area of the codebase should be refactored into usecases.
> chore(auth): Add waits to asynchronous tests

- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginInstrumentationTests.kt
- testutils/src/main/java/com/amplifyframework/testutils/HubAccumulator.java
- testutils/src/main/java/com/amplifyframework/testutils/HubAccumulatorExtensions.kt
`AWSCognitoAuthPluginInstrumentationTests` fail very frequently on CI.  I've made two changes to try to make this test class more robust:
- Sign out before the test starts and sleep for 1 second before proceeding - this is to ensure we are actually in the correct state before starting the test
- Unsubscribe from the Hub when the test finishes. This prevents the hub from accumulating listeners.
> chore(auth): Signout before tests start

- apollo/README.md
Adds some additional details around authorization modes to the apollo/README file.
n/a
> chore(apollo): Add details about authorization modes to Apollo AppSync README

- apollo/apollo-appsync/src/main/java/com/amplifyframework/apollo/appsync/ApolloExtensions.kt
- apollo/apollo-appsync/src/main/java/com/amplifyframework/apollo/appsync/AppSyncEndpoint.kt
- apollo/apollo-appsync/src/main/java/com/amplifyframework/apollo/appsync/util/WebSocketConnectionInterceptor.kt
- apollo/apollo-appsync/src/test/java/com/amplifyframework/apollo/appsync/ApolloExtensionsTest.kt
- apollo/apollo-appsync/src/test/java/com/amplifyframework/apollo/appsync/util/WebSocketConnectionInterceptorTest.kt
AppSync recently added the ability to use HTTP headers instead of query parameters to authorize the websocket connection request. This is now the recommended way to connect (and new AppSync instances will eventually stop accepting query parameters).
This change switches the `apollo-appsync` library to use this new method of authorization.
- Added unit tests
- Manual test passes
- Integration tests still pass
> feat(apollo): Use HTTP headers instead of query parameters for authorization

- aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
- aws-api/src/main/java/com/amplifyframework/api/aws/utils/JSONObjectExtensions.kt
AppSync now supports passing the authorization headers as HTTP headers instead of query string parameters when establishing a websocket connection.
This PR migrates the API category to the new, recommended method for passing authorization headers.
- Manual test
- Integration tests
> feat(api): Pass authorization in header instead of query parameter for API category

- core-kotlin/src/main/java/com/amplifyframework/kotlin/core/Amplify.kt
- rxbindings/src/main/java/com/amplifyframework/rx/RxAmplify.java
*Issue #, if available:* 
#2943
The `RxAmplify` and the Kotlin Facade version of `Amplify` both instantiate their own versions of the Analytics (and Logging) category. Neither do that for other categories.
This is a problem because they delegate to the main Amplify for all other actions, including adding plugins. Therefore, the Analytics plugin gets added to the "main" instance of the Category (e.g. the one owned by `com.amplifyframework.core.Amplify`) while subsequent API calls get routed to the "new" instance of the category (owned by `com.amplifyframework.rx.RxAmplify` or `com.amplifyframework.kotlin.core.Amplify`). Such API calls always result in a `IllegalStateException` because there is no plugin added to that instance of the category.
The fix is simple, …
> fix(analytics): Fix accessing the Analytics category from RxAmplify or Kotlin Facade

- apollo/apollo-appsync/src/main/java/com/amplifyframework/apollo/appsync/AppSyncEndpoint.kt
- apollo/apollo-appsync/src/test/java/com/amplifyframework/apollo/appsync/AppSyncEndpointTest.kt
*Issue #, if available:* #2945
In China the AppSync URL has `.cn` as a TLD, and we weren't account for that in our standard URL regex. I updated the regex to [match Amplify JS](https://github.com/aws-amplify/amplify-js/blob/7402f607443786750c9b2da63461739f974b594b/packages/api-graphql/src/Providers/AWSWebSocketProvider/appsyncUrl.ts#L13-L16)
Unit test
> fix(apollo): Fix using Apollo to connect to AppSync in China

- aws-api/src/main/java/com/amplifyframework/api/aws/DomainType.java
- aws-api/src/test/java/com/amplifyframework/api/aws/DomainTypeTest.java
*Issue #, if available:* #2945
In China the AppSync URL has .cn as a TLD, and we weren't account for that in our standard URL regex. I updated the regex to [match Amplify JS](https://github.com/aws-amplify/amplify-js/blob/7402f607443786750c9b2da63461739f974b594b/packages/api-graphql/src/Providers/AWSWebSocketProvider/appsyncUrl.ts#L13-L16)
Unit test
> fix(api): Fix connecting to AppSync from China with API category

- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoLegacyCredentialStoreInstrumentationTest.kt
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/CredentialStoreStateMachineInstrumentationTest.kt
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/testutils/CredentialStoreUtil.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/CredentialStoreCognitoActions.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/data/AWSCognitoLegacyCredentialStore.kt
Amplify v1 (or standalone AWS Android SDK) migrations to Amplify v2 do not migrate all required data in some cases. This results in token refresh failures.
Requirements for Issue:
1. Device Tracking Enabled
2. Sign in is completed with an alias that does not match the real Cognito assigned userId (ex: sign in with email)
3. Amplify v1 Sign In completed with sign in method that supports device tracking (ex: SRP, not HostedUI)
Cause of Bug
Amplify v2 pulls "LastAuthUserId" from the legacy (v1) credential store. This value is the alias (ex: email address), not necessarily the actual userId. This results in a failed lookup for device metadata. Device metadata will not be migrated to the new credential store format, and the existing file remains untouched on the device.
Additional Bug …
> fix(auth): Fix Device Metadata migration if alised userId was used

- .gitignore
- apollo/apollo-appsync-amplify/build.gradle.kts
- aws-analytics-pinpoint/build.gradle.kts
- aws-api-appsync/build.gradle.kts
- aws-api/build.gradle.kts
- aws-auth-cognito/build.gradle.kts
- aws-auth-plugins-core/build.gradle.kts
- aws-datastore/build.gradle.kts
- aws-geo-location/build.gradle.kts
- aws-logging-cloudwatch/build.gradle.kts
- aws-pinpoint-core/build.gradle.kts
- aws-predictions/build.gradle.kts
- aws-push-notifications-pinpoint-common/build.gradle.kts
- aws-storage-s3/build.gradle.kts
- build.gradle.kts
- core-kotlin/build.gradle.kts
- core/build.gradle.kts
- maplibre-adapter/build.gradle.kts
- rxbindings/build.gradle.kts
Android Studio Ladybug ships with an embedded JVM of 21.0.3. Since we were not being explicit in which JVM to use for compilation, this caused builds to fail because our Java code was being compiled with Java 21, while our Kotlin verison only supports up to Java 20.
I resolved this by explicitly setting the `jvmToolchain` to 17 for all gradle builds, regardless of whether it's from command line, on CI, or in the IDE.
I also had to disable the `-Werror` compiler option. It appears that this option was previously being disregarded, which has allowed many warnings to accumulate. Once these warnings are addressed then we can re-enable `-Werror` to prevent additional warnings from being introduced.
- Verified …
> chore: Fix building in Android Studio Ladybug

- aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointManager.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthService.kt
- aws-auth-plugins-core/src/main/java/com/amplifyframework/auth/plugins/core/CognitoClientFactory.kt
- aws-core/build.gradle.kts
- aws-core/src/main/java/com/amplifyframework/util/AmplifyHttp.kt
- aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/AmazonLocationService.kt
- aws-logging-cloudwatch/src/main/java/com/amplifyframework/logging/cloudwatch/AWSCloudWatchLoggingPlugin.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSComprehendService.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSPollyService.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSRekognitionService.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSTextractService.kt
- aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSTranslateService.kt
- aws-push-notifications-pinpoint/src/main/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsPlugin.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/S3StorageTransferClientProvider.kt
- configuration/consumer-rules.pro
- documents/OkHttp4.md
- gradle/libs.versions.toml
#2809 
All AWS clients will now use the `Http4Engine` if it is available on the classpath.
- Create test app using OkHttp4 and verify the correct engine is used in Amplify
> feat(all): Add ability to use OkHttp4 with Amplify v2.x

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/AbortMultiPartUploadWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/BaseTransferWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/BlockingTransferWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/CompleteMultiPartUploadWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/DownloadWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/InitiateMultiPartUploadTransferWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/PartUploadTransferWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/RouterWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/SinglePartUploadWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/SuspendingTransferWorker.kt
- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/TransferWorkerFactory.kt
*Problem:* We found that with multi-part uploads that took a long time (e.g. a large file being uploaded or a slow network connection) would eventually cause `SocketTimeoutException`s. After a long investigation, we found that the issue is with creating a lot of `CoroutineWorkers` and queuing them up at the same time. Since all of the pending part uploads were being queued at the same time, `WorkManager` would actually queue them ALL of them at the same time because the S3 uploadPart call is a suspending function. So a part upload may "start" at T:0, get suspended because 20 other parts are trying to upload at the same time, and then not actually continue until 5 minutes later. And since the socket connection was already open, it would timeout because nothing …
> fix(storage): Fix SocketTimeoutException when executing a long multi-part upload

- build.gradle.kts
- gradle/libs.versions.toml
Resolved a few warnings in our Gradle builds
- Using deprecated `project.buildDir` (should be `project.layout.buildDirectory`)
- Using unsupported build tools (build tools version is now set automatically by AGP)
- Specifying useless `targetSdk` in a library project (only app projects should set targetSdk)
- Using deprecated `packagingOptions` (renamed to `packaging`)
- Unable to resolve `androidx.annotation:annotation:1.1.0` - I'm not sure why this happens since that artifact [does exist](https://mvnrepository.com/artifact/androidx.annotation/annotation/1.1.0), but upgrading to 1.9.1 appears to resolve 🤷‍♂️
This PR does not resolve compilation warnings, only warnings from the Gradle build itself.
- Ran …
> chore: Resolve warnings in Gradle scripts

- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginEmailMFATests.kt
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginUserAuthTests.kt
*Description of changes:* I found that in the last month's integ test runs, an overwhelming number of failures were in AWSCognitoAuthPluginUserAuthTests with the reasoning being CodeMismatchExceptions. Looking at it, I found that there's an edge case if tests are being run in parallel, the AppSync subscription returns the next code and the test assumes it's the one it cares about and tries to confirm with that code. 
The change now checks if the code belongs to the test user that belongs to the test case.
Locally while running the test suite, had an AppSync explorer open and spamming the CreateMfaInfo mutation before and after the change. Before, a few tests would fail due to the same exception. After, it would ignore the …
> chore: Fix an integration test edge case while testing MFA/OTP codes

- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoLegacyCredentialStoreInstrumentationTest.kt
*Description of changes:* From the [Android documentation for File.listFiles()](https://developer.android.com/reference/java/io/File#listFiles()):
```
There is no guarantee that the name strings in the resulting array will appear in any specific order; 
they are not, in particular, guaranteed to appear in alphabetical order.
```
This is important because the test is doing a list comparison where order matters and the test failure shows that:
`java.lang.AssertionError: expected:<[2924030b-54c0-48bc-8bff-948418fba949, 7e001127-5f11-41fb-9d10-ab9d6cf41dba]> but was:<[7e001127-5f11-41fb-9d10-ab9d6cf41dba, 2924030b-54c0-48bc-8bff-948418fba949]>`
Validated no regression
By …
> chore: Fix transient legacy credential store integ test failure

- apollo/README.md
- apollo/apollo-appsync-amplify/api/apollo-appsync-amplify.api
- apollo/apollo-appsync-amplify/src/main/java/com/amplifyframework/apollo/appsync/ApolloAmplifyConnector.kt
- apollo/apollo-appsync-amplify/src/test/java/com/amplifyframework/apollo/appsync/ApolloAmplifyConnectorTest.kt
ApolloAmplifyConnector was created to read AppSync connection information from `amplify_outputs.json`, but some customers who do use Amplify but do not have a Gen2 configuration file (e.g. existing Gen1 customers) may also want to use this class. They already could use the companion functions, but this new constructor makes it possible for them to use the convenience authorizer factories instead.
So now a Gen1 customer can do the following:
```kotlin
val connector = ApolloAmplifyConnector(
endpointUrl = "https://example1234567890123456789.appsync-api.us-east-1.amazonaws.com/graphql",
region = "us-east-1",
apiKey = "[YOUR_API_KEY]"
)
val apolloClient = ApolloClient.Builder()
.appSync(connector.endpoint, connector.apiKeyAuthorizer()) …
```
> feat(Apollo): Add constructor to ApolloAmplifyConnector for directly specifying connection information

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthStateMachine.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/KotlinAuthFacadeInternal.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AssociateWebAuthnCredentialUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AuthUseCaseFactory.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/FetchDevicesUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ForgetDeviceUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ListWebAuthnCredentialsUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/RememberDeviceUseCase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/AssociateWebAuthnCredentialUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/DeleteWebAuthnCredentialsUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/FetchDevicesUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ForgetDeviceUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ListWebAuthnCredentialsUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/RememberDeviceUseCaseTest.kt
Moves logic for device management APIs (remember device, forget device, fetch devices) out of `RealAWSAuthCognitoPlugin` and into use case classes.
Unit tests
> chore(auth): Create use cases for device management APIs

- rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
These tests are frequently failing on CI. This appears to happen because the initial delay is too small, so the first update often gets missed by the observer. This is easy to reproduce locally by setting a small initial delay (like 10) which will cause the tests to often fail locally. On CI the delay needs to be much higher.
> fix(core): Fix random failures in RxStorageBindingTest

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/KotlinAuthFacadeInternal.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AuthUseCaseFactory.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/GetCurrentUserUseCase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/MockData.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/GetCurrentUserUseCaseTest.kt
- core/src/main/java/com/amplifyframework/util/ExceptionExtensions.kt
Use the cached user id (this is the "sub" from cognito) and username when invoking `getCurrentUser` instead of trying to fetch and parse a new access token.
This fixes a bug where `getCurrentUser` returns an error if the device is offline and the access token is expired. The user is still considered "signed in" in this scenario, however, so failing to return the current user is incongruent behaviour.
- Reproduced bug before fix, verified it does not occur after fix
- Unit tests
> fix(auth): Return cached user id and username instead of refetching them in getCurrentUser

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/data/LegacyKeyProvider.kt
https://github.com/aws-amplify/amplify-android/issues/2991
Prevents uncaught exception that occurs in legacy keystore migration when a keystore isn't available (ex: in an Instant App Launch). Verified that Auth + Authenticator will allow in memory sign in's with these changes.
> fix(auth): Prevent crash if KeyStore not available (ex: instant app)

- aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferWorkerObserver.kt
Issue #2840
The error appears on devices with limited heap (for example, some tablets or set-top boxes running Android 7.1.2/OS 14) when many pending transfers trigger multiple LiveData observer registrations in the TransferWorkerObserver. These duplicate observer registrations may lead to excessive internal allocations (via Room’s InvalidationTracker, MapBuilder, and SetBuilder), eventually causing OOM.
To address this, the PR introduces a thread-safe set (observedTags) that tracks which transfer tags have already been observed. In the attachObserver() method, we now check if the tag is already present in observedTags and return early if so; otherwise, the observer is registered and the tag is added to the set. Similarly, in …
> fix(storage): Prevent duplicate observer registration in TransferWorkerObserver to mitigate OOM issues

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthSession.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/KotlinAuthFacadeInternal.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AuthUseCaseFactory.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ConfirmUserAttributeUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/FetchUserAttributesUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ResendUserAttributeConfirmationUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/UpdateUserAttributesUseCase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/CustomMatchers.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ConfirmUserAttributeUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/FetchUserAttributesUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ResendUserAttributeConfirmationUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/UpdateUserAttributesUseCaseTest.kt
Continues refactoring `RealAWSCognitoAuthPlugin` class into smaller, coroutine based usecases. This PR covers the `fetchUserAttributes`, `confirmUserAttribute`, `resendUserAttributeConfirmationCode`, `updateUserAttribute` and `updateUserAttributes` APIs.
Unit test
Test App
> chore(auth): Move Attribute management into usecase classes

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/KotlinAuthFacadeInternal.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AuthUseCaseFactory.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/SetupTotpUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/VerifyTotpSetupUseCase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/SetupTotpUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/VerifyTotpSetupUseCaseTest.kt
- Moves the TOTP Setup functions into use case classes.
- Fixes some bugs in `setupTotp` where Amplify would hang (never invoke callbacks) in certain scenarios.
- Unit test
> chore(auth): Migrate TOTP setup to use case classes

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthStateMachine.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/KotlinAuthFacadeInternal.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AuthUseCaseFactory.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ConfirmSignUpUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ResendSignupCodeUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/SignUpUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/StateMachine.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ConfirmSignUpUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ResendSignupCodeUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/SignUpUseCaseTest.kt
Moves `signUp`, `confirmSignUp`, and `resendSignupCode` to usecase classes.
This PR adds lines because `signUp` and `confirmSignUp` did not have good unit test coverage, that has been improved in this PR.
> chore(auth): Move signup functions to usecases

- .github/workflows/issue_comment.yml
This change strips special characters before calling xargs when posting a Slack notification for issue comments, which fixes failures caused by comments that e.g. have quotes in them.
> chore: Remove special characters before calling xargs in comment notify

- appsync/aws-appsync-events/build.gradle.kts
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/Events.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsEndpoints.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/RestClient.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/PublishResult.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/utils/Headers.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/EventsEndpointsTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/EventsTest.kt
- appsync/aws-appsync-events/src/test/resources/publish_multi_failure.json
- appsync/aws-appsync-events/src/test/resources/publish_multi_partial_success.json
- appsync/aws-appsync-events/src/test/resources/publish_single_success.json
* Handles 200 range response codes for Events rest publishes
* Future PR will handle non 200 responses
* Unit tests are added. Will set up integration test suite at end of Events development phase
> feat(data): Event REST Publish for 200 codes

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/KotlinAuthFacadeInternal.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AuthUseCaseFactory.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/DeleteUserUseCase.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthConfigurationTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/testUtil/EventMatchers.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/testUtil/MockData.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/testUtils/MockData.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/DeleteUserUseCaseTest.kt
Moves the delete user functionality to a use case and adds unit tests covering this functionality.
Unit tests
Test app
> chore(auth): Move deleteUser to use case

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthSession.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/KotlinAuthFacadeInternal.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AuthUseCaseFactory.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/FetchAuthSessionUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/AuthorizationEvent.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/testUtil/EventMatchers.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/FetchAuthSessionUseCaseTest.kt
Refactors fetchAuthSession to move the logic into the usecase class. Adds additional unit test coverage.
> chore(auth): Refactor fetchAuthSession to useCase

- appsync/aws-appsync-core/src/main/java/com/amplifyframework/aws/appsync/core/Logger.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/Events.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsChannel.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsWebSocket.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsWebSocketProvider.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/WebSocketMessage.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/utils/ConnectionTimeoutTimer.kt
> feat(data): Events API Connection ack timeout handling

- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/Events.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsChannel.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsWebSocket.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/OkHttpConfigurationProvider.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/RestClient.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/EventsException.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/PublishResult.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/utils/Headers.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/EventsTest.kt
> feat(data):  Update Events API Contract

- appsync/aws-appsync-amplify/src/test/java/com/amplifyframework/aws/appsync/core/authorizers/AmplifyIamAuthorizerTest.kt
- appsync/aws-appsync-amplify/src/test/java/com/amplifyframework/aws/appsync/core/authorizers/AmplifyUserPoolAuthorizerTest.kt
- appsync/aws-appsync-amplify/src/test/java/com/amplifyframework/aws/appsync/core/util/AppSyncRequestSignerTest.kt
- appsync/aws-appsync-core/src/main/java/com/amplifyframework/aws/appsync/core/AppSyncRequest.kt
- appsync/aws-appsync-core/src/test/java/com/amplifyframework/aws/appsync/core/AppSyncRequestTest.kt
- appsync/aws-appsync-core/src/test/java/com/amplifyframework/aws/appsync/core/Logger.kt
- appsync/aws-appsync-events/build.gradle.kts
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/Events.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsChannel.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsWebSocket.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/RestClient.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/EventsException.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/WebSocketMessage.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/utils/ConnectionTimeoutTimer.kt
- appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/utils/JsonUtils.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/EventsTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/EventsWebSocketProviderTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/EventsWebSocketTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/WebSocketDisconnectReasonTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/data/EventsErrorTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/data/EventsExceptionTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/data/PublishResultTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/data/WebSocketMessageTest.kt
- appsync/aws-appsync-events/src/test/java/com/amplifyframework/aws/appsync/events/utils/ConnectionTimeoutTimerTest.kt
- appsync/aws-appsync-events/src/test/resources/publish_errors.json
> feat(data): Fix Data event parsing + unit tests

- appsync/aws-sdk-appsync-events/src/main/java/com/amazonaws/sdk/appsync/events/Events.kt
- appsync/aws-sdk-appsync-events/src/main/java/com/amazonaws/sdk/appsync/events/EventsChannel.kt
> feat(data) Events Publish upate

- aws-auth-cognito/build.gradle.kts
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/exceptions/webauthn/WebAuthnNotSupportedException.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/WebAuthnHelper.kt
- build.gradle.kts
- gradle/libs.versions.toml
Passkeys use credential manager, which require the play services dependency if running on pre-Android 13 devices. Previously customers had to add this dependency themselves, but we should have done it.
- Verified passkey usage works on device running Android 10
> fix(auth): Fix passkey usage on Android < 13 devices

- .github/workflows/codecov_code_coverage.yml
Use configured codecov token to upload coverage reports to avoid rate limiting.
> chore: Use codecov token for code report uploads

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/exceptions/webauthn/WebAuthnNotSupportedException.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/WebAuthnHelper.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/helpers/WebAuthnHelperTest.kt
If CredentialManager tells us a device doesn't support passkeys then throw a `WebAuthnNotSupportedException` instead of general `WebAuthnException`.
Added unit tests.
Unit tests
Replicate on pre-Android 28 device
> fix(auth): Update exception handling for devices that don't support passkeys

- appsync/aws-sdk-appsync-events/src/androidTest/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClientTests.kt
- appsync/aws-sdk-appsync-events/src/main/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClient.kt
- appsync/aws-sdk-appsync-events/src/test/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClientTest.kt
> fix(data) Modify unsubscribe event scenarios

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/asf/DeviceDataCollector.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/asf/DeviceDataCollectorTest.kt
*Issue #, if available:* #3057
Use displayMetrics to get the size of the display instead of WindowManager. Added unit tests.
Verified that app crashes on signIn if the following strictMode is used, but does not crash afterwards:
```kotlin
StrictMode.setVmPolicy(
StrictMode.VmPolicy.Builder()
.detectIncorrectContextUse()
.penaltyLog()
.penaltyDeath()
.build()
)
```
Verified that the same device size is returned before and after the change.
> fix(auth): Remove WindowManager usage from DeviceDataCollector

- appsync/aws-sdk-appsync-events/src/main/java/com/amazonaws/sdk/appsync/events/EventsWebSocket.kt
- appsync/aws-sdk-appsync-events/src/main/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClient.kt
- appsync/aws-sdk-appsync-events/src/test/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClientTest.kt
- appsync/aws-sdk-appsync-events/src/test/java/com/amazonaws/sdk/appsync/events/EventsWebSocketTest.kt
> Fix events test lockups

- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLLazyCreateInstrumentationTest.kt
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLLazyDeleteInstrumentationTest.kt
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLLazyQueryInstrumentationTest.kt
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLLazyUpdateInstrumentationTest.kt
- aws-api/src/androidTest/java/com/amplifyframework/api/aws/extensions/LazyModelList.kt
- aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginUserAuthTests.kt
In some API test cases, results were in the paged list, so tests were failing by not getting the expected total counts. This ensure's that all lazy model lists fetch all pages.
> fix(data) Stabilize API/Auth tests

- configuration/instrumentation-tests.gradle
- scripts/run_test_in_devicefarm.sh
> chore: Modularize Integration Test Runs

- aws-logging-cloudwatch/src/test/kotlin/com/amplifyframework/logging/cloudwatch/CloudWatchLogManagerTest.kt
- aws-logging-cloudwatch/src/test/kotlin/com/amplifyframework/logging/cloudwatch/LoggingConstraintsResolverTest.kt
- aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/transfer/worker/ImmediateTaskExecutor.kt
- gradle/libs.versions.toml
Fixes unclosed databases in the unit tests for cloudwatch logging plugin. This was addressed in version **2.9.0** of the WorkManager test artifact, which added the `closeWorkDatabase()` function. (see [here](https://issuetracker.google.com/issues/242026176))
I updated to **2.9.1**, which is the latest version that didn't require adjusting our compile SDK.
I replaced the `workmanager-runtime-ktx` dependency with `workmanager-runtime` because as of version 2.9.0 the KTX functionality was promoted to the main artifact, and `workmanager-runtime-ktx` is now empty.
Verified that no error logs emitted by these tests.
By submitting this pull request, I confirm …
> chore: Fix unclosed databases in WorkManager tests

- aws-push-notifications-pinpoint-common/build.gradle.kts
- aws-push-notifications-pinpoint/build.gradle.kts
- gradle/libs.versions.toml
- Updates firebase to the latest version. This fixes duplicate class errors for customers who are trying to use recent versions of the `firebase-messaging` artifact because the `-ktx` artifact classes have been merged into the main artifact.
- Migrates to using the firebase bom.
> fix(notifications): Update to latest firebase bom

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthConfiguration.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/HostedUIHelper.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/OauthConfiguration.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthConfigurationTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/statemachine/codegen/data/OauthConfigurationTest.kt
https://github.com/aws-amplify/amplify-android/issues/3078
Multiple redirect uris can't be passed to Cognito. We need to select one. We will attempt to select the first app redirect scheme (non http, https).
> fix(auth): Select first non http(s) redirect

- .github/workflows/codecov_code_coverage.yml
- aws-auth-cognito/src/test/java/com/amplifyframework/statemachine/StateMachineListenerTests.kt
Removes the `testNoNotifyImmediateCancel` test. This test has a threading race condition (easily verifiable by adding a `Thread.sleep(100)` call to the test body) causing it to inconsistently fail on CI.
Also updated the code coverage workflow to save test results if the job fails, allowing us to see the particular failure which will help in tracking down other test issues.
> chore: Remove inconsistent test

- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/AutoSignInUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ConfirmSignUpUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/DeleteUserUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/SignUpUseCase.kt
- aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/StateMachine.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ConfirmSignUpUseCaseTest.kt
- aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/SignUpUseCaseTest.kt
- Use `onSubscription` instead of `onStart` to trigger state machine events while collecting. `onStart` does not guarantee that emissions generated from the block are visible in downstream collectors when used on a SharedFlow.
- Use SharedFlow for emitting states instead of a StateFlow because StateFlow will conflate emitted values, which can skip required intermediate states in subscribers.
These changes shouldn't effect production behaviour, but in unit tests this resolves some race conditions that happened when states update too quickly.
- Tests should pass
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> chore(auth): Fix race conditions in read state machine states
