aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java
Fixes config keys to match what the CLI is generating
=> [Storage] Fixes config keys

aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java, aws-api/src/main/java/com/amplifyframework/api/aws/operation/AWSRestOperation.java, aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestOperationRequestUtils.java, aws-api/src/test/java/com/amplifyframework/api/aws/utils/RestOperationRequestUtilsTest.java, core/src/main/java/com/amplifyframework/api/rest/RestOperationRequest.java, core/src/main/java/com/amplifyframework/api/rest/RestOptions.java, core/src/test/java/com/amplifyframework/api/rest/RestOptionsTest.java
- Implemented a Builder for `RestOptions`
- `RestOptions` takes header values
- Added unit tests.
=> [API] Added headers for rest request

aws-analytics-pinpoint/gradle.properties, aws-api/gradle.properties, aws-datastore/gradle.properties, aws-storage-s3/gradle.properties, core/gradle.properties
=> Update artifact description to indicate preview version

gradle.properties
=> Fix group id typo

core/gradle.properties
=> Update core artifact id

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlCommand.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTable.java, core/src/main/java/com/amplifyframework/analytics/Properties.java, core/src/main/java/com/amplifyframework/api/rest/RestOperationRequest.java, core/src/main/java/com/amplifyframework/api/rest/RestOptions.java, core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java, core/src/main/java/com/amplifyframework/core/model/ModelSchema.java, core/src/main/java/com/amplifyframework/core/model/ModelSchemaRegistry.java, core/src/main/java/com/amplifyframework/util/FieldFinder.java, core/src/main/java/com/amplifyframework/util/Immutable.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/AmplifyModelProvider.java, testmodels/src/main/java/com/amplifyframework/testmodels/personcar/AmplifyCliGeneratedModelProvider.java, testmodels/src/main/java/com/amplifyframework/testmodels/personcar/RandomVersionModelProvider.java, testutils/src/main/java/com/amplifyframework/testutils/LatchedResponseStreamListener.java
It is a utility class, but it was packaged with the other utilities.
=> [Core] Move Immutable helper to utils Java package

core/src/main/java/com/amplifyframework/core/Amplify.java
=> [Core] Cleanup code quality issues in Amplify facade

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapterInstrumentedTest.java
Fix test failure due to slight deviation in exception messages between local machine and circleCI's machine.
=> Fix test for invalid foreign key

aws-datastore/src/test/java/com/amplifyframework/datastore/network/ModelProviderFactory.java
=> [DataStore] Fix import of Immutable

aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/AnalyticsPinpointInstrumentedTest.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AmazonPinpointAnalyticsPlugin.java, build.gradle, core/src/main/java/com/amplifyframework/analytics/AnalyticsCategory.java, core/src/main/java/com/amplifyframework/analytics/AnalyticsCategoryBehavior.java
=> [Analytics] Add support for global event properties

aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java, core/src/main/java/com/amplifyframework/core/model/ModelSchemaRegistry.java
=> [SQLiteStorageAdapter] Minor refactoring

aws-datastore/src/main/java/com/amplifyframework/datastore/network/SyncEngine.java, build.gradle
=> Restore build (two separate git commits)

.circleci/copy-configs, .gitignore, aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java, aws-api/src/androidTest/java/com/amplifyframework/api/aws/TestAWSMobileClient.java, aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncSigV4SignerInterceptorFactory.java, aws-api/src/main/java/com/amplifyframework/api/aws/EndpointType.java, aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/ApiGatewayIamSigner.java, aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/AppSyncSigV4SignerInterceptor.java, aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestOperationRequestUtils.java
* Issues: #169 
Changes to support signing a Rest Request with IAM credentials.
- Made `EndpointType` public
- New signed class for ApiGateway IAM
- Removed hard coded header `content-type`
=> [API] IAM support for REST api request

configuration/checkstyle-rules.xml, configuration/java.header
Update copyright header for checkstyle
=> Update checkstyle rules to accept variable copyright year

.circleci/config.yml
=> Enhancements to CircleCI Configuration

build.gradle
=> OkHttp 4.3.0 -> 4.3.1

aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointClientFactory.java, aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java, aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java, aws-api/src/main/java/com/amplifyframework/api/aws/UserAgentInterceptor.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.java, core/src/main/java/com/amplifyframework/util/UserAgent.java
=> Add User-Agent header to all outbound network requests

build.gradle
=> Use latest AWS SDK release 2.16.7

aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AmazonPinpointAnalyticsPlugin.java, aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageDownloadFileOperation.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageUploadFileOperation.java, core/src/main/java/com/amplifyframework/core/category/Category.java
- Resolves 9 "Missing space in string literal" recommendations.
- Resolves 3 "Dereferenced variable may be null" warnings.
=> Resolve some issues found by LGTM.com.

aws-datastore/src/main/java/com/amplifyframework/datastore/network/AppSyncApi.java, aws-datastore/src/test/java/com/amplifyframework/datastore/network/MockAppSyncEndpoint.java, core/src/main/java/com/amplifyframework/core/async/NoOpCancelable.java
=> [core] Move NoOpCancelable into core module

.circleci/config.yml, build.gradle, configuration/checkstyle.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Android Gradle Plugin -> 3.6.0
Gradle -> 6.2.1
OkHttp -> 4.4.0
Checkstyle -> 8.29
AndroidX Core -> 1.2.0
AWS SDK -> 2.16.8
=> Use latest dependency versions

.circleci/copy-configs, .gitignore, aws-storage-s3/build.gradle, aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageDownloadAccessLevelTest.java, aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageDownloadTest.java, aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadAccessLevelTest.java, aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java, aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/TestConfiguration.java, testutils/src/main/java/com/amplifyframework/testutils/FileAssert.java, testutils/src/main/java/com/amplifyframework/testutils/Resources.java, testutils/src/main/java/com/amplifyframework/testutils/random/RandomTempFile.java, testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousMobileClient.java
Added tests for storage category (see #259)
=> Add storage instrumentation tests

aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/ModelMetadata.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/PersistentModelVersion.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTable.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java, core/src/main/java/com/amplifyframework/core/model/Model.java, core/src/main/java/com/amplifyframework/core/model/ModelSchema.java, testutils/src/main/java/com/amplifyframework/testutils/random/RandomModel.java
=> Storage adapter error handling cleanups

aws-analytics-pinpoint/proguard-rules.pro, aws-api/proguard-rules.pro, aws-datastore/proguard-rules.pro, aws-storage-s3/proguard-rules.pro, core/proguard-rules.pro, rxbindings/proguard-rules.pro, testmodels/proguard-rules.pro, testutils/proguard-rules.pro
Refer: https://stackoverflow.com/a/39356251/695787
=> Don't rename source file attribute in ProGuard

build.gradle
Refer: https://stackoverflow.com/a/39356251/695787
=> Android Gradle Plugin to 3.6.1.

CONTRIBUTING.md
*Description of changes:* Fix a small typo in the Contributing Guidelines
=> Fix path to copy-configs script

.circleci/config.yml, gradle/wrapper/gradle-wrapper.properties
=> Use the latest Gradle release, 6.2.2.

aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/AnalyticsPinpointInstrumentedTest.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AmazonPinpointAnalyticsPlugin.java
Update plugin key for analytics to match the key name generated by CLI
=> [Analytics] Update the plugin key for analytics to match one generated by the cli

aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AmazonPinpointAnalyticsPlugin.java, aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java, aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java, core/src/main/java/com/amplifyframework/core/plugin/Plugin.java, core/src/main/java/com/amplifyframework/hub/AWSHubPlugin.java, core/src/main/java/com/amplifyframework/logging/AndroidLoggingPlugin.java
Make plugin configuration nullable and force the implementation to null-check if it is required
=> Make plugin configuration nullable

README.md, rxbindings/README.md
=> Advertise version 0.10.0 in the README.md.

.circleci/config.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Latest Gradle and Android Gradle Plugin

build.gradle
=> Use Latest SDK, 2.16.11.

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/StorageItemChange.java, configuration/checkstyle-rules.xml
=> Enforce a consistent annotation specification style

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, core/src/main/java/com/amplifyframework/auth/AuthCategory.java, core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java, core/src/main/java/com/amplifyframework/auth/AuthCodeDeliveryDetails.java
=> Adds confirmSignIn to Auth

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, core/src/main/java/com/amplifyframework/auth/AuthCategory.java, core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java
https://quip-amazon.com/V550Arr1aKJN/Amplify-Auth-Category-Interface#KVW9CAtlT6x
=> Adds forgotPassword/confirmForgotPassword

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthProvider.java, core/src/main/java/com/amplifyframework/auth/AuthCategory.java, core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java, core/src/main/java/com/amplifyframework/auth/AuthProvider.java
Takes the prototype method of just Facebook and makes it generic for other providers.
=> Adds social sign in

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.java
=> [aws-datastore] Log Sync events as Info

build.gradle
=> Update Android Gradle Plugin to latest, 3.6.3.

aws-predictions/src/androidTest/java/com/amplifyframework/predictions/aws/AWSPredictionsIdentifyEntitiesTest.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/AWSPredictionsPluginConfiguration.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/NetworkPolicy.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/EmotionTypeAdapter.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/GenderBinaryTypeAdapter.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/IdentifyResultTransformers.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/configuration/IdentifyEntitiesConfiguration.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/operation/AWSIdentifyOperation.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSPredictionsService.java, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSRekognitionService.java, core/src/main/java/com/amplifyframework/predictions/models/Feature.java
* Add configuration for `identifyEntities`
* Implement entities detection + entity match detection
=> Implement online entity detection

CONTRIBUTING.md, README.md
Missed some feedback on https://github.com/aws-amplify/amplify-android/pull/413. Applying it here.
=> A few small doc tweaks to README.md, CONTRIBUTING.md.

aws-api/build.gradle, aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java, aws-api/src/test/resources/blog-owners-query-results.json, build.gradle
Tests two simple mutation and query behaviors of the AWSApiPlugin
component, by using a MockWebServer to replay "cooked" responses from
OkHttp.
=> [aws-api] Basic GraphQL components tests for AWSApiPlugin

aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfigurationProvider.java
small PR to fix a checkstyle violation in master.
I'm not sure my docs are 100% accurate but my main goal is to get a green build. Follow up with improvements will be more than welcome. :)
=> fix datastore javadoc checkstyle

core/src/androidTest/java/com/amplifyframework/hub/HubInstrumentedTest.java
This test is flakey, and frequently fails. Further effort will be
required to determine a root cause. Meanwhile, we would like to bulid a
consistent baseline of passing tests, from which we can build.
=> [core] Ignore HubInstrumentedTest#multiplePublications

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, core/src/main/java/com/amplifyframework/auth/AuthChannelEventName.java, core/src/main/java/com/amplifyframework/datastore/DataStoreChannelEventName.java
Adds hub events to Auth to notify when these three globally relevant events happen:
- Signed out
- Signed in
- Session expired
=> Adds Hub events for Auth

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java, core/src/main/java/com/amplifyframework/auth/AuthCategory.java, core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java, testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
Adds the sign out method to Auth with unit tests.
=> Adds sign out to Auth

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
=> [aws-auth-cognito] Fix checkstyle issue

aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfiguration.java
=> [aws-datastore] Remove an unused constant

aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/AnalyticsPinpointInstrumentedTest.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointManagerFactory.java
Some basic formatting and style tweaks
=> [aws-analytics-pinpoint] Minor formatting and style tweaks

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
=> [aws-datastore] Minor code style tweaks in SQLiteStorageAdapter

core/src/main/java/com/amplifyframework/api/graphql/GraphQLLocation.java, core/src/main/java/com/amplifyframework/api/graphql/GraphQLPathSegment.java, core/src/main/java/com/amplifyframework/api/graphql/GraphQLResponse.java, core/src/main/java/com/amplifyframework/api/rest/RestOperationRequest.java, core/src/main/java/com/amplifyframework/api/rest/RestOptions.java, core/src/main/java/com/amplifyframework/api/rest/RestResponse.java
=> [core] Add equals hashCode toString for API data classes

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java
Turns out that even though AWSMobileClient was throwing runtime exceptions for global sign out, they had a special class setup to catch them and report them through the onError callback so updating our code to handle them properly.
=> Fixes global signout exception handling

aws-datastore/src/main/java/com/amplifyframework/datastore/ApplyRemoteConflictHandler.java, aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfiguration.java
=> [aws-datastore] equals, toString, hashCode for config and conflict handler

build.gradle
=> Update OkHttp to latest, 4.7.2.

aws-analytics-pinpoint/proguard-rules.pro, aws-api/proguard-rules.pro, aws-auth-cognito/proguard-rules.pro, aws-datastore/proguard-rules.pro, aws-predictions-tensorflow/proguard-rules.pro, aws-predictions/proguard-rules.pro, aws-storage-s3/proguard-rules.pro, build.gradle, core/proguard-rules.pro, rxbindings/proguard-rules.pro, testmodels/proguard-rules.pro, testutils/proguard-rules.pro
Removes allowAccessModification from ProGuard 
=> Removes allowAccessModification from ProGuard

README.md
*Description of changes:* Draft of README updates for 1.0.0.
=> README Updates for 1.0.0

.circleci/config.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Android Gradle Plugin 4.0.0, Gradle 6.4.1, AndroidX Core 1.3.0.

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java, aws-predictions-tensorflow/src/main/java/com/amplifyframework/predictions/tensorflow/service/TensorFlowTextClassificationService.java
A `CountDownLatch` will hang a thread indefinitely if invoked by `await()`.
Likewise, an Rx `Completable` will do the same, if invoked by `blockingAwait()`
(it operates very similarly to the latch.)
Instead, use the time-bound versions of these calls, which return a
boolean indicating whether or not they achieved their desired state
within an allotted time window.
This prevents a thread from becoming permanently hung without reporting
a failure to operate.
=> Add time constraints on unbounded blocking calls

rxbindings/src/main/java/com/amplifyframework/rx/RxAmplify.java, rxbindings/src/main/java/com/amplifyframework/rx/RxPredictionsBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxPredictionsCategoryBehavior.java, rxbindings/src/test/java/com/amplifyframework/rx/RxPredictionsBindingTest.java
=> feat(rxbindings): add binding for predictions

README.md
https://docs.amplify.aws/lib/getting-started/setup/q/platform/android `404`s
=> Fix Getting Started link

.github/CODEOWNERS
=> chore: add code maintainers for default reviewers

.circleci/codecov.sh, .circleci/config.yml
=> ci: vend codecov script to avoid downloading from an untrusted source

aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java
=> fix(datastore) Missed a function name change during merge

aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
My changes for #599 ended up causing some subscription related tests to fail. This PR fixes that.
=> fix(api) Fix tests broken by PR #599

core/src/main/res/layout/fragment_device.xml, core/src/main/res/layout/fragment_logs.xml, core/src/main/res/values/strings.xml
*Description of changes:* Created the developer menu logs UI shown in the picture below.
=> Create logs UI for developer menu

aws-api/src/test/java/com/amplifyframework/api/aws/UserAgentTest.java
=> chore(api): Fix flakey UserAgentTest

rxbindings/README.md
=> chore: rxbindings readme refer to latest artifacts

aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java, build.gradle
Uses the latest version of the AWS SDK
=> Updates to latest SDK version

README.md
=> chore: update readme to point to latest release

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageReservedWordTest.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteColumn.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTable.java
This is an expansion to address a missed case from #712 and other sources of test failure.
=> fix(aws-datastore): address issue where primary key was not properly quoted

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SqlKeyword.java
fix typo in sql keyword between
=> fix(datastore): typo in sql keyword between

.circleci/config.yml
=> Trying to pin the image version

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, build.gradle
Updates Amplify to use the latest version of the SDK including the fixed version of HostedUI. In order to enable users to listen for the proper activity result, it also exposes the activity result code.
=> fix(auth): Updates to use fixed HostedUI

core/src/test/java/com/amplifyframework/util/UserAgentTest.java
Change hardcoded value of `main` in favor of pulling the version name from `gradle.properties`
=> Pull version name from BuildConfig

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, build.gradle
Reverts #734 due to not passing user acceptance testing.
=> Revert #734

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageHelper.java
Related to #707 
Wrapping tablename in drop statement
=> fix(datastore) quote drop table command

build.gradle, gradle/wrapper/gradle-wrapper.properties
Gradle -> 6.6
AndroidX Core -> 1.3.1
=> chore: update dependencies

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, build.gradle
Fixes issue #552 as well as the inability to sign in with MFA on the web UI flow.
=> feat(auth): Adds improved signInWithWebUI functionality

aws-predictions/src/androidTest/java/com/amplifyframework/predictions/aws/AWSPredictionsTranslateTest.java
=> fix: relax condition of translate assertion

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthComponentTest.java, core/src/main/java/com/amplifyframework/auth/AuthCategory.java, core/src/main/java/com/amplifyframework/auth/AuthCategoryBehavior.java, core/src/main/java/com/amplifyframework/auth/AuthDevice.java, rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxAuthCategoryBehavior.java, rxbindings/src/test/java/com/amplifyframework/rx/RxAuthBindingTest.java, testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
Add `rememberDevice()`, `forgetDevice()`, and `fetchDevices()` in the Auth category
=> feat(aws-auth-cognito): implement device tracking

aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLInstrumentationTest.java, aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java
=> chore(ci) ignore tests failing due to resources that no longer exist

core/src/main/java/com/amplifyframework/core/Amplify.java
=> fix: do not allow changing plugins after configure

CONTRIBUTING.md
=> Resolve a typo in #Contributing via Pull Requests

core/src/main/java/com/amplifyframework/datastore/DataStoreCategoryBehavior.java, rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreCategoryBehavior.java
=> fix(datastore) tweak docs to mention sorting

rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java
Make the classes public so people can actually use them.
=> fix(rxbindings) Modify accessor for storage operation

core/src/main/java/com/amplifyframework/datastore/DataStoreCategoryBehavior.java, rxbindings/src/main/java/com/amplifyframework/rx/RxAdapters.java, rxbindings/src/main/java/com/amplifyframework/rx/RxApiBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxAuthBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxDataStoreCategoryBehavior.java, rxbindings/src/main/java/com/amplifyframework/rx/RxGraphQlBehavior.java, rxbindings/src/main/java/com/amplifyframework/rx/RxHubBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxOperations.java, rxbindings/src/main/java/com/amplifyframework/rx/RxPredictionsBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxStorageCategoryBehavior.java, rxbindings/src/test/java/com/amplifyframework/rx/RxAdaptersTest.java, rxbindings/src/test/java/com/amplifyframework/rx/RxApiBindingTest.java, rxbindings/src/test/java/com/amplifyframework/rx/RxDataStoreBindingTest.java, rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
This PR is an aggregate of all the changes made to the feature branch `features/rxbindings`. See individual list of commits for all the approvals of individual PRs merged into the feature branch
=> feat(rxbindings) RxBindings improvements.

rxbindings/README.md
=> fix: rxbindings readme v2 to v3

CONTRIBUTING.md
=> chore: Add details on how to point to mavenLocal

CONTRIBUTING.md
=> Fix a typo in gradle configuration of mavenLocal 

build.gradle
=> chore(build) Update awsSdkVersion dependency to 2.19.0

aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java, core/src/main/java/com/amplifyframework/util/FieldFinder.java
Fixes https://github.com/aws-amplify/amplify-android/issues/817
- See comments in code for explanation of the fix.
=> fix(api) Fix ClassCastException when building selection set for custom types

README.md, rxbindings/README.md
=> chore: point to latest version in README.md files

README.md, rxbindings/README.md
=> chore: update READMEs to highlight 1.4.0 release

build.gradle
=> chore(build): update build tools version

core/src/androidTest/java/com/amplifyframework/devmenu/DevMenuMainViewInstrumentationTest.java
=> chore(devmenu) ignore failing instrumentation tests

CONTRIBUTING.md
=> chore: document log threshold configuration

.github/stale.yml
*Description of changes:* Uses the stale.yml from the SDK repo here to configure Stale bot.
=> Add stale configuration

README.md, rxbindings/README.md
Ues the latest release version in `README.md` file
=> chore: use the latest release version in readme

aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncSigV4SignerInterceptorFactory.java, aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncSigV4SignerInterceptorFactoryTest.java, build.gradle
=> chore: update okhttp dependencies to 4.9.0

build.gradle
=> chore: update androidx core to 1.3.2.

aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java, core/src/main/java/com/amplifyframework/core/model/AuthRule.java, testmodels/src/main/java/com/amplifyframework/testmodels/ownerauth/OwnerAuth.java
Modifies our code to fetch whatever value from the access token specified by the user (or the default username if the user didn't specify one)
=> fix(API): Adds support for custom identity claim

build.gradle
=> chore: update AWS SDK version

README.md, rxbindings/README.md
=> Update README to reference latest release 1.4.2

README.md
=> chore: tweaks to verbiage of README

aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java, aws-api/src/test/java/com/amplifyframework/api/aws/auth/OwnerBasedAuthTest.java
Support custom group claim for OIDC `@auth` use-case.
*No tests are included in this PR, but the changes were tested in a sample app. Explicit unit tests will follow in a separate PR unless requested otherwise.*
=> feature(aws-api): support custom group claim

aws-api/src/test/java/com/amplifyframework/api/aws/auth/AuthRuleRequestDecoratorTest.java
fixes checkstyle error that was introduced in #920 
=> chore(aws-api): checkstyle fixup

aws-api-appsync/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequest.java, aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java, aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java, aws-api/src/test/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactoryTest.java, aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java, aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java, core/src/main/java/com/amplifyframework/core/model/ModelAssociation.java, core/src/main/java/com/amplifyframework/core/model/ModelSchema.java, core/src/main/java/com/amplifyframework/util/FieldFinder.java
Addresses some Android Studio / IntelliJ code tips.
=> chore: miscellaneous code cleanups

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentedTest.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/DataStoreCategoryConfigurator.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/DataStoreHubEventFilters.java, testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousDataStore.java
Validate that they will run manually, if you remove the \@Ignore. Update
the rationale for these tests being ignored.
=> chore: update basic cloud sync tests

README.md, rxbindings/README.md
=> chore: Advertise version 1.6.0 in READMEs

README.md, rxbindings/README.md
=> chore(release) Update READMEs to reference latest version, 1.6.2

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
=> fix(aws-datastore): kludges to support flutter connected models

README.md, rxbindings/README.md
=> chore: 1.6.3 branding

README.md, rxbindings/README.md
=> chore: advertise 1.6.4.

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java
When the DataStore is used from Flutter, Java-language model classes
don't exist.
The Merger component is responsible for applying remote mutations onto
the local store. It contained an ifPresent() check, which checked for
the presence of a model by its Java class. This method would fail to
work as expected when the SerializedModel envelope type was used.
ifPresent() has been updated to query the local store by model name,
instead of using the Java class.
Resolves: https://github.com/aws-amplify/amplify-android/issues/994
=> fix: honor deletions from AppSync when used by Flutter

aws-datastore/src/androidTest/assets/schemas/meeting/meeting.json, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridAssociationSyncInstrumentationTest.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridTemporalSyncInstrumentationTest.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java
Resolves: https://github.com/aws-amplify/amplify-android/issues/998
=> fix(aws-datastore): support temporal types in Flutter

aws-api-appsync/src/main/java/com/amplifyframework/core/model/types/GsonJavaTypeAdapters.java, aws-api-appsync/src/test/java/com/amplifyframework/core/model/types/GsonJavaTypeAdaptersTest.java
Resolves: https://github.com/aws-amplify/amplify-android/issues/997
=> fix: comprehend deserialization of primitive types

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/OutboxMutationEvent.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/OrchestratorTest.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/TestHubEventFilters.java
Resolves: https://github.com/aws-amplify/amplify-android/issues/1012
=> chore(aws-datastore): align OutboxMutationEvent to iOS

aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java
=> chore: improve recovery suggestions during lost connectivity

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
Fixes https://github.com/aws-amplify/amplify-android/issues/1017
=> fix(datastore) hybrid query results should be sorted when sort order provided

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java
Fixes #1050
DataStore model mutation responses from AppSync are being discarded and the model _version is not being updated properly in the local store. Once that is fixed, outbox mutations for SerializedModels will crash during save because they are missing the modelSchema property.
The discard is happening due to code that removes outstanding mutations and code that checks for outstanding mutations before proceeding are not being called in the opposite order as desired. 
=> fix(aws-datastore): MutationProcessor - Resolve out-of-sync model  version

aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLOperation.java, aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java, aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionOperation.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessor.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SubscriptionProcessorTest.java
Fixes https://github.com/aws-amplify/amplify-android/issues/541 (DataStore crashes when device goes offline)
=> fix(aws-datastore): Resolves crash when going offline

README.md
=> chore: add GitHub release and Maven Central badges

README.md, rxbindings/README.md
=> chore (release) 1.6.8

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
When an item is removed from the Mutation Outbox, there is a check to
see if there are more items in the Outbox. If so, the code is meant to
continue processing outbox items until they're all processed.
However, the notification to continue processing additional items was
broken. As a result, the mutation outbox may not have been fully
processed in some cases.
Resolves: https://github.com/aws-amplify/amplify-android/issues/1083
=> fix: continue processing outbox items after removal

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
Previously, if a customer were to try to create the same object twice, like this:
```
val blog = Blog.builder()                    
.name("My Blog")
.build()
Amplify.DataStore.save(blog, {}, {})
Amplify.DataStore.save(blog, {}, {})
```
both would successfully be added to the mutation outbox.  This was because the second mutation was checking for existence of the item in the queue before the first mutation was complete.  This PR moves the logic in `enqueue` which checks existence of the item into the `Completable`, so that it happens _after_ the first mutation completes. 
It also makes a similar change to the `remove` method, so that it is synchronized as well.
Lastly, I removed any `Completeable.defer` that just wrapped a `Completable.create`, because `Completable.create` already defers …
=> fix(datastore) Make PersistentMutationOutbox operations synchronized

CONTRIBUTING.md, gradle.properties
Change local version name of build to `local` from `main`.
=> chore: update contributing

build.gradle
=> chore: increment SDK version to 2.22.0

build.gradle
=> chore: increment SDK version to 2.22.1

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
=> chore(datastore) minor simplification in SQLiteStorageAdapter

.github/workflows/gradle.yml
=> chore: create GitHub action to build and test

README.md, rxbindings/README.md
=> Release 1.6.10

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java
Use the correct schema for building serialized model.
=> fix(datastore): incorrectly serialized model for cascaded delete

README.md, rxbindings/README.md
=> chore: publicize 1.6.11 release

configuration/instrumentation-tests.gradle, scripts/devicefarm-test-runner-buildspec.yml, scripts/generate_df_testrun_report, scripts/pull_backend_config_from_amplify, scripts/run_test_in_devicefarm.sh
Adding a script to generate junit xml compatible output based on device farm test execution. This is a building block which will be used to provide better access to test reports.
=> chore(ci/cd):Generate build reports from DF data

core/src/main/java/com/amplifyframework/core/category/Category.java
Currently, when a customer tries to use a plugin that is not configured, they get this error:
`Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.`
This error makes sense if the current state is `NOT_CONFIGURED` or `CONFIGURING`.  However, if the state is `FAILED`, it could be because either configuration or initialization failed, so we should throw a more useful error.
=> fix(core): Improve error messaging when category configuration or initialization fails

.github/workflows/gradle.yml, scripts/retry.sh
=> chore(ci) retry build 3 times before failing

README.md, rxbindings/README.md
=> chore(release): bump library version in docs

build.gradle, gradle/wrapper/gradle-wrapper.properties
| Dependency | Old Version | New Version |
|-------------|------------|-------------|
| Gradle | 6.7.1 | **6.8.2** |
| OkHttp | 4.9.0 | **4.9.1** |
| MockWebServer | 4.9.0 | **4.9.1** |
| Robolectric | 4.4 | **4.5.1** |
| AndroidX Navigation | 2.3.2 | **2.3.3** |
=> chore: update project dependencies

CONTRIBUTING.md, gradle.properties
Update `gradle.properties` to use live version name rather than "local" for release workflow enhancement. 
=> chore: update local version name to live

build.gradle
=> chore: Update SDK version to 2.22.2

README.md, gradle.properties, rxbindings/README.md
=> release: 1.16.15

core-kotlin/gradle.properties
=> release: Core kotlin 0.1.1

README.md, gradle.properties, rxbindings/README.md
=> release: 1.17.0

.github/stale.yml
Setting daysUntilStale to 30
Borrowed the same setting from [amplify-js](https://github.com/aws-amplify/amplify-js/blob/main/.github/stale.yml)
=> chore: update stalebot settings

.github/stale.yml
=> chore: add quotes to labels with spaces

README.md
=> chore: update docs links in the readme

build.gradle
=> chore: update SDK dependency to 2.22.3

aws-api/src/main/java/com/amplifyframework/api/aws/auth/ApiRequestDecoratorFactory.java
When making the change for #1238 a regression was introduced for cases where the API plugin was initialized without passing in an Cognito auth provider. [The previously used interceptor had logic to default](https://github.com/aws-amplify/amplify-android/blob/b0a71c80a2a0c416fa1f28f22e6f43d7114b7de7/aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncSigV4SignerInterceptorFactory.java#L106) to using the `DefaultCognitoUserPoolsAuthProvider` if one was not available via `ApiAuthProviders`
This logic is now replicated here. 
Also, modified the logic to throw exceptions when the necessary provider for the requested auth mode is not available.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> fix(aws-api): use default cognito provider if needed.

build.gradle
=> chore: update SDK to 2.22.5

aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncClientInstrumentationTest.java, testutils/src/main/java/com/amplifyframework/testutils/FieldValue.java, testutils/src/main/java/com/amplifyframework/testutils/ModelOverride.java
extension of #1259 
Created utility class to easily override model properties and fixed another test suite with timestamp problems.
=> chore: fix integration tests involving model comparison

README.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
=> chore(release): version bump to 1.17.2

.github/workflows/release_pr_approval_count.yml
Needed to update the branch name and PR title for the workflow that checks for 2 approvals on release PRs
=> fix(ci): update branch name and PR subject

.github/workflows/release_pr.yml
=> chore: update name of workflow that prepares next release

build.gradle
=> chore: bump sdk version to 2.22.6

scripts/fastlane/Fastfile
Same fix as the one for the AppSync and V2 SDKs
=> fix: change protocol for github import

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.17.3\nAmplify Android 0.1.4
=> release: Amplify Android 1.17.3

build.gradle
Upgrade `awsSdkVersion` dependency of Amplify library.
=> chore(release): Depend on latest sdk version

build.gradle
=> chore(release): Upgrade dependency on the latest SDK version

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.17.4\nAmplify Android 0.1.5
=> release: Amplify Android 1.17.4

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.17.5\nAmplify Android 0.1.6
=> release: Amplify Android 1.17.5

aws-api-appsync/src/test/java/com/amplifyframework/datastore/appsync/ModelConverterTest.java, aws-api-appsync/src/test/resources/selection-set-post.txt, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AppSyncClientInstrumentationTest.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/DataStoreCategoryConfigurator.java, aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java, aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLiteTableTest.java, aws-datastore/src/test/resources/create-comment-request.txt, aws-datastore/src/test/resources/delta-sync-request-document-for-post.txt, aws-datastore/src/test/resources/on-create-request-for-blog.txt, aws-datastore/src/test/resources/on-update-request-for-post.txt, aws-datastore/src/test/resources/update-blog-owner-with-predicate.txt, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/AmplifyModelProvider.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Author.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Blog.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/BlogOwner.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Comment.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/Post.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/PostAuthorJoin.java, testmodels/src/main/java/com/amplifyframework/testmodels/commentsblog/schema.graphql
=> chore: fix datastore integration test timeout by using sync expressions to limit the sync

configuration/checkstyle-suppressions.xml
*Issue #836 *
Updated checkstyle suppression file path to be cross platform friendly.
=> fix: checkstyle failure on Windows

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.17.6\nAmplify Android 0.1.7
=> release: Amplify Android 1.17.6

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.17.7\nAmplify Android 0.1.8
=> release: Amplify Android 1.17.7

build.gradle
Update SDK version to the latest release.
=> chore: update sdk version

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.17.8\nAmplify Android 0.1.9
=> release: Amplify Android 1.17.8

build.gradle
=> chore: Update dependency on the latest SDK version

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.18.0\nAmplify Android 0.2.0
=> release: Amplify Android 1.18.0

aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java, aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
#1322 
Implement datastore observe with predicate api
=> chore: Implement observe with predicate API

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.19.0\nAmplify Android 0.3.0
=> release: Amplify Android 1.19.0

aws-api/src/test/java/com/amplifyframework/util/GsonFactoryTest.java
Resolves https://github.com/aws-amplify/amplify-android/issues/815
=> chore(api): add unit test to prove serialization deserialization works

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.java
*Issue #1288 *
Merge mutations when create is followed by an update.
=> fix(datastore): Merge mutations when create is followed by update

build.gradle
=> Update SDK version to 2.26.0

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.20.0\nAmplify Android 0.4.0
=> release: Amplify Android 1.20.0

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.20.1\nAmplify Android 0.4.1
=> release: Amplify Android 1.20.1

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.21.0\nAmplify Android 0.5.0
=> release: Amplify Android 1.21.0

.github/workflows/stale.yml
update the template due to the label changes
=> chore: update stale.yml

scripts/Gemfile.lock
=> chore: trying to fix release script

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.22.0\nAmplify Android 0.6.0
=> release: Amplify Android 1.22.0

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
Delete after create operation of DataStore is updated with the expected behavior.
=> Updated DataStore delete test based on expected delete behavior

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.23.0\nAmplify Android 0.7.0
=> release: Amplify Android 1.23.0

.gitignore
#1347 added another test configuration to pull from S3. Ignore this file to prevent accidental leak of confidential information.
=> chore: specify test config in gitignore

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.24.0\nAmplify Android 0.8.0
=> release: Amplify Android 1.24.0

build.gradle, core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java, core/src/main/java/com/amplifyframework/core/category/CategoryType.java, core/src/main/java/com/amplifyframework/geo/GeoCategory.java, core/src/main/java/com/amplifyframework/geo/GeoCategoryBehavior.java, core/src/main/java/com/amplifyframework/geo/GeoCategoryConfiguration.java, core/src/main/java/com/amplifyframework/geo/GeoCategoryPlugin.java, core/src/main/java/com/amplifyframework/geo/GeoException.java
Add `Geo` category to Amplify.
=> feat(geo): adds Geo category to Amplify

core/src/main/java/com/amplifyframework/core/Amplify.java, core/src/main/java/com/amplifyframework/hub/HubChannel.java
Expose static Geo category in `Amplify`.
=> feat(core): register geo category to Amplify and Hub

build.gradle
=> chore: SDK version bump

aws-geo-location/gradle.properties, maplibre-adapter/gradle.properties
=> chore(geo): add alpha version to geo

aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/SearchApiTest.kt, aws-geo-location/src/main/java/com/amplifyframework/geo/location/AWSLocationGeoPlugin.kt, core/src/main/java/com/amplifyframework/geo/models/Coordinates.java, testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousGeo.java
Add integration tests for Search API
=> Test search API

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java, aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
Adding code to create composite primary key on sqllite table when the Model has Index named "undefined".
=> Adding create composite primary key on sqllite table

aws-geo-location/gradle.properties, maplibre-adapter/gradle.properties, maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/view/support/PlaceInfoPopupView.kt, maplibre-adapter/src/main/res/values/dimens.xml
reduce the elevation of pop-up window to make "Search this area" button show up above it
=> fix(maplibre-adapter): adjust place info pop-up elevation

build.gradle
*Description of changes:* Bump the SDK version to the latest version in build.gradle.
=> Bump SDK version in build.gradle

build.gradle
=> chore: bump sdk version to 2.38.0

.github/workflows/notify_comments.yml
=> chore: notify comments on pending response issue

.github/workflows/notify_comments.yml, .github/workflows/notify_release.yml
- remove output logs
- escape single quotes
=> chore: fix webhook ghactions

.github/workflows/notify_comments.yml
=> chore: fix notify ghaction

.github/workflows/notify_comments.yml
=> chore: notify comments on closing soon issues

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java
*Issue #, if available:* #1500
Removed the UUID restriction from containedModelID
=> fix/1500-Remove the UUID restriction from persistentRecord

.github/ISSUE_TEMPLATE/2.feature_report.yaml
*Issue #, if available:* Chore
Adding a new feature request template to our repo
=> Adding a new feature request template to our repo

aws-geo-location/gradle.properties, maplibre-adapter/gradle.properties
*Description of changes:* Update the Amplify Geo plugin and MapLibre Adapter versions to 1.0.0
- [ x ] Yes (documentation PR will be created as part of the release)
=> chore(geo): Update Geo versions to 1.0.0

aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.kt
=> fix listFiles API: add prefix

aws-api/src/androidTest/java/com/amplifyframework/api/aws/GraphQLInstrumentationTest.java, aws-api/src/androidTest/java/com/amplifyframework/api/aws/RestApiInstrumentationTest.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/MultiAuthSyncEngineInstrumentationTest.java
Fix instrumentation test failing in dev-preview build.
=> fix api instrumentation test

aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/MapsApiTest.kt, aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/SearchApiTest.kt, aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageListAccessLevelTest.java, maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewTestActivityTest.kt
- Ignore failing integration tests.
- ran locally.
=> fix: Ignore failing tests to unblock dev-preview

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, rxbindings/README.md
=> Bump version to 1.36.0-dev-preview.0

README.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Version bumps for 1.35.3 (and Kotlin 0.19.3) custom release.  Yes merge, I misunderstood.
=> Version bumps

.github/ISSUE_TEMPLATE/1.bug_report.yaml, .github/ISSUE_TEMPLATE/2.feature_report.yaml
*Description of changes:* Adds the Geo category to the bug report and feature request templates.
=> chore: add geo to issue templates

CHANGELOG.md, core-kotlin/CHANGELOG.md
Would normally be created as part of the GH action
=> Update changelog after manual release v1.35.3

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java, aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTreeTest.java
Adding cascade delete support for a child model with custom primary key.
**Logs that prove deleting the parent item cascade deletes the model with custom primary key.**
```
2022-05-05 18:04:37.491 20679-20986/com.example.customprimarykey I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
2022-05-05 18:04:37.916 20679-20988/com.example.customprimarykey I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
2022-05-05 18:04:37.920 20679-20899/com.example.customprimarykey I/amplify:aws-datastore: Starting processing subscription data buffer.
2022-05-05 18:04:37.920 20679-20899/com.example.customprimarykey …
```
=> Cpk cascade delete

build.gradle
=> Update SDK version in build.gradle

build.gradle
=> chore: update gson version for dev preview

.github/workflows/notify_comments.yml
=> chore: fix gh action syntax error

.github/workflows/notify_release.yml
notify on published event (includes both release and pre-release).
=> chore: update notify_release.yml

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/1.bug_report.yaml, .github/ISSUE_TEMPLATE/2.feature_report.yaml, .github/workflows/notify_comments.yml, CHANGELOG.md, README.md, aws-api-appsync/src/main/java/com/amplifyframework/core/model/temporal/Temporal.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelFieldTypeConverter.java, build.gradle, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Correctly merge main commits into dev-preview branch before release, and bump versions to match dev-preview.
To check:
=> Dev preview update and version bump

aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java, aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactoryTest.java
appsync custom foreign key support for create mutation input variables.
- [ X] Added Unit Tests
=> Appsync mutation fk

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java, core/src/main/java/com/amplifyframework/core/model/annotations/ModelConfig.java
Fix for outbox hub event of processed.
- [ X] Tested on frontend (Add Screenshots)
- [ X] No
=> Fixing outbox event processed,

aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/ObserveQueryExecutorTest.java
=> fix: ignore flaky test

.github/workflows/closed_issue_message.yml
Add visibility warning comment when issues are closed.
=> chore: add visibility warning comment on closed issues

build.gradle
=> Bump SDK version to 2.48.0

CHANGELOG.md, README.md, core-kotlin/CHANGELOG.md, core-kotlin/gradle.properties, gradle.properties, rxbindings/README.md
Amplify Android 1.35.6
Amplify Android 0.19.6
=> release: Amplify Android 1.35.6

CONTRIBUTING.md
Add a list of guidelines to follow when creating a PR.
=> chore: add PR guidelines

build.gradle
=> Update version/Updating build.gradle to include the latest version of the aws sdk

.github/workflows/release_pr.yml
Add input field to workflow action for release tag from which next release version and changelog should be calculated.
=> chore: update release_pr.yml

.github/workflows/priority_bumper.yml, .github/workflows/project_automation.yml
- add new issues to project
- move issues to WIP column
- move issues to Todo column
- bump priority to P2
- bump priority to P1
=> chore: add GH workflow to automate projects

build.gradle
=> Update aws android sdk version in build.gradle

aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java, aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SqlCommandTest.java
=> Fix NPE when extracting primary from nested model in flutter

aws-analytics-pinpoint/build.gradle, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginBehavior.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginKt.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AnalyticsClient.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/EventRecorder.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointManager.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/Session.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/SessionClient.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/database/EventTable.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/database/PinpointDatabase.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/database/PinpointDatabaseHelper.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/AndroidAppDetails.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/AndroidDeviceDetails.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/PinpointEvent.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/PinpointSession.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/SDKInfo.kt, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/models/PinpointEventTest.kt, build.gradle
- This PR contains the initial changes for pinpoint migration including recording pinpoint event locally.
- [ -] No
=> feat: Initial changes for pinpoint migration

gradle.properties
=> Cpk version update

gradle.properties
=> version update

aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.java
[1803](https://github.com/aws-amplify/amplify-android/issues/1803)
Needs to go out with this change: https://github.com/aws-amplify/aws-sdk-android/pull/2950
TransferService is now always called to start, since mobile sdk will now shut down transfer service upon completed transfers
=> fix(storage): Always start TransferService on transfer start

aws-storage-s3/src/main/res/values/strings.xml
https://github.com/aws-amplify/amplify-android/issues/1803
Remove "Amplify" from Android notifications that show during background transfers.
=> fix(category) Update transfer message in notification

.idea/codeStyles/Project.xml, aws-api/src/main/java/com/amplifyframework/api/aws/utils/RestRequestFactory.java, aws-api/src/test/java/com/amplifyframework/api/aws/utils/RestRequestFactoryTest.java
- [ x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
*Issue #, if available:* 1830
Update the Delete REST API to ensure it would work with and without a body.
- [ x] Added Unit Tests
- [ x] No
=> Fix(API) : Update the Delete REST API to ensure it would work with and without a body

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthResetPasswordOptions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ResetPasswordUseCase.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/CodeDeliveryDetailsTypeExtensionTest.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ResetPasswordUseCaseTest.kt
Add reset password use case.
Tested e2e using a sample app and verifying that an email for reset password was sent out.
- [ x] No
=> feat(auth): add reset password

build.gradle
=> Chore(Release): Updating mobile client to the latest

build.gradle
=> Chore (Release): Updating the version to 2.50.1 for AWS SDK

aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.java
Prevents sound/vibrate on notifications
=> Fix(Storage): Reduce transfer Foreground Notification priority 

build.gradle
=> chore: update AWS SDK for Android version

aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelMetadata.java, aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/PersistentModelVersion.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/LastSyncMetadata.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java, core/src/main/java/com/amplifyframework/core/model/Model.java
=> (fix: datastore) Removing unused code.

.github/PULL_REQUEST_TEMPLATE.md
=> chore: change pull request template

aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadAccessLevelTest.java
=> chore: reenable ignored integration tests in storage

aws-analytics-pinpoint/build.gradle, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginBehavior.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginKt.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AnalyticsClient.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AutoEventSubmitter.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AutoEventSubmitterOld.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AutoSessionTracker.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AutoSessionTrackerOld.java, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/EventRecorder.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/PinpointManager.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/database/EventTable.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/database/PinpointDatabase.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/AndroidAppDetails.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/AndroidDeviceDetails.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/LocaleSerializer.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/PinpointEvent.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/PinpointSession.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/models/SDKInfo.kt, aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/targeting/endpointProfile/EndpointProfile.kt, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginBehaviorTest.kt, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/AnalyticsClientTest.kt, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/AutoSessionTrackerTest.java, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/EventRecorderTest.kt, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/database/PinpointDatabaseTest.kt, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/models/PinpointEventTest.kt
Issue #, if available:
Description of changes:
feat: Add EventSubmitter to Pinpoint
How did you test these changes?
Manually tested
[ *] Added Unit Tests
Documentation update required?
[* ] No
=> feat: Add EventSubmitter to Pinpoint

core/src/androidTest/java/com/amplifyframework/devmenu/DevMenuMainViewInstrumentationTest.java
Issue #, if available:
Description of changes:
Unignore dev menu tests, there are running successfully locally.
How did you test these changes?
Ran locally
Documentation update required?
[* ] No
=> chore: Unignore tests

aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
=> fix(data): disable failing test

scripts/run_test_in_devicefarm.sh
Run test on only one device on branch names containing dev-preview.
=> chore: run test on single device on dev-preview branch

.github/workflows/release_pr.yml
```
Scanning 16 files with 3 yaml rules.
Ran 3 rules on 16 files: 0 findings.
```
* No
=> chore: address github action

.github/workflows/codecov_code_coverage.yml, build.gradle, jacoco-config.gradle, jacoco.gradle
- Add gradle task to generate test coverage report using jacoco
- Add github actions to generate coverage report and upload test report to codecov
- Tested in [forked repo](https://github.com/saijaddhuka/amplify-android/pull/1#issuecomment-1211423962)
- No
=> chore: intgerate codecov for PR code coverage

aws-api/build.gradle, aws-auth-cognito/build.gradle, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/AuthorizationCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SRPCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInChallengeCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCustomActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/usecases/ResetPasswordUseCase.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/StateTransitionTests.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/usecases/ResetPasswordUseCaseTest.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSComprehendService.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSRekognitionService.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSTextractService.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSTranslateService.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/AbortMultiPartUploadWorker.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/CompleteMultiPartUploadWorker.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/InitiateMultiPartUploadTransferWorker.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/PartUploadTransferWorker.kt, build.gradle
- Upgrade Kotlin SDK version
- add new imports
=> chore: upgrade AWS kotlin SDK

codecov.yml
- Add codecov yml to post coverage comments on the PR
- N/A
- No
=> chore: add codecov yml

aws-auth-cognito/build.gradle, aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginInstrumentationTests.kt, aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/testutils/Credentials.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, scripts/pull_backend_config_from_s3
- Added hub events publication for sign in/ out and delete user events
_Note that delete user integration test has not been added as it will require to delete the integration test user._
=> feat(auth): publish hub events for auth

aws-datastore/src/test/java/com/amplifyframework/datastore/AWSDataStorePluginTest.java
Increased time out on latch for a unit test which was flacky.
=> chore(datastore): flaky test fix

scripts/maven-release-publisher.yml
- Run integration tests using release SDK before releasing Amplify Android
- NA
- NA
=> chore: run integration build as part of release job

build.gradle
=> chore: update build.gradle

scripts/run_test_in_devicefarm.sh
Set the max devices to 1 in dev-preview branch.
**Note: This should not be merged back to main**
=> chore : set max devices to 1 for dev-preview

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/result/AWSCognitoAuthSignOutResult.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/result/FederateToIdentityPoolResult.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
=> fix(auth): Federation order change

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/DeviceSRPCognitoSignInActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SRPCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/SRPHelper.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/SignInChallengeHelper.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/actions/DeviceSRPSignInActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/actions/SignInActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/DeviceSRPSignInEvent.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SignInEvent.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/DeviceSRPSignInState.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignInChallengeState.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignInState.kt
- add missing state transitions
- add device metadata to params for SRP actions
- fix error handling
- remove unused states, actions and events
=> fix(auth): bugfix device srp

aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignInState.kt
- handle confirm device event when sign in is complete if MFA is enabled
=> fix(auth): fix sign in with MFA enabled

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
=> fix(auth): fetch auth session fix

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/AuthenticationCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SRPCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/SignInData.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SRPEvent.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/events/SignInEvent.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignInState.kt
- [x ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
*Description of changes:*; Fixing the lambda for custom auth with SRP exposed a state machine path that was not triggered. That is fixed in this PR.
=> Fix(Auth): Fixing custom auth with SRP

core-kotlin/build.gradle, core-kotlin/src/main/java/com/amplifyframework/kotlin/storage/KotlinStorageFacade.kt, core-kotlin/src/main/java/com/amplifyframework/kotlin/storage/Storage.kt, core-kotlin/src/test/java/com/amplifyframework/kotlin/storage/KotlinStorageFacadeTest.kt, rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxStorageCategoryBehavior.java, rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java
- Add Kotlin & RxJava facade for getTransfer API
=> feat: Add kotlin and RxJava facade for getTransfer API

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPluginTest.kt
- [x ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.
Fix fetch attributes return type to return list instead of mutable list
Manually Tested
=> FIx(Auth): Fix fetch attributes return type to return list instead of mutable list

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/SignInChallengeHelper.kt
=> Chore(Auth): Remove TODO in SignInChallenge since that was already implemented

aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferRecord.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferTable.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/utils/JsonUtils.kt
- Update class visibility to internal for classes used internally.
=> chore: Update visibility for classes used internally

aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/EmotionTypeAdapter.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/adapter/GenderBinaryTypeAdapter.kt
*Description of changes:* Add missing JvmStatic annotation in predictions adapters.
=> fix(predictions): add JvmStatic annotation

aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/data/AWSCognitoLegacyCredentialStoreTest.kt
Fix for updating device metadata test on legacy credential store
=> Fix(Auth): Fix for updating device metadata test on legacy credential store

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/helpers/HostedUIHttpHelper.kt
=> fix(auth): parse token hostedui fix

aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/authstategenerators/AuthStateJsonGenerator.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/SignOutTestCaseGenerator.kt, aws-auth-cognito/src/test/java/featureTest/utilities/CognitoMockFactory.kt, aws-auth-cognito/src/test/resources/feature-test/states/SignedIn_SessionEstablished.json, aws-auth-cognito/src/test/resources/feature-test/testsuites/signIn/Test_that_SRP_signIn_invokes_proper_cognito_request_and_returns_success.json, aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_global_signOut_while_signed_in_returns_complete_with_success.json, aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_signOut_while_signed_in_returns_complete_with_success.json
=> chore(auth): Sign out tests

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/JsonGenerator.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/ConfirmSignInTestCaseGenerator.kt, aws-auth-cognito/src/test/java/featureTest/utilities/APICaptorFactory.kt, aws-auth-cognito/src/test/java/featureTest/utilities/AuthOptionsFactory.kt, aws-auth-cognito/src/test/resources/feature-test/testsuites/confirmSignIn/Test_that_SignIn_with_SMS_challenge_invokes_proper_cognito_request_and_returns_success.json
- add confirm sign in test case generator
- fix confirm sign in success result case
=> test(auth): add confirm sign in test generator

aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/ResetPasswordTestCaseGenerator.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/SignInTestCaseGenerator.kt, aws-auth-cognito/src/test/java/featureTest/utilities/CognitoMockFactory.kt, aws-auth-cognito/src/test/resources/feature-test/testsuites/resetPassword/AuthException_is_thrown_when_forgotPassword_API_call_fails.json, aws-auth-cognito/src/test/resources/feature-test/testsuites/signIn/Test_that_Device_SRP_signIn_invokes_proper_cognito_request_and_returns_success.json
=> Chore(Auth) - Add Device srp test case

aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginFeatureTest.kt, aws-auth-cognito/src/test/java/featureTest/utilities/CognitoMockFactory.kt
- Pull Android based mocks to top level such that they are mocked independent of mocks for cognito.
- Pull default mock for Amplify Credential
- Fixes delete user test case failures
=> chore(auth): common mocks for testing

aws-auth-cognito/build.gradle, build.gradle
remove dependencies in legacy sdk
=> chore: remove aws sdk dependency declarations

aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/EventRecorder.kt, build.gradle
- Bump kotlin sdk version to fix this awslabs/aws-kotlin-sdk#733
- Wrap record & submit events in try to catch.
=> chore: Fix crashes due to exception, update kotlin sdk

aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginInstrumentationTests.kt, configuration/instrumentation-tests.gradle
- Modify existing integration test to use plugin instead of SynchronousAuth
- Add test case for fetchAuthSession
=> chore(auth): add fetch auth session integration test

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmResetPasswordOptions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthConfirmSignUpOptions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignUpOptions.kt
Add missing options and definitions.
=> feat(auth): audit of missing auth options

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
Added the case for signed out to throw a signedoutexception
=> Fix(Auth): Fix for invalid state exception when the user is signed out

aws-geo-location/gradle.properties, core-kotlin/gradle.properties, core/build.gradle, gradle.properties, maplibre-adapter/gradle.properties, scripts/maven-release-publisher.yml, scripts/pull_backend_config_from_s3, scripts/run_test_in_devicefarm.sh
- Restore devicefarm run script
- Use same version number for all the libraries
=> chore: restore script changes

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/exceptions/service/GlobalSignOutException.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/SerializationTools.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/featuretest/generators/testcasegenerators/SignOutTestCaseGenerator.kt, aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_globalSignOut_returns_partial_success_with_revoke_token_error.json, aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_global_signOut_error_returns_partial_success_with_global_sign_out_error.json, aws-auth-cognito/src/test/resources/feature-test/testsuites/signOut/Test_that_signOut_returns_partial_success_with_revoke_token_error.json
=> chore(auth): Sign Out Test cases

.github/workflows/release_pr.yml
Use branch ref from workflow trigger.
=> fix: release action branch

.github/workflows/release_pr.yml
Use branch ref from workflow trigger.
=> fix: v1 release action branch ref

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignInOptions.java, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/AWSCognitoAuthSignUpOptions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/options/FederateToIdentityPoolOptions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/data/AuthConfiguration.kt
=> fix(auth): Fix authFlowType getter annotation and correct for null safety

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
=> fix(auth): Change errors returned on some apis while federated

build.gradle
=> Fix(Chore)Bump aws sdk version to 2.59

build.gradle, core/build.gradle
*Issue #, if available:* #2102
*Description of changes:* Removes an unused navigation dependency that causes a conflict when the in-app review dependency is added.
Tested manually and ran existing tests to check that dependency is unused.
=> fix(core): remove unused dynamic nav dependency

aws-geo-location/src/main/java/com/amplifyframework/geo/location/AWSLocationGeoPlugin.kt, aws-geo-location/src/main/java/com/amplifyframework/geo/location/Errors.kt, aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/AmazonLocationService.kt, aws-geo-location/src/main/java/com/amplifyframework/geo/location/service/GeoService.kt, core/src/main/java/com/amplifyframework/geo/GeoCategoryBehavior.java, core/src/main/java/com/amplifyframework/geo/options/GeoDeleteLocationHistoryOptions.java
=> Delete location history

aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/TransferOperations.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/TransferStatusUpdater.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker/DownloadWorker.kt, testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousAuth.java
=> fix: fix integration test and added logger to integration test

build.gradle
=> chore: bump aws sdk version to 2.59.1

testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousGeo.java
@sdhuka discovered that upping the timeout to 20s fixes the error locally.
=> fix(geo): Increase Geo timeout so that it runs successfully on a Pixel 3a XL

CHANGELOG.md
=> chore: update changelog for Amplify Android 2.1.0

CHANGELOG.md
=> chore: update changelog for v2.1.0

configuration/publishing.gradle
Remove unused version and group properties
These are set explicitly in the pom, and these values being present breaks using the framework as an included build
=> chore: Remove unused version and group properties

.github/pr-title-checker-config.json, CONTRIBUTING.md
=> chore: add release tag to PR title checker config

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/HostedUIClient.kt
[2234](https://github.com/aws-amplify/amplify-android/issues/2234)
=> fix(auth): Fix Authorization header for HostedUI fetchToken when appSecret is used

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Update PR template to include security checklist item

aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLOperation.java, aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java, aws-api/src/main/java/com/amplifyframework/api/aws/MultiAuthAppSyncGraphQLOperation.java, aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionEndpoint.java, aws-api/src/test/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactoryTest.java, aws-api/src/test/resources/non-json-gql-response.json, aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java, aws-datastore/src/main/java/com/amplifyframework/datastore/DataStoreConfiguration.java, aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/ConflictResolver.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationProcessor.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/RetryHandler.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java, aws-datastore/src/test/java/com/amplifyframework/datastore/DataStoreConfigurationTest.java, aws-datastore/src/test/java/com/amplifyframework/datastore/MutationProcessorRetryTest.java, aws-datastore/src/test/java/com/amplifyframework/datastore/appsync/AppSyncMocking.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/RetryHandlerTest.java, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/SyncProcessorTest.java
#2201
These are the same changes as #2201 applied to the v1 branch.
- Wrote additional unit tests
- Manual testing with emulator
- Simulation of different network conditions via a MITM (e.g. 5XX, 4XX, timeouts, connection resets, etc)
- aws-amplify/docs#4986
=> feat(datastore): Add recoverability improvements (v1)

build.gradle.kts
Fixes an error introduced in the migration to kotlin build files
=> chore: Set the signing information in project extras

configuration/publishing.gradle
=> Restore publishing sources jar

core/src/main/java/com/amplifyframework/devmenu/DeveloperMenu.java
*Issue #, if available:* #2293
*Description of changes:* Adds null checks for the logging plugin used in the developer menu.
Tested with a sample app.
=> fix(core): add null checks for dev menu logs

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/HostedUIClient.kt
https://github.com/aws-amplify/amplify-android/issues/2238
https://github.com/aws-amplify/amplify-android/issues/2302
=> fix(auth): Add hosted ui error description on token failure

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java, aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLPredicateTest.java
=> Use instr() for beginswith checking v2

aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/adapter/SQLPredicate.java, aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLPredicateTest.java
=> Use instr() for string checking v1

build.gradle
=> chore: Update AWS SDK for Android version 

CHANGELOG.md, README.md, gradle.properties, rxbindings/README.md
=> release: Amplify Android 2.5.0

maplibre-adapter/build.gradle
=> chore: upgrade gson v1 Amplify

aws-geo-location/gradle.properties, build.gradle, maplibre-adapter/gradle.properties
*Description of changes:* Update the MapLibre version to avoid duplicate class exceptions with androidx and android support libraries.
Ran existing maplibre-adapter tests and tested in a sample app.
=> fix(maplibre-adapter): update MapLibre version

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/MultiAuthSyncEngineInstrumentationTest.java, aws-datastore/src/test/java/com/amplifyframework/datastore/MutationProcessorRetryTest.java
=> chore: disable inconsistent tests

CHANGELOG.md, README.md, gradle.properties, rxbindings/README.md
=> release: Amplify Android 2.6.0

CHANGELOG.md, README.md, gradle.properties, rxbindings/README.md
* Amplify Android 2.7.0
-  [ ] No
=> release: Amplify Android 2.7.0

aws-auth-cognito/build.gradle.kts, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthService.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt, aws-core/src/main/java/com/amplifyframework/auth/AWSCognitoAuthMetadataType.kt, gradle.properties
=> chore(auth): Add internal API to add to user-agent

CHANGELOG.md, README.md, gradle.properties, rxbindings/README.md
=> release: Amplify Android 2.7.1

aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageListAccessLevelTest.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/AWSS3StoragePlugin.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/operation/AWSS3StorageListOperation.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/options/AWSS3StoragePagedListOptions.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/request/AWSS3StorageListRequest.java, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/StorageService.java, aws-storage-s3/src/test/java/com/amplifyframework/storage/s3/StorageComponentTest.java, core-kotlin/src/main/java/com/amplifyframework/kotlin/storage/KotlinStorageFacade.kt, core-kotlin/src/main/java/com/amplifyframework/kotlin/storage/Storage.kt, core-kotlin/src/test/java/com/amplifyframework/kotlin/storage/KotlinStorageFacadeTest.kt, core/src/main/java/com/amplifyframework/storage/StorageCategory.java, core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java, core/src/main/java/com/amplifyframework/storage/options/StoragePagedListOptions.java, core/src/main/java/com/amplifyframework/storage/result/StorageListResult.java, rxbindings/src/main/java/com/amplifyframework/rx/RxStorageBinding.java, rxbindings/src/main/java/com/amplifyframework/rx/RxStorageCategoryBehavior.java, rxbindings/src/test/java/com/amplifyframework/rx/RxStorageBindingTest.java, testutils/src/main/java/com/amplifyframework/testutils/sync/SynchronousStorage.java
* Deprecate existing list API's
* Add new list api with pagination support
- Added integration test
- Manually tested using pen test app
=> feat(storage): Add pagination support for list api

aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AWSCognitoAuthQueueTests.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
https://github.com/aws-amplify/amplify-android/issues/2341
=> fix(auth): Prevent auth calls from processing until configured or errored

.github/workflows/notify_comments.yml, .github/workflows/notify_release.yml
=> chore: Update notify_release.yml and notify_comments.yml

CHANGELOG.md, README.md, gradle.properties, rxbindings/README.md
=> release: Amplify Android 2.8.0

aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthValidationTest.kt, aws-auth-cognito/src/test/resources/feature-test/configuration/authconfiguration_oauth.json
Adds unit tests to validate the auth SRP/HostedUI test matrix.
=> chore(auth): Add test cases for auth validation matrix

.github/workflows/notify_comments.yml, .github/workflows/notify_release.yml
=> fix: String interpolation for workflow

CHANGELOG.md, README.md, gradle.properties, rxbindings/README.md
=> release: Amplify Android 2.8.1

aws-auth-cognito/build.gradle.kts, settings.gradle.kts
https://github.com/aws-amplify/amplify-android/issues/2416
=> fix(all) Fix non-existent aws-http version + ensure Smithy version matches one in Kotlin SDK

CHANGELOG.md, README.md, gradle.properties, rxbindings/README.md
=> release: Amplify Android 2.8.2

build.gradle
=> chore: bump SDK version

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/MultiAuthSyncEngineInstrumentationTest.java, aws-geo-location/src/androidTest/java/com/amplifyframework/geo/location/SearchApiTest.kt
*Description of changes:* Fix tests that pass locally but inconsistently pass/fail on CI due to user being signed in and then trying to sign in again or user being signed in when running a test that requires no user is signed in. Also ignores a test that passes locally but inconsistently fails on CI, pending further investigation.
Ran the tests themselves.
=> chore: fix signed in error in tests and ignore inconsistent test

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/ReachabilityMonitor.kt, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/ReachabilityMonitorTest.kt
=> @fix(data): Fix reachability debouncer causing delay on local inserts

aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java
Ignore failing DS test. Test use case verified to be working in a sample app.
=> test(datastore): ignore DS test

build.gradle
*Description of changes:* Update the AWS SDK for Android version.
=> chore: Update AWS SDK for Android version in Amplify Android v1

.github/workflows/publish_rollback.yml, .github/workflows/rollback_release.yml
Add a workflow that can quickly create a rollback release.
=> chore: Add rollback workflow

aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsCanaryTest.kt, aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsInstrumentationTest.kt, aws-analytics-pinpoint/src/androidTest/java/com/amplifyframework/analytics/pinpoint/PinpointAnalyticsStressTest.kt, aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/AWS4Signer.kt, aws-api/src/test/java/com/amplifyframework/api/aws/auth/DummyCredentialsProvider.kt, aws-core/src/main/java/com/amplifyframework/auth/AWSCredentialsProvider.kt, aws-core/src/main/java/com/amplifyframework/auth/CognitoCredentialsProvider.kt, aws-datastore/src/androidTest/java/com/amplifyframework/datastore/BasicCloudSyncInstrumentationTest.java, aws-pinpoint-core/src/main/java/com/amplifyframework/pinpoint/core/EventRecorder.kt, aws-predictions/src/androidTest/java/com/amplifyframework/predictions/aws/AmazonPollyPresigningClientTest.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/http/LivenessWebSocket.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSComprehendService.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSRekognitionService.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AmazonPollyPresigningClient.kt, aws-predictions/src/test/java/com/amplifyframework/predictions/aws/http/LivenessWebSocketTest.kt, aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/StorageStressTest.kt, aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.kt, canaries/example/build.gradle, maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewStressTest.kt, maplibre-adapter/src/androidTest/java/com/amplifyframework/geo/maplibre/MapViewTestActivityTest.kt, maplibre-adapter/src/main/java/com/amplifyframework/geo/maplibre/http/AWSRequestSignerInterceptor.kt, settings.gradle.kts
*Issue #, if available:* #2401
*Description of changes:* When using a proxy if your port is invalid it produces a crash without providing additional info from the kotlin sdk as to what the current port is. This PR will update the latest kotlin SDK which has the fix to provide more information : https://github.com/awslabs/smithy-kotlin/pull/837
=> fix(misc): bumping kotlin sdk version to include enhanced proxy exception messages

core/src/main/java/com/amplifyframework/core/model/Model.java, core/src/test/java/com/amplifyframework/core/model/ModelIdentifierTest.kt
=> fix(api): Fix getPrimaryKeyString for non-string CPK with no sort keys

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/actions/SignInChallengeCognitoActions.kt, aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/actions/SignInChallengeActions.kt
*Description of changes:* There was code that all reference to was removed as part of #2503. This is a clean up of the dead code left behind.
=> chore(auth): Remove dead code that is no longer being used

.github/workflows/codecov_code_coverage.yml, aws-api/src/test/java/com/amplifyframework/api/aws/AWSApiPluginTest.java
=> chore: fix code coverage reporting

scripts/Gemfile.lock
- Updates WEBrick dependency as per dependabot alert.
- Reran fastlane script
=> chore: Update WEBrick to 1.8.1

build.gradle
=> fix(misc): updating aws sdk version

aws-pinpoint-core/src/test/java/com/amplifyframework/pinpoint/core/TargetingClientTest.kt
Tests were inadvertently removed in previous PR.
=> fix(push): Add previously removed tests

build.gradle.kts
=> chore: Remove dokka

scripts/run_test_in_devicefarm.sh
=> chore: Update DeviceFarm Minimum

aws-predictions/src/androidTest/java/com/amplifyframework/predictions/aws/AWSPredictionsIdentifyTextTest.java, scripts/run_canary_in_devicefarm.sh
=> chore: bump min Device Farm version for canaries

CHANGELOG.md
=> Fix CHANGELOG.md for v2.14.8

.github/workflows/release_pr.yml
=> chore: use Ruby 3.0

aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.kt, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/MutationOutbox.kt, aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.kt, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.kt, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.kt
https://github.com/aws-amplify/amplify-android/issues/2667
=> fix(Datastore): Ensure proper data merger reconciliation

.github/workflows/closed_issue_message.yml
None
The AWS SDKs received some customer feedback that our closed issue message is too loud and too full of emoji. This is a slightly more polite close message. If you disagree, please disregard this PR.
No testing was performed.
=> chore: a more polite closed issue message

aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MergerTest.kt, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/MutationProcessorTest.kt, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutboxTest.kt, aws-datastore/src/test/java/com/amplifyframework/datastore/syncengine/VersionRepositoryTest.kt
=> chore(data): cleanup imports

.github/CODEOWNERS
Update CODEOWNERS such that admin team members are required to approve PRs that change the public API.
=> chore: Require admin approval for changes to .api files

aws-geo-location/build.gradle.kts, aws-geo-location/src/main/java/com/amplifyframework/geo/location/AWSLocationGeoPlugin.kt, aws-geo-location/src/main/java/com/amplifyframework/geo/location/configuration/GeoConfiguration.kt, aws-geo-location/src/main/java/com/amplifyframework/geo/location/configuration/MapsConfiguration.kt, aws-geo-location/src/main/java/com/amplifyframework/geo/location/configuration/SearchIndicesConfiguration.kt, aws-geo-location/src/test/java/com/amplifyframework/geo/location/configuration/GeoConfigurationTest.kt, core/api/core.api, testutils/src/main/java/com/amplifyframework/testutils/configuration/AmplifyOutputsDataBuilder.kt
- Configure Geo Plugin from Amplify Outputs
=> feat(geo): Configure Geo Plugin with Amplify Outputs

aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginConfiguration.java, aws-analytics-pinpoint/src/test/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPluginConfigurationTest.kt, core/src/main/java/com/amplifyframework/core/configuration/AmplifyOutputsData.kt, testutils/src/main/java/com/amplifyframework/testutils/configuration/AmplifyOutputsDataBuilder.kt
Analytics block added an additional level of nesting under an "amazonPinpoint" key
=> chore(analytics): Update shape of analytics configuration to match schema updates

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.kt, aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AuthConfiguration.kt, aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AuthConfigurationTest.kt, core/api/core.api, core/src/main/java/com/amplifyframework/core/configuration/AmplifyOutputsData.kt, core/src/test/java/com/amplifyframework/core/configuration/AmplifyOutputsDataTest.kt, testutils/src/main/java/com/amplifyframework/testutils/configuration/AmplifyOutputsDataBuilder.kt
- Configure the Auth plugin with the Gen2 config
=> feat(auth): Configure Auth Plugin when using Amplify Outputs

core/src/test/java/com/amplifyframework/core/configuration/AmplifyOutputsDataTest.kt
Update the parsing unit test to match changes in schema updates.
- additional nesting of amazonPinpoint for analytics
- split of oauth domain into cognito_domain and custom_domain
=> chore(all): Update unit tests for schema updates

configuration/instrumentation-tests.gradle
- The Gen2 canary test was removed (to be re-added later with a new backend) but missed removal from the gradle scripts file
=> chore(analytics): Fix pinpoint canary tests

.github/workflows/issue_comment.yml
This will allow surfacing the comment author to Amplify channels
=> chore: Add comment author to slack webhook payload

README.md
Verified README appears as desired.
=> chore: Add note about semantic versioning for dependency updates.

aws-pinpoint-core/build.gradle.kts, gradle/libs.versions.toml
N/A
A new version of this library was released just 2 days ago which resulted in an open PR failing because of a lint rule. 
=> chore(analytics): Update junit ktx dependency

aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AuthCanaryTest.kt, aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AuthCanaryTestGen2.kt, aws-auth-cognito/src/androidTest/java/com/amplifyframework/auth/cognito/AuthStressTests.kt
=> chore(auth): Fix tests by using proper birthdate attribute according to Cognito

scripts/Gemfile, scripts/Gemfile.lock
=> chore: update rexml

scripts/run_canary_in_devicefarm.sh, scripts/run_test_in_devicefarm.sh
=> chore: bump latest Android version for testing

.editorconfig
Newer versions of the KtLint IDE plugin respond to the ktlint_code_style setting in `.editorconfig`. Adding this rule prevents the plugin from trying to make invalid formatting changes.
=> chore: Use android studio code style

.github/workflows/issue_closed.yml
=> chore: Update issue_closed.yml

aws-predictions/src/main/java/com/amplifyframework/predictions/aws/models/FaceTargetMatchingParameters.kt, aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/RunFaceLivenessSession.kt
*Description of changes:* This adds some more attributes that we get from the backend to the data class that we send to the UI component. This will allow the Liveness UI component to not use hard coded values and use the values retrieved from backend.
*How did you test these changes?* Unit tests passed and verified the changes works on both the no light build and is backwards compatible without the no light changes.
=> feat(predictions): Add more backend-retrieved attributes to FaceTargetMatchingParams

aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/RunFaceLivenessSession.kt
We need to construct the correct streaming endpoint with correct base domain depending on the regions. Not all region belong to commercial partition so the base domain becomes different. We can keep adding new regions in this check to get the desired base domain in future. 
Tested through a isolated main program.
=> feat(predictions): Added region handling for creating correct streaming endpoint from region

aws-auth-cognito/src/main/java/com/amplifyframework/statemachine/codegen/states/SignInState.kt
=> fix(auth): Fix auto sign in with device tracking

aws-auth-cognito/src/test/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPluginTest.kt
- Fix issue with failing unit tests. The usecase may not be invoked right away.
=> fix(auth): Fix race condition in new unit tests added to AWSCognitoAuthPluginTest

aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt
This change allows signUp, confirmSignUp, and autoSignIn to proceeds if the AuthN state is SigningUp
=> fix(auth): Allow sign up, confirm sign up, and auto sign in while SigningIn

appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/Events.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsChannel.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsWebSocket.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsWebSocketProvider.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/WebSocketDisconnectReason.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/WebSocketMessage.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/utils/ConnectionTimeoutTimer.kt
=> feat(data): Events Lib WS Publishing

appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/Events.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsChannel.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/EventsWebSocket.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/RestClient.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/EventsError.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/EventsException.kt, appsync/aws-appsync-events/src/main/java/com/amplifyframework/aws/appsync/events/data/WebSocketMessage.kt
Now handling rest and ws errors the same. All exceptions thrown from lib are an `EventsException` type
=> feat(data): Events Lib consistent exception handling

appsync/aws-sdk-appsync-amplify/api/aws-sdk-appsync-amplify.api, appsync/aws-sdk-appsync-core/api/aws-sdk-appsync-core.api, appsync/aws-sdk-appsync-events/api/aws-sdk-appsync-events.api, appsync/aws-sdk-appsync-events/src/main/java/com/amazonaws/sdk/appsync/events/data/EventsException.kt
=> feat(data) Events api contract lock

.github/ISSUE_TEMPLATE/1.bug_report.yaml, .github/ISSUE_TEMPLATE/2.feature_report.yaml, .github/PULL_REQUEST_TEMPLATE.md
Various small improvements to the GitHub templates
N/A
=> chore: Update GitHub templates

appsync/aws-sdk-appsync-core/src/test/java/com/amazonaws/sdk/appsync/core/util/Iso8601TimestampTest.kt
=> fix(data): Ignore test

appsync/aws-sdk-appsync-core/src/test/java/com/amazonaws/sdk/appsync/core/util/Iso8601TimestampTest.kt, appsync/aws-sdk-appsync-events/src/androidTest/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClientAmplifyIamTests.kt, appsync/aws-sdk-appsync-events/src/androidTest/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClientAmplifyUserPoolTests.kt, appsync/aws-sdk-appsync-events/src/androidTest/java/com/amazonaws/sdk/appsync/events/testmodels/TestMessage.kt, appsync/aws-sdk-appsync-events/src/androidTest/java/com/amazonaws/sdk/appsync/events/testmodels/TestUser.kt, appsync/aws-sdk-appsync-events/src/androidTest/java/com/amazonaws/sdk/appsync/events/utils/Credentials.kt, appsync/aws-sdk-appsync-events/src/test/java/com/amazonaws/sdk/appsync/events/EventsWebSocketClientTest.kt
=> fix(data): Events licenses

scripts/pull_backend_config_from_s3
=> feat(data):  Pull Events Integration Test Data

appsync/aws-sdk-appsync-events/src/test/java/com/amazonaws/sdk/appsync/events/EventsWebSocketTest.kt
=> fix(data) Events fix test lockup

appsync/aws-sdk-appsync-events/src/main/java/com/amazonaws/sdk/appsync/events/utils/ConnectionTimeoutTimer.kt
=> fix(data) Events timeout fix

configuration/publishing.gradle, gradle.properties, settings.gradle.kts
*Description of changes:* 
Followed the migration wiki and Central Portal documentation to make these changes. After this is pushed, I'll have to also modify the build spec for the publish CodeBuild project as we need to manually tell the API "we're done uploading, start staging the repository" then we can finish our publishing flow from the UI.
Did test publishes of Amplify Android to Central Portal and validated that they showed up.
=> chore: Update sonatype endpoint for publishing

annotations/gradle.properties, build-logic/plugins/src/main/kotlin/KotlinConventionPlugin.kt
=> chore: fix jar signatures for publishing

annotations/build.gradle.kts
=> chore: fix annotation packaging

scripts/Gemfile, scripts/Gemfile.lock
=> chore: Update rexml to 3.4.2 to resolve dependabot alert
